### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by bucks9052** [charlesbel/Microsoft-Rewards-Farmer#1]
i got this error when i ran it 
Traceback (most recent call last):
  File "script.py", line 108, in <module>
    bing_search(10)
  File "script.py", line 87, in bing_search
    search_terms = get_google_trends(numberOfSearches)
  File "script.py", line 76, in get_google_trends
    google_trends = json.loads(r.text[6:])
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by charlesbel** [comment]
Fixed !
