### ISSUE TITLE
Failing quiz from the daily set

### ISSUE THREAD

**Issue by njhughesSAS** [charlesbel/Microsoft-Rewards-Farmer#10]
`DevTools listening on ws://127.0.0.1:50591/devtools/browser/79672ace-b15b-4995-b72c-85cd3ef598f4
[8396:5320:1114/082629.092:ERROR:display_layout.cc(562)] PlacementList must be sorted by first 8 bits of display_id 
Traceback (most recent call last):
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer_test.py", line 339, in <module>
    completeDailySet(browser)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer_test.py", line 229, in completeDailySet
    completeDailySetTrueOrFalse(browser, cardNumber)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer_test.py", line 183, in completeDailySetTrueOrFalse
    browser.find_element_by_xpath('//*[@id="rqStartQuiz"]').click()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 368, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="rqStartQuiz"]"}
  (Session info: chrome=86.0.4240.193)`

here is the source for the quiz page
https://gist.github.com/njhughesSAS/952ab6117942214c167b699abe46807f

**Comment by charlesbel** [comment]
If you have another day this issue, could you share me the source code of the dashboard of that day ?

**Comment by njhughesSAS** [comment]
Can do looks like it's connected to the lighting quiz or this or that everything worked on today's set
