### ISSUE TITLE
New bug in BING] Starting Desktop and Edge Bing searches... [BUG]

### ISSUE THREAD

**Issue by Vorffeed** [charlesbel/Microsoft-Rewards-Farmer#111]
When I manage to solve the other syntax problem and get it to work, now I get this other one

←[92m[PUNCH CARDS] Completed the Punch Cards successfully !←[00m
[MORE PROMO] Trying to complete More Promotions...
←[92m[MORE PROMO] Completed More Promotions successfully !←[00m
[BING] Starting Desktop and Edge Bing searches...
Traceback (most recent call last):
  File "C:\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 805, in <module>
    bingSearches(browser, remainingSearches)
  File "C:\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 272, in bingSearches
    search_terms = getGoogleTrends(numberOfSearches)
  File "C:\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 229, in getGoogleTrends
    google_trends = json.loads(r.text[6:])
  File "C:\Users\Lina\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Lina\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Lina\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Gitzzly** [comment]
Same problem here

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by link2Eps1lon** [comment]
I am using farmer version 2.0, but have same problem when starting Edge Bing searches.

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
