### ISSUE TITLE
[BUG] find_element_by_name

### ISSUE THREAD

**Issue by inverspe** [charlesbel/Microsoft-Rewards-Farmer#113]
I get this error when i run it

Traceback (most recent call last):
  File "C:\Users\ediwe\OneDrive\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\ediwe\OneDrive\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 46, in login
    browser.find_element_by_name("loginfmt").send_keys(email)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

**Comment by inverspe** [comment]
why is thing has so many god fucking problems
