### ISSUE TITLE
[BUG] i have a problem pls help me ...

### ISSUE THREAD

**Issue by ghost** [charlesbel/Microsoft-Rewards-Farmer#115]
Traceback (most recent call last):
  File "C:\Users\Theo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "g:\Mon Drive\Théo\Python\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 771, in <module>
    browser = browserSetup(True, PC_USER_AGENT)
  File "g:\Mon Drive\Théo\Python\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 35, in browserSetup
    chrome_browser_obj = webdriver.Chrome(options=options)
  File "C:\Users\Theo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Theo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\Theo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by LuckiestOne23** [comment]
Could you please provide information on selenium webdriver / browser used? As stated in the traceback part, chromedriver is not found. Have you installed it?

**Comment by MrFlappy0** [comment]
> Could you please provide information on the selenium webdriver version being used? As stated in the traceback part, chromedriver is not found. Have you installed it?

yes, but my chrome version is 105.0.5195.102 and I can't find a chrome driver related to this version, can you help me

**Comment by Andrew1644563** [comment]
In that case, you would go to the website on the README.MD on the main page of this repository and click the chrome driver link. This will send you to a website with a list of available downloads. Since your version is 105, you would click on the 105 version and click the win_32.zip file to download. Extract and place the .exe within your C:/Windows and double click to run it. Try it again after you follow the steps. Please respond if you have further issues/questions.

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git
