### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 104

### ISSUE THREAD

**Issue by RealPogger** [charlesbel/Microsoft-Rewards-Farmer#120]
I put the newest chromedriver for version 106 of chrome in C:\Windows but I get this error.
Traceback (most recent call last):
  File "C:\Users\Home\Downloads\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 771, in <module>
    browser = browserSetup(True, PC_USER_AGENT)
  File "C:\Users\Home\Downloads\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 35, in browserSetup
    chrome_browser_obj = webdriver.Chrome(options=options)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 71, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 104
Current browser version is 106.0.5249.91 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

**Comment by RealPogger** [comment]
I can't find any other place that has a old version of the chromedriver either.

**Comment by AlexyGalaxy** [comment]
Make sure you have manually logged into your bing rewards account and clicked join microsoft rewards to show you the "Microsoft Bing Dashboard". Brand new accounts have issues with the script.

You also need to check your accounts file to make sure it has correct syntax and check your main .py file to make sure it has correct syntax. If you have something out of place the script will do this. Id reccomend using Visual Studios Code. Once open it should recommend you to install a python extention. Then Visual Studios Code should recomend changes to help make the script run.

Or uninstall and redownload. Here is a README I have created for this project to help. Good Luck.

README How to Install:
-Install zip from GitHub: https://github.com/charlesbel/Microsoft-Rewards-Farmer

-Install Python https://www.python.org/downloads/
Select custom installation, change nothing hit yes until installed.

-Open Microsoft-Rewards-Farmer-master, move requirements.txt to C:\Users\Alex

-Open command prompt. win + R>CMD, then type (without quotes): 'pip install -r requirements.txt' Press enter

-Intall Google Chrome.

-Install ChromeDriver from https://chromedriver.chromium.org/downloads
Place the file in X:\Windows (X as your Windows disk letter)

-Edit the accounts.json.sample with your accounts credentials and rename it by removing .sample at the end
If you want to add more than one account, the syntax is the following :
[
{
"username": "Your Email",
"password": "Your Password"
},
{
"username": "Your Email",
"password": "Your Password"
}
]

-How to Fix Mobile:
Comment out around line 134-137 with three double quotes above and below
"""
#Refresh page
browser.get('https://bing.com/')
#Wait 5 seconds
time.sleep(10)
"""

-How to run Script:
Run the script by double clicking on ms_rewards_farmer.py

**Comment by RealPogger** [comment]
Sorry for the late response. I have tried everything you told me to do and I still get the same error. I have updated the chromedriver and put it in the right folder but I still get the error.
