### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by crjase** [charlesbel/Microsoft-Rewards-Farmer#127]
*MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE*

**Error Log**
Traceback (most recent call last):
  File "C:\Users\jason\Desktop\Bots\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

I've properly installed requests, from pip.

**Comment by NovaFlippy** [comment]
`cd /Microsoft-Rewards-Farmer-master`
`python -m pip install requests`
`py -m pip install requests`
`pip install requests`

Try after running these commands and let me know what it gives you.

**Comment by AlexyGalaxy** [comment]
> _MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE_
> 
> **Error Log** Traceback (most recent call last): File "C:\Users\jason\Desktop\Bots\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 4, in import requests ModuleNotFoundError: No module named 'requests'
> 
> I've properly installed requests, from pip.

I agree the README is out of date and too complex. I created more simple version let me know if it helps.

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
