### ISSUE TITLE
Headless true Attribute error

### ISSUE THREAD

**Issue by njhughesSAS** [charlesbel/Microsoft-Rewards-Farmer#13]
This error is produced with headless enabled

`DevTools listening on ws://127.0.0.1:53160/devtools/browser/44e64fc2-aaaf-4fc0-a6c7-cf43538c9b67
[13748:8324:1119/071644.574:ERROR:display_layout.cc(562)] PlacementList must be sorted by first 8 bits of display_id
PS C:\Users\User> & C:/Users/User/AppData/Local/Programs/Python/Python39/python.exe c:/Users/User/Documents/Microsoft-Rewards-Farmer-master/farmer_test.py
Traceback (most recent call last):
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer_test.py", line 354, in <module>
    browser = browserSetup(True, PC_USER_AGENT)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer_test.py", line 37, in browserSetup
    options.headless = True
AttributeError: can't set attribute`

The following is the Error from running headless false
`Traceback (most recent call last):
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\import time.py", line 351, in <module>
    login(browser, account['username'], account['password'])
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\import time.py", line 64, in login
    waitUntilVisible(browser, By.ID, 'KmsiCheckboxField', 10)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\import time.py", line 92, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:`

**Comment by charlesbel** [comment]
I made an update, try it :)
