### ISSUE TITLE
Cant find element

### ISSUE THREAD

**Issue by njhughesSAS** [charlesbel/Microsoft-Rewards-Farmer#15]
`DevTools listening on ws://127.0.0.1:22319/devtools/browser/372f3220-26db-4a7f-81b1-e5572ee20102
[4612:6160:1120/105556.392:ERROR:display_layout.cc(562)] PlacementList must be sorted by first 8 bits of display_id 
[4612:6160:1120/105557.576:ERROR:device_event_log_impl.cc(211)] [10:55:57.575] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[4612:6160:1120/105557.577:ERROR:device_event_log_impl.cc(211)] [10:55:57.577] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[4612:6160:1120/105724.379:ERROR:display_layout.cc(562)] PlacementList must be sorted by first 8 bits of display_id 
Traceback (most recent call last):
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\import time.py", line 370, in <module>
    completeDailySet(browser)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\import time.py", line 260, in completeDailySet
    completeDailySetTrueOrFalse(browser, cardNumber)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\import time.py", line 213, in completeDailySetTrueOrFalse        
    browser.find_element_by_xpath('//*[@id="rqStartQuiz"]').click()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 368, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="rqStartQuiz"]"}
  (Session info: chrome=87.0.4280.66)`

here is the source 
https://gist.github.com/njhughesSAS/59c68eaa928da4a902572571da0df5c3

**Comment by charlesbel** [comment]
What type of quiz was it and how much points was it rewarded ?

**Comment by njhughesSAS** [comment]
quiz
![Capture](https://user-images.githubusercontent.com/69064506/99907588-826d9880-2c92-11eb-81ec-4e3cfe7c4731.JPG)

https://gist.github.com/njhughesSAS/0fdb27462e3f557a2ebc299fac63cbef

dashboard
![Capture_dash](https://user-images.githubusercontent.com/69064506/99907631-c6609d80-2c92-11eb-8eec-09c26bdc4d02.JPG)
https://gist.github.com/njhughesSAS/8e3dd3fce2d76c4edf3f7f368cc900e9

**Comment by charlesbel** [comment]
I made an update, it should work
