### ISSUE TITLE
Page Not found error

### ISSUE THREAD

**Issue by njhughesSAS** [charlesbel/Microsoft-Rewards-Farmer#16]
Traceback (most recent call last):
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\import time.py", line 485, in <module>
    completePunchCards(browser)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\import time.py", line 360, in completePunchCards
    completePunchCard(browser, url, punchCard['childPromotions'])
    browser.execute_script("document.getElementsByClassName('offer-cta')[0].click()")
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 544, in execute_script
    return self.execute(command, {
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read property 'click' of undefined
  (Session info: chrome=87.0.4280.66)

![image](https://user-images.githubusercontent.com/69064506/100766612-ad9c6a00-33ad-11eb-8a12-07ab14e63a46.png)

**Comment by charlesbel** [comment]
I think it is an error from Microsoft side, keep this issue updated if you still face to this issue

**Comment by njhughesSAS** [comment]
The only way to complete the bot right now is commenting out the daily set

**Comment by charlesbel** [comment]
I don't understand why the bot send you to this url, it should send you to https://account.microsoft.com/rewards/dashboard/ENUS_pcparent_Holiday_punchcard
Could please go to your dashboard and send me the source code of the page ?

**Comment by njhughesSAS** [comment]
https://gist.github.com/njhughesSAS/99cf1137131175f83edbcf7f70f1de1c
here is the source for today's dashboard.

I also wanted to mention that the new way we check for headless is throwing an error I just commented it out to test the rest of the update. 
Traceback (most recent call last):
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\import time.py", line 474, in <module>
    browser = browserSetup(True, PC_USER_AGENT)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\import time.py", line 36, in browserSetup
    options.headless = True
AttributeError: can't set attribute

**Comment by charlesbel** [comment]
I can confirm that the error is from Microsoft side, it looks like microsoft send a wrong url... I have no idea why
Otherwise I fixed the headless !

**Comment by njhughesSAS** [comment]
Yep confirmed setting it the old way fixed it!

**Comment by charlesbel** [comment]
Fixed !
