### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by VanTesla** [charlesbel/Microsoft-Rewards-Farmer#182]
Traceback (most recent call last):
  File "C:\Users\13379\Documents\Tools\Microsoft-Rewards-Farmer-2.0\ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\13379\Documents\Tools\Microsoft-Rewards-Farmer-2.0\ms_rewards_farmer.py", line 46, in login
    browser.find_element_by_name("loginfmt").send_keys(email)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
