### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Real1zz** [charlesbel/Microsoft-Rewards-Farmer#183]
*MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE*

**Error Log**
Traceback (most recent call last):
  File "C:\Users\h\Desktop\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 794, in <module>
    completeDailySet(browser)
  File "C:\Users\h\Desktop\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 483, in completeDailySet
    d = getDashboardData(browser)['dailySetPromotions']
  File "C:\Users\h\Desktop\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 479, in getDashboardData
    dashboard = json.loads(dashboard)
  File "C:\Users\h\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\h\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\h\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Screenshot of the page**
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/135432931/6eb6a509-efec-4b3a-9ae2-d92d5bcf1c19)

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
