### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BeastBugha** [charlesbel/Microsoft-Rewards-Farmer#185]
[DAILY SET] Trying to complete the Daily Set...
Traceback (most recent call last):
  File "C:\Users\Jake\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 794, in <module>
    completeDailySet(browser)
  File "C:\Users\Jake\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 483, in completeDailySet
    d = getDashboardData(browser)['dailySetPromotions']
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 479, in getDashboardData
    dashboard = json.loads(dashboard)
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jake\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
