### ISSUE TITLE
[BUG] cannot create default profile directory

### ISSUE THREAD

**Issue by 8ddman** [charlesbel/Microsoft-Rewards-Farmer#196]
Traceback (most recent call last):
  File "/home/nadmin/mountarea/Microsoft-Rewards-Farmer-master/main.py", line 93, in <module>
    browser = browserSetup(account['username'], headless, False, LANG)
  File "/home/nadmin/mountarea/Microsoft-Rewards-Farmer-master/lib/browser.py", line 23, in browserSetup
    return webdriver.Chrome(options=options)
  File "/home/nadmin/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/home/nadmin/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/home/nadmin/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/nadmin/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/nadmin/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/nadmin/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot create default profile directory
Stacktrace:
#0 0xaaaaab3fa088 <unknown>
#1 0xaaaaab169808 <unknown>
#2 0xaaaaab190bac <unknown>
#3 0xaaaaab18d370 <unknown>
#4 0xaaaaab18b748 <unknown>
#5 0xaaaaab1c47cc <unknown>
#6 0xaaaaab1c41ac <unknown>
#7 0xaaaaab194aa8 <unknown>
#8 0xaaaaab195a04 <unknown>
#9 0xaaaaab3c0aec <unknown>
#10 0xaaaaab3c36b0 <unknown>
#11 0xaaaaab3c3c88 <unknown>
#12 0xaaaaab3cb6e4 <unknown>
#13 0xaaaaab3c42dc <unknown>
#14 0xaaaaab39eda0 <unknown>
#15 0xaaaaab3e2e98 <unknown>
#16 0xaaaaab3e3028 <unknown>
#17 0xaaaaab3f26c4 <unknown>
#18 0xffffb9451648 start_thread
#19 0xffffb8f7ac1c <unknown>

**Comment by charlesbel** [comment]
What's your Linux version ?

**Comment by charlesbel** [comment]
Fixed by #216
