### ISSUE TITLE
[BUG] Title

### ISSUE THREAD

**Issue by xegyms** [charlesbel/Microsoft-Rewards-Farmer#204]
*MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE*

**Error Log**
Traceback (most recent call last):
  File "/Users/damon/Downloads/Microsoft-Rewards-Farmer-master/main.py", line 93, in <module>
    browser = browserSetup(account['username'], headless, False, LANG)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/damon/Downloads/Microsoft-Rewards-Farmer-master/lib/browser.py", line 23, in browserSetup
    return webdriver.Chrome(options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 110.0.5481.177 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Stacktrace:
0   chromedriver                        0x0000000100957f48 chromedriver + 4226888
1   chromedriver                        0x00000001009504f4 chromedriver + 4195572
2   chromedriver                        0x0000000100594d68 chromedriver + 281960
3   chromedriver                        0x00000001005c0bac chromedriver + 461740
4   chromedriver                        0x00000001005bcfd8 chromedriver + 446424
5   chromedriver                        0x00000001005ba150 chromedriver + 434512
6   chromedriver                        0x00000001005f793c chromedriver + 686396
7   chromedriver                        0x00000001005f7164 chromedriver + 684388
8   chromedriver                        0x00000001005c3f1c chromedriver + 474908
9   chromedriver                        0x00000001005c4ef4 chromedriver + 478964
10  chromedriver                        0x000000010091959c chromedriver + 3970460
11  chromedriver                        0x000000010091d6f0 chromedriver + 3987184
12  chromedriver                        0x00000001009235b4 chromedriver + 4011444
13  chromedriver                        0x000000010091e2fc chromedriver + 3990268
14  chromedriver                        0x00000001008f61c0 chromedriver + 3826112
15  chromedriver                        0x000000010093a088 chromedriver + 4104328
16  chromedriver                        0x000000010093a1e0 chromedriver + 4104672
17  chromedriver                        0x0000000100949f28 chromedriver + 4169512
18  libsystem_pthread.dylib             0x000000018897bfa8 _pthread_start + 148
19  libsystem_pthread.dylib             0x0000000188976da0 thread_start + 8

**Screenshot of the page**
<img width="1680" alt="Screenshot 2023-07-24 at 8 53 32 pm" src="https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/139342700/d34b1925-2a20-4daa-851c-dd5d96cb8c63">

**Value of dashboard variable**
Open the source code of the [Microsoft Rewards Dashboard Page](https://rewards.bing.com), search for <pre>var dashboard = </pre>
Copy the whole json of this line and paste it on [Gist](https://gist.github.com). Then share me the link of the gist here.

**Comment by charlesbel** [comment]
You just need to read the error bro:

This version of ChromeDriver only supports Chrome version 114
Current browser version is 110.0.5481.177 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

You downloaded the wrong chromedriver...
