### ISSUE TITLE
[BUG] Cannot use

### ISSUE THREAD

**Issue by iMayday-Yee** [charlesbel/Microsoft-Rewards-Farmer#234]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

PS G:\User\Desktop\Microsoft-Rewards-Farmer-master> python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 11, in <module>
    from src.userAgentGenerator import GenerateUserAgent
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\userAgentGenerator.py", line 9, in <module>
    class GenerateUserAgent:
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\userAgentGenerator.py", line 41, in GenerateUserAgent
    browserVersions: dict[str, Any] = {}
TypeError: 'type' object is not subscriptable

### Copy and paste your error

PS G:\User\Desktop\Microsoft-Rewards-Farmer-master> python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 11, in <module>
    from src.userAgentGenerator import GenerateUserAgent
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\userAgentGenerator.py", line 9, in <module>
    class GenerateUserAgent:
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\userAgentGenerator.py", line 41, in GenerateUserAgent
    browserVersions: dict[str, Any] = {}
TypeError: 'type' object is not subscriptable

### Screenshot of the bug

PS G:\User\Desktop\Microsoft-Rewards-Farmer-master> python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 11, in <module>
    from src.userAgentGenerator import GenerateUserAgent
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\userAgentGenerator.py", line 9, in <module>
    class GenerateUserAgent:
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\userAgentGenerator.py", line 41, in GenerateUserAgent
    browserVersions: dict[str, Any] = {}
TypeError: 'type' object is not subscriptable

### Value of dashboard variable

PS G:\User\Desktop\Microsoft-Rewards-Farmer-master> python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 11, in <module>
    from src.userAgentGenerator import GenerateUserAgent
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\userAgentGenerator.py", line 9, in <module>
    class GenerateUserAgent:
  File "G:\User\Desktop\Microsoft-Rewards-Farmer-master\src\userAgentGenerator.py", line 41, in GenerateUserAgent
    browserVersions: dict[str, Any] = {}
TypeError: 'type' object is not subscriptable

**Comment by charlesbel** [comment]
You must upgrade to python 3.9 or later
