### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by Pilotkosinus** [charlesbel/Microsoft-Rewards-Farmer#239]
Good day

I am trying to run the program on an AWS Kali Linux server. I always get an error message. The time and date of my server are set correctly. On my Windows machine everything runs without problems. 

`Traceback (most recent call last):

  File "/home/kali/Microsoft-Rewards-Farmer/main.py", line 110, in <module>
    main()
    
  File "/home/kali/Microsoft-Rewards-Farmer/main.py", line 15, in main
    executeBot(loadedAccounts)
    
  File "/home/kali/Microsoft-Rewards-Farmer/main.py", line 71, in executeBot
    with Browser(
         ^^^^^^^^
         
  File "/home/kali/Microsoft-Rewards-Farmer/src/browser.py", line 27, in __init__
    self.utils = Utils(self.webdriver, f"{self.localeLang}_{self.localeGeo}")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 
  File "/home/kali/Microsoft-Rewards-Farmer/src/utils.py", line 18, in __init__
    pylocale.setlocale(pylocale.LC_NUMERIC, locale)
    
  File "/usr/lib/python3.11/locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           
locale.Error: unsupported locale setting`

**Comment by udu3324** [comment]
I think this issue is related to #233

**Comment by charlesbel** [comment]
Fixed it !

**Comment by Pilotkosinus** [comment]
So I recloned the repo but still got the error. 

`
Traceback (most recent call last):

  File "/home/kali/Microsoft-Rewards-Farmer/main.py", line 110, in <module>
    main()
    
  File "/home/kali/Microsoft-Rewards-Farmer/main.py", line 15, in main
    executeBot(loadedAccounts)
    
  File "/home/kali/Microsoft-Rewards-Farmer/main.py", line 71, in executeBot
    with Browser(
         ^^^^^^^^
         
  File "/home/kali/Microsoft-Rewards-Farmer/src/browser.py", line 27, in __init__
    self.utils = Utils(self.webdriver)
                 ^^^^^^^^^^^^^^^^^^^^^
                 
  File "/home/kali/Microsoft-Rewards-Farmer/src/utils.py", line 18, in __init__
    pylocale.setlocale(pylocale.LC_NUMERIC, pylocale.getdefaultlocale()[0])
  File "/usr/lib/python3.11/locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           
locale.Error: unsupported locale setting
`

**Comment by Pilotkosinus** [comment]
> Fixed it !

So I recloned the repo but still got the error.

`
Traceback (most recent call last):

File "/home/kali/Microsoft-Rewards-Farmer/main.py", line 110, in
main()

File "/home/kali/Microsoft-Rewards-Farmer/main.py", line 15, in main
executeBot(loadedAccounts)

File "/home/kali/Microsoft-Rewards-Farmer/main.py", line 71, in executeBot
with Browser(
^^^^^^^^

File "/home/kali/Microsoft-Rewards-Farmer/src/browser.py", line 27, in init
self.utils = Utils(self.webdriver)
^^^^^^^^^^^^^^^^^^^^^

File "/home/kali/Microsoft-Rewards-Farmer/src/utils.py", line 18, in init
pylocale.setlocale(pylocale.LC_NUMERIC, pylocale.getdefaultlocale()[0])
File "/usr/lib/python3.11/locale.py", line 626, in setlocale
return _setlocale(category, locale)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

locale.Error: unsupported locale setting
`

**Comment by pilonull** [comment]
Yea, I'm also running in to this error. On ubuntu 22.04 LTS

have tried with python3.10 and 3.11

**Comment by charlesbel** [comment]
I understand why, because there is no env variable declared on your machines, so I handled it in the script, try it !

**Comment by pilonull** [comment]
> I understand why, because there is no env variable declared on your machines, so I handled it in the script, try it !

Pulled the latest zip from the releases page and the error is still occurring.
Also tried downloading code zip and same issue. 


```
python3.10: 

alex@Ubuntu-Plex:~/Desktop/Microsoft-Rewards-Farmer-master$ python3 main.py 
********************{ asdfasdfwer@gmail.com }********************
Traceback (most recent call last):
  File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 110, in <module>
    main()
  File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 15, in main
    executeBot(loadedAccounts)
  File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 71, in executeBot
    with Browser(
  File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/src/browser.py", line 27, in __init__
    self.utils = Utils(self.webdriver)
  File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/src/utils.py", line 20, in __init__
    pylocale.setlocale(pylocale.LC_NUMERIC, locale)
  File "/usr/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

python3.11:

alex@Ubuntu-Plex:~/Desktop/Microsoft-Rewards-Farmer-master$ python3.11 main.py 
********************{ apasdfasdfy@gmail.com }********************
Traceback (most recent call last):
  File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 110, in <module>
    main()
  File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 15, in main
    executeBot(loadedAccounts)
  File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 71, in executeBot
    with Browser(
         ^^^^^^^^
  File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/src/browser.py", line 27, in __init__
    self.utils = Utils(self.webdriver)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/src/utils.py", line 20, in __init__
    pylocale.setlocale(pylocale.LC_NUMERIC, locale)
  File "/usr/lib/python3.11/locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting

```

**Comment by charlesbel** [comment]
> > I understand why, because there is no env variable declared on your machines, so I handled it in the script, try it !
> 
> Pulled the latest zip from the releases page and the error is still occurring. Also tried downloading code zip and same issue.
> 
> ```
> python3.10: 
> 
> alex@Ubuntu-Plex:~/Desktop/Microsoft-Rewards-Farmer-master$ python3 main.py 
> ********************{ asdfasdfwer@gmail.com }********************
> Traceback (most recent call last):
>   File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 110, in <module>
>     main()
>   File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 15, in main
>     executeBot(loadedAccounts)
>   File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 71, in executeBot
>     with Browser(
>   File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/src/browser.py", line 27, in __init__
>     self.utils = Utils(self.webdriver)
>   File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/src/utils.py", line 20, in __init__
>     pylocale.setlocale(pylocale.LC_NUMERIC, locale)
>   File "/usr/lib/python3.10/locale.py", line 620, in setlocale
>     return _setlocale(category, locale)
> locale.Error: unsupported locale setting
> 
> python3.11:
> 
> alex@Ubuntu-Plex:~/Desktop/Microsoft-Rewards-Farmer-master$ python3.11 main.py 
> ********************{ apasdfasdfy@gmail.com }********************
> Traceback (most recent call last):
>   File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 110, in <module>
>     main()
>   File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 15, in main
>     executeBot(loadedAccounts)
>   File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/main.py", line 71, in executeBot
>     with Browser(
>          ^^^^^^^^
>   File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/src/browser.py", line 27, in __init__
>     self.utils = Utils(self.webdriver)
>                  ^^^^^^^^^^^^^^^^^^^^^
>   File "/home/alex/Desktop/Microsoft-Rewards-Farmer-master/src/utils.py", line 20, in __init__
>     pylocale.setlocale(pylocale.LC_NUMERIC, locale)
>   File "/usr/lib/python3.11/locale.py", line 626, in setlocale
>     return _setlocale(category, locale)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> locale.Error: unsupported locale setting
> ```

What do you get when you run in python 
```
import locale
locale.getdefaultlocale()
```
?

**Comment by pilonull** [comment]
> What do you get when you run in python
> 
> ```
> import locale
> locale.getdefaultlocale()
> ```
> 
> ?

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/8344590/ab4b68aa-add9-4135-87d0-6c7a2af90916)

**Comment by pilonull** [comment]
Also: 

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/8344590/f436977f-abf8-412e-858e-f34dc5e1b44e)

**Comment by Pilotkosinus** [comment]
![Unbenannt](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/45830242/02e52029-2fa7-4c40-9ab6-ebaf7d8ae589)

**Comment by Pilotkosinus** [comment]
![Unbenannt](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/45830242/eb2ece27-5331-48a2-8f4d-7c365fa9786a)

**Comment by EricThunder** [comment]
Getting the exact same issue with the exact same output of the above commands as other people
