### ISSUE TITLE
Selenium Error

### ISSUE THREAD

**Issue by njhughesSAS** [charlesbel/Microsoft-Rewards-Farmer#25]
`[DAILY SET] Completing quiz of card 2
Traceback (most recent call last):
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\new_update.py", line 563, in <module>
    completeDailySet(browser)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\new_update.py", line 391, in completeDailySet
    completeDailySetVariableActivity(browser, cardNumber)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\new_update.py", line 303, in completeDailySetVariableActivity
    waitUntilVisible(browser, By.XPATH, '//*[@id="currentQuestionContainer"]/div/div[1]', 10)
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\test\new_update.py", line 136, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:`

source:
https://gist.github.com/njhughesSAS/7388685682efe886cb1aa7a96ba5adba

dashboard
![image](https://user-images.githubusercontent.com/69064506/101949619-c0325280-3ba8-11eb-89b8-5d22940453f2.png)

xPATH for test your smarts
/html/body/div[1]/div[2]/main/div/ui-view/mee-rewards-dashboard/main/div/mee-rewards-daily-set-section/div/mee-card-group[1]/div/mee-card[2]/div/card-content/mee-rewards-daily-set-item-content/div/div[2]/p

**Comment by charlesbel** [comment]
Thanks, I just fixed it ! 👍
