### ISSUE TITLE
[BUG] Chrome No Longer Running

### ISSUE THREAD

**Issue by gardncol** [charlesbel/Microsoft-Rewards-Farmer#250]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

Environment: Ubuntu Server 22.04
Python Version: 3.10.12

After upgrading to the new version of the application, I get a chrome no longer running error.

Steps to reproduce:

1. Download latest zip from release
2. Decompress release
3. Migrate old accounts.json to new uncompressed directory
4. python3 main.py

### Copy and paste your error

Traceback (most recent call last):
  File "/home/USER/Github/New-Microsoft-Rewards-Farmer/Microsoft-Rewards-Farmer-master/main.py", line 110, in <module>
    main()
  File "/home/USER/Github/New-Microsoft-Rewards-Farmer/Microsoft-Rewards-Farmer-master/main.py", line 15, in main
    executeBot(loadedAccounts)
  File "/home/USER/Github/New-Microsoft-Rewards-Farmer/Microsoft-Rewards-Farmer-master/main.py", line 71, in executeBot
    with Browser(
  File "/home/USER/Github/New-Microsoft-Rewards-Farmer/Microsoft-Rewards-Farmer-master/src/browser.py", line 26, in __init__
    self.webdriver = self.browserSetup()
  File "/home/USER/Github/New-Microsoft-Rewards-Farmer/Microsoft-Rewards-Farmer-master/src/browser.py", line 52, in browserSetup
    return webdriver.Chrome(options=options)
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/USER/.cache/selenium/chrome/linux64/115.0.5790.170/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x562cbd744613 <unknown>
#1 0x562cbd470537 <unknown>
#2 0x562cbd49b588 <unknown>
#3 0x562cbd4985d9 <unknown>
#4 0x562cbd4d8643 <unknown>
#5 0x562cbd4d7d8f <unknown>
#6 0x562cbd4cf803 <unknown>
#7 0x562cbd4a368b <unknown>
#8 0x562cbd4a442e <unknown>
#9 0x562cbd705c28 <unknown>
#10 0x562cbd709af7 <unknown>
#11 0x562cbd71401c <unknown>
#12 0x562cbd70a723 <unknown>
#13 0x562cbd6d9457 <unknown>
#14 0x562cbd72e628 <unknown>
#15 0x562cbd72e7b7 <unknown>
#16 0x562cbd73d483 <unknown>
#17 0x7f4e1e61ab43 <unknown>

### Screenshot of the bug

Traceback (most recent call last):
  File "/home/USER/Github/New-Microsoft-Rewards-Farmer/Microsoft-Rewards-Farmer-master/main.py", line 110, in <module>
    main()
  File "/home/USER/Github/New-Microsoft-Rewards-Farmer/Microsoft-Rewards-Farmer-master/main.py", line 15, in main
    executeBot(loadedAccounts)
  File "/home/USER/Github/New-Microsoft-Rewards-Farmer/Microsoft-Rewards-Farmer-master/main.py", line 71, in executeBot
    with Browser(
  File "/home/USER/Github/New-Microsoft-Rewards-Farmer/Microsoft-Rewards-Farmer-master/src/browser.py", line 26, in __init__
    self.webdriver = self.browserSetup()
  File "/home/USER/Github/New-Microsoft-Rewards-Farmer/Microsoft-Rewards-Farmer-master/src/browser.py", line 52, in browserSetup
    return webdriver.Chrome(options=options)
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/USER/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/USER/.cache/selenium/chrome/linux64/115.0.5790.170/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x562cbd744613 <unknown>
#1 0x562cbd470537 <unknown>
#2 0x562cbd49b588 <unknown>
#3 0x562cbd4985d9 <unknown>
#4 0x562cbd4d8643 <unknown>
#5 0x562cbd4d7d8f <unknown>
#6 0x562cbd4cf803 <unknown>
#7 0x562cbd4a368b <unknown>
#8 0x562cbd4a442e <unknown>
#9 0x562cbd705c28 <unknown>
#10 0x562cbd709af7 <unknown>
#11 0x562cbd71401c <unknown>
#12 0x562cbd70a723 <unknown>
#13 0x562cbd6d9457 <unknown>
#14 0x562cbd72e628 <unknown>
#15 0x562cbd72e7b7 <unknown>
#16 0x562cbd73d483 <unknown>
#17 0x7f4e1e61ab43 <unknown>

### Value of dashboard variable

            var dashboard = {"userStatus":{"levelInfo":{"activeLevel":"Level1","activeLevelName":"Level 1","progress":0,"progressMax":500,"levels":[{"key":"Level1","active":true,"name":"Level 1","tasks":[{"text":"Free and included with your Microsoft account","url":null}],"privileges":[{"text":"5 points per Bing Search, up to 50 points per day","url":"//www.bing.com/?FORM=MA1368"},{"text":"1 point per $1 spent in Microsoft Store, plus earn bonus points on select purchases","url":"//www.microsoftstore.com"},{"text":"Points for exploring offers from Microsoft Rewards","url":"/rewards/dashboard"},{"text":"Access to member sales and discounts","url":null},{"text":"Redeem your points for gift cards, sweepstakes entries, or donate them to charity","url":"/rewards/redeem"}]},{"key":"Level2","active":false,"name":"Level 2","tasks":[{"text":"Earn at least 500 points each month","url":null}],"privileges":[{"text":"5 points per Bing Search, up to 250 points per day","url":"//www.bing.com/?FORM=MA1368"},{"text":"Level 1 Microsoft Store benefits, plus exclusive Level 2 bonus offers","url":null},{"text":"Points for exploring offers from Microsoft Rewards","url":"/rewards/dashboard"},{"text":"Access to member sales and discounts, with exclusives for Level 2 members","url":null},{"text":"Get up to 10% off when redeeming rewards from Microsoft brands","url":null}]}],"benefitsPromotion":{"benefits":[{"key":"BingSearch","text":"Daily Bing search point limit (5 points per search)*","url":"https://www.bing.com/?FORM=MA1368","helpText":"* The Level 2 Bing search benefit is the sum of 150 points on PC and 100 points on mobile","supportedLevels":{"level1":"50","level2":"250","level2XBoxGold":"250"}},{"key":"EdgeSearch","text":"Bing search bonus daily cap for Microsoft Edge ","url":"https://www.microsoft.com/rewards/edge-bonus?form=ML18S8\u0026OCID=ML18S8\u0026rtc=1","helpText":null,"supportedLevels":{"level1":"5","level2":"20","level2XBoxGold":"20"}},{"key":"PointsDollarSpent","text":"Points earned per $ spent in Microsoft Store online**","url":"https://www.microsoft.com/store/b/home?rtc=1","helpText":"**Qualifying content only. \u003ca class=\u0027c-hyperlink\u0027 href=\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\u0027\u003eSee more\u003c/a\u003e for details.","supportedLevels":{"level1":"1:1","level2":"10:1","level2XBoxGold":"20:1"}},{"key":"PointsSeeDailyOffers","text":"Points for exploring daily offers","url":"https://account.microsoft.com/rewards","helpText":null,"supportedLevels":{"level1":"","level2":"","level2XBoxGold":""}},{"key":"MemberDiscounts","text":"Access to exclusive member sales and discounts","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"MemberInvites","text":"Occasional surprise invites to exclusive member-only events","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"RedeemOff","text":"Up to 10% off when redeeming from Microsoft brands","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}}],"supportedLevelKeys":["level1","level2","level2XBoxGold"],"supportedLevelTitles":["Level 1","Level 2","Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Live Gold\u003c/span\u003e"],"supportedLevelTitlesMobile":["Level 1","Level 2","Level 2 +Xbox Live Gold"],"activeLevel":"level1","name":"level_benefits","priority":1,"attributes":{"hidden":"True","benefits":"[{ key: \u0027BingSearch\u0027, text: \u0027Daily Bing search point limit (5 points per search)*\u0027, url: \u0027https://www.bing.com/?FORM=MA1368\u0027, helpText: \u0027* The Level 2 Bing search benefit is the sum of 150 points on PC and 100 points on mobile\u0027, supportedLevels: { \u0027level1\u0027: \u002750\u0027, \u0027level2\u0027: \u0027250\u0027, level2XBoxGold: \u0027250\u0027 } }, { key: \u0027EdgeSearch\u0027, text: \u0027Bing search bonus daily cap for Microsoft Edge \u0027, url: \u0027https://www.microsoft.com/rewards/edge-bonus?form=ML18S8\u0026OCID=ML18S8\u0026rtc=1\u0027, supportedLevels: { \u0027level1\u0027: \u00275\u0027, \u0027level2\u0027: \u002720\u0027, level2XBoxGold: \u002720\u0027 } }, { key: \u0027PointsDollarSpent\u0027, text: \u0027Points earned per $ spent in Microsoft Store online**\u0027, url: \u0027https://www.microsoft.com/store/b/home?rtc=1\u0027, helpText: \u0027**Qualifying content only. \u003ca class=\\\u0027c-hyperlink\\\u0027 href=\\\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\\\u0027\u003eSee more\u003c/a\u003e for details.\u0027, supportedLevels: { \u0027level1\u0027: \u00271:1\u0027, \u0027level2\u0027: \u002710:1\u0027, level2XBoxGold: \u002720:1\u0027 } }, { key: \u0027PointsSeeDailyOffers\u0027, text: \u0027Points for exploring daily offers\u0027, url: \u0027https://account.microsoft.com/rewards\u0027, supportedLevels: { \u0027level1\u0027: \u0027\u0027, \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 } }, { key: \u0027MemberDiscounts\u0027, text: \u0027Access to exclusive member sales and discounts\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }  }, { key: \u0027MemberInvites\u0027, text: \u0027Occasional surprise invites to exclusive member-only events\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}, { key: \u0027RedeemOff\u0027, text: \u0027Up to 10% off when redeeming from Microsoft brands\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}]","supportedLevelKeys":"level1;level2;level2XBoxGold","supportedLevelTitle":"Level 1;Level 2;Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Live Gold\u003c/span\u003e","levelTitleMobile":"Level 1;Level 2;Level 2 +Xbox Live Gold","activeLevel":"level1","give_eligible":"False","destination":""},"offerId":"","complete":false,"counter":0,"activityProgress":0,"activityProgressMax":0,"pointProgressMax":0,"pointProgress":0,"promotionType":"","promotionSubtype":"","title":"","extBannerTitle":"","titleStyle":"","theme":"","description":"","extBannerDescription":"","descriptionStyle":"","showcaseTitle":"","showcaseDescription":"","imageUrl":"","dynamicImage":"","smallImageUrl":"","backgroundImageUrl":"","showcaseBackgroundImageUrl":"","showcaseBackgroundLargeImageUrl":"","promotionBackgroundLeft":"","promotionBackgroundRight":"","iconUrl":"","animatedIconUrl":"","animatedLargeBackgroundImageUrl":"","destinationUrl":"","linkText":"","hash":"53b28ef7f02a15ccbb5b13e737b1ea7b4998ba9b611090e43e25a4e5f224c0da","activityType":"11","isRecurring":false,"isHidden":true,"isTestOnly":false,"isGiveEligible":false,"level":"","slidesCount":0,"legalText":"","legalLinkText":"","deviceType":""}},"availablePoints":105183,"lifetimePoints":149183,"lifetimePointsRedeemed":44000,"ePuid":"31_WKMLXqC6ECB0fbkumh177KsNZfF0MeuM0KmdBYUsKQ-Rco6BtnCUrxAh-XvXm_4hSf7tAl8KqUToG5a9Nbw","redeemGoal":{"name":"000400000331","price":42000,"provider":"tango","disabled":false,"category":"Shop","title":"Xbox Game Pass Ultimate - 3 months","variableGoalSpecificTitle":"","smallImageUrl":"small/000400000330_142x142.png","mediumImageUrl":"medium/000400000330_262x164.png","largeImageUrl":"large/000400000330_310x216.png","largeShowcaseImageUrl":"showcasev2/000400000330_644x360.png","description":{"itemGroupText":"3 months","smallText":"","largeText":"\u003cdiv class=\u0022prizeText\u0022\u003e\u003cp\u003eGet all the benefits of Xbox Live Gold, plus\u0026nbsp;over 100 high-quality console and PC games.\u0026nbsp;With games added all the time, there’s always something new to play.\u0026nbsp;With a huge variety of games from every genre, there’s something for everyone.\u0026nbsp;Enjoy\u0026nbsp;exclusive member deals and discounts.\u0026nbsp;Play together with friends on the most advanced multiplayer network and discover your next favorite game.\u0026nbsp;\u003c/p\u003e\u003cp class=\u0022SmallFont\u0022\u003eNote:\u0026nbsp;Use your active Xbox Game Pass Ultimate membership to play games on Xbox One and Windows 10 PC. Xbox Game Pass Ultimate includes Xbox Game Pass for Console, Xbox Game Pass for PC, Xbox Live Gold and additional benefits.\u0026nbsp;Note:\u0026nbsp;Purchase of Xbox Game Pass Ultimate automatically upgrades your existing Xbox Live Gold or Xbox Game Pass membership(s) to Xbox Game Pass Ultimate at a conversion ratio each based on days remaining. Learn how this works at \u003ca href=\u0022https://www.xbox.com/en-US/xbox-game-pass\u0022 rel=\u0022noopener noreferrer\u0022 target=\u0022_blank\u0022\u003ewww.xbox.com/gamepass\u003c/a\u003e. Future code redemptions are also subject to a conversion ratio. Conversion ratio subject to change. All conversions to Xbox Game Pass Ultimate are final: Once converted, you cannot re-convert your Xbox Game Pass Ultimate membership back to a previous membership.\u0026nbsp;Maximum 36 months of redeemed\u0026nbsp;Xbox Game Pass Ultimate per account at a time, including any converted time from Xbox Live Gold and/or Xbox Game Pass (for PC or console).\u003c/p\u003e\u003cp class=\u0022SmallFont\u0022\u003eGame titles and number vary over time and by country. Membership continues to be charged at the then-current price (subject to change; plus applicable taxes) unless cancelled. Cancel anytime to stop your next scheduled charge; see \u003ca href=\u0022https://www.account.microsoft.com/services\u0022 rel=\u0022noopener noreferrer\u0022 target=\u0022_blank\u0022\u003eaccount.microsoft.com/services\u003c/a\u003e. Notice before purchase of add-ons, DLC, consumables, virtual currency, or subscriptions (sold separately): If your membership terminates or a game is removed from the catalog, you must reactivate your membership or buy the game separately to continue using these items. ISP f…

**Comment by charlesbel** [comment]
Do you have a display on your machine ? Did you run the program headless ?

**Comment by gardncol** [comment]
The program was run headless. I do not have a display attached to this computer.

**Comment by gardncol** [comment]
I ran the program as my user on the Linux box. If my use case isn't a supported one, totally get it. I can try something else.

**Comment by charlesbel** [comment]
You can also add after line 62 of src/browser.py an `options.add_argument("--no-sandbox")`, should solve the problem
