### ISSUE TITLE
Program stops mid search

### ISSUE THREAD

**Issue by Lectoid** [charlesbel/Microsoft-Rewards-Farmer#252]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

I have a few accounts, today though the search seems to stop with the below error. I tried searching through the closed issues, but not sure what I'm even looking for.

### Copy and paste your error

[BING] 10/20
[BING] 11/20
[BING] 12/20
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 110, in <module>
    main()
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 15, in main
    executeBot(loadedAccounts)
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 97, in executeBot
    accountPointsCounter = Searches(mobileBrowser).bingSearches(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\src\searches.py", line 60, in bingSearches
    points = self.bingSearch(word)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\src\searches.py", line 83, in bingSearch
    return self.browser.utils.getBingAccountPoints()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\src\utils.py", line 127, in getBingAccountPoints
    data = self.getBingInfo()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\src\utils.py", line 111, in getBingInfo
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master>

### Screenshot of the bug

n/a

### Value of dashboard variable

n/a

**Comment by charlesbel** [comment]
Fixed !
