### ISSUE TITLE
[BUG] no module named seleniumwire

### ISSUE THREAD

**Issue by gh0sti** [charlesbel/Microsoft-Rewards-Farmer#256]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

I installed selenium chrome browser and instructed on the main page and updated the farmer to latest commit that was published this morning. This is the error I get.

### Copy and paste your error

C:\Users\gh0sti\Downloads\MRF 3.0.5>python main.py
Traceback (most recent call last):
  File "C:\Users\gh0sti\Downloads\MRF 3.0.5\main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "C:\Users\gh0sti\Downloads\MRF 3.0.5\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "C:\Users\gh0sti\Downloads\MRF 3.0.5\src\browser.py", line 9, in <module>
    import seleniumwire.undetected_chromedriver as webdriver
ModuleNotFoundError: No module named 'seleniumwire'

### Screenshot of the bug

none

### Value of dashboard variable

review error from cmd

**Comment by charlesbel** [comment]
You need to run again ``pip install -r requirements.txt``

**Comment by gh0sti** [comment]
C:\Users\gh0sti\Downloads\MRF306>python main.py
Traceback (most recent call last):
  File "C:\Users\gh0sti\Downloads\MRF306\main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "C:\Users\gh0sti\Downloads\MRF306\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "C:\Users\gh0sti\Downloads\MRF306\src\browser.py", line 9, in <module>
    import seleniumwire.undetected_chromedriver as webdriver
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 12, in <module>
    from seleniumwire.inspect import InspectRequestsMixin
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\inspect.py", line 7, in <module>
    from seleniumwire import har
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\har.py", line 12, in <module>
    from seleniumwire.thirdparty.mitmproxy.http import HTTPFlow
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\http.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import http
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\__init__.py", line 1, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import http1, http2, multipart, status_codes
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\__init__.py", line 2, in <module>
    from .read import (connection_close, expected_http_body_size, read_body, read_request, read_request_head,
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\http1\read.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import (headers, request,
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\request.py", line 8, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import cookies, message, multipart
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\message.py", line 6, in <module>
    from seleniumwire.thirdparty.mitmproxy.net.http import encoding
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\http\encoding.py", line 12, in <module>
    import brotli
  File "C:\Users\gh0sti\AppData\Local\Programs\Python\Python311\Lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: The specified module could not be found.

**Comment by charlesbel** [comment]
Maybe you're system is missing the visual c++ redistributable DLLs (though I think python itself should come with one).
Try to install the current "vc_redist.x64.exe" from this link
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

**Comment by gh0sti** [comment]
> https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

That fixed it. I was on win 11 22h2. Would updating requirements.txt to include this potentially fix this issue in the future?

**Comment by charlesbel** [comment]
Unfortunately not with pip, will add it in the README for those who don't already installed it.
