### ISSUE TITLE
[BUG] TypeError: 'NoneType' object not iterable

### ISSUE THREAD

**Issue by Yash1907** [charlesbel/Microsoft-Rewards-Farmer#257]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

After the undetected chrome update the program does not open chrome and just crashes.

### Copy and paste your error

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/50154127/cc787341-b5d8-4090-af52-6e89b2553e84)

### Screenshots

The chrome window does not open

### Value of dashboard variable

Program does not get that far

**Comment by charlesbel** [comment]
Did you used a proxy ?

**Comment by Yash1907** [comment]
No I did not

**Comment by eaaasun** [comment]
I've been getting this problem too, also with the same error messages as OP.

**Comment by damianTC** [comment]
I have the same problem after updating
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/38479551/aeaf57f9-11c7-4c09-b4d7-3bde32ff5745)

**Comment by charlesbel** [comment]
Would someone of you copy and paste here the error when you replace lines 20 to 24 in main.py from
```
        try:
            executeBot(currentAccount)
        except Exception as e:
            logging.error(f"{e.__class__.__name__}: {e}")
```
to just
```
        executeBot(currentAccount)
```

**Comment by Yash1907** [comment]
`2023-08-12 15:13:25,280 [INFO] Using default request storage
Traceback (most recent call last):
  File "C:\Users\Downloads\temp_farmer\Microsoft-Rewards-Farmer\main.py", line 144, in <module>
    main()
  File "C:\Users\Downloads\temp_farmer\Microsoft-Rewards-Farmer\main.py", line 20, in main
    executeBot(currentAccount)
  File "C:\Users\Downloads\temp_farmer\Microsoft-Rewards-Farmer\main.py", line 105, in executeBot
    with Browser(
         ^^^^^^^^
  File "C:\Users\Downloads\temp_farmer\Microsoft-Rewards-Farmer\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\temp_farmer\Microsoft-Rewards-Farmer\src\browser.py", line 80, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 32, in __init__
    config = self._setup_backend(seleniumwire_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\seleniumwire\webdriver.py", line 41, in _setup_backend
    self.backend = backend.create(
                   ^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\seleniumwire\backend.py", line 24, in create
    backend = MitmProxy(addr, port, options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\seleniumwire\server.py", line 56, in __init__
    **build_proxy_args(get_upstream_proxy(self.options)),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\seleniumwire\utils.py", line 57, in get_upstream_proxy
    merged.update(proxy_options)
TypeError: 'NoneType' object is not iterable
Exception ignored in: <function Chrome.__del__ at 0x00000264327ACD60>
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 800, in __del__
    self.quit()
  File "C:\Users\AppData\Roaming\Python\Python311\site-packages\seleniumwire\webdriver.py", line 67, in quit
    self.backend.shutdown()
    ^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 763, in __getattribute__
    return super().__getattribute__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Chrome' object has no attribute 'backend'`

this is what i got

**Comment by charlesbel** [comment]
Just fixed it ! (that was an error from myself, very easy to correct)
