### ISSUE TITLE
[ERROR] Binary Location Must be a String

### ISSUE THREAD

**Issue by femboyjophiel** [charlesbel/Microsoft-Rewards-Farmer#262]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

When trying to run it, I get this error.

### Copy and paste your error

New version available !
Removing old files...
Downloading...
Extracting...
Done !
Starting...
←[38;5;39m2023-08-12 22:09:22,778 [INFO] ********************myemail********************←[0m
←[38;5;39m2023-08-12 22:09:23,286 [INFO] Using default request storage←[0m
←[38;5;39m2023-08-12 22:09:23,293 [INFO] Created proxy listening on 127.0.0.1:3063←[0m
←[38;5;39m2023-08-12 22:09:23,293 [INFO] Using undetected_chromedriver←[0m
←[38;5;39m2023-08-12 22:09:24,203 [INFO] patching driver executable C:\Users\Nate\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe←[0m
←[38;5;196m2023-08-12 22:09:24,780 [ERROR] TypeError: Binary Location Must be a String←[0m
Traceback (most recent call last):
  File "C:\Users\Nate\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 21, in main
    executeBot(currentAccount)
  File "C:\Users\Nate\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 108, in executeBot
    with Browser(
  File "C:\Users\Nate\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "C:\Users\Nate\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\browser.py", line 76, in browserSetup
    driver = webdriver.Chrome(
  File "C:\Python310\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 372, in __init__
    options.binary_location = (
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\options.py", line 55, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/104801958/8f93b219-5ce2-461c-a292-c53a43f11fa5)

### Value of dashboard variable

https://gist.github.com/femboyjophiel/78d41ffd5471447bd32143c723198616#file-dashboard-txt

**Comment by udu3324** [comment]
you might want to remove your email to prevent scrapers

**Comment by femboyjophiel** [comment]
> 

yeah youre probably right

**Comment by charlesbel** [comment]
Please make sure every brower-related dependencies are up to date : ```pip install selenium selenium-wire undetected-chromedriver --upgrade```

**Comment by femboyjophiel** [comment]
> Please make sure every brower-related dependencies are up to date : `pip install selenium selenium-wire undetected-chromedriver --upgrade`

It turns out its a problem with selenium, the browser location is set to none by default so it causes an error. It still doesnt work but i guess this problem is resolved

**Comment by charlesbel** [comment]
Looks like Chrome is not installed or not installed in the default location, could you confirm ?
