### ISSUE TITLE
Bot crashing

### ISSUE THREAD

**Issue by charlesbel** [charlesbel/Microsoft-Rewards-Farmer#263]
The bot crashes if It doesn't run with -v, and it spits out the error below

[ERROR] TypeError: '<' not supported between instances of 'NoneType' and 'int'

_Originally posted by @udu3324 in https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/242#issuecomment-1676105141_

**Comment by charlesbel** [comment]
@udu3324 does it happens when completing bing searches ?

**Comment by udu3324** [comment]
> @udu3324 does it happens when completing bing searches ?

No no, it happens at the start when the bot tries to login

**Comment by charlesbel** [comment]
> > @udu3324 does it happens when completing bing searches ?
> 
> No no, it happens at the start when the bot tries to login

Could you retry with the latest version so we will see a full traceback (forgot it when first publishing the code)

**Comment by udu3324** [comment]
> > > @udu3324 does it happens when completing bing searches ?
> > 
> > 
> > No no, it happens at the start when the bot tries to login
> 
> Could you retry with the latest version so we will see a full traceback (forgot it when first publishing the code)

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/47045986/b0fa52c0-37e8-4096-99b1-033355b9874e)
```
TypeError: '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "C:\Users\compooter\Desktop\Microsoft-Rewards-Farmer\main.py", line 21, in main
    executeBot(currentAccount)
  File "C:\Users\compooter\Desktop\Microsoft-Rewards-Farmer\main.py", line 108, in executeBot
    with Browser(
  File "C:\Users\compooter\Desktop\Microsoft-Rewards-Farmer\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "C:\Users\compooter\Desktop\Microsoft-Rewards-Farmer\src\browser.py", line 76, in browserSetup
    driver = webdriver.Chrome(
  File "C:\Users\compooter\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\compooter\AppData\Local\Programs\Python\Python39\lib\site-packages\undetected_chromedriver\__init__.py", line 386, in __init__
    if self.patcher.version_main < 108:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by udu3324** [comment]
Turns out that I forgot to install undetected-chromedriver
