### ISSUE TITLE
[BUG] ImportError: cannot import name 'Headers' from 'h11._headers'

### ISSUE THREAD

**Issue by Uvxtq** [charlesbel/Microsoft-Rewards-Farmer#268]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

errors on run

### Copy and paste your error

Traceback (most recent call last):
  File "C:\Users\jacob\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "C:\Users\jacob\Downloads\Microsoft-Rewards-Farmer-master\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "C:\Users\jacob\Downloads\Microsoft-Rewards-Farmer-master\src\browser.py", line 9, in <module>
    import seleniumwire.undetected_chromedriver as webdriver
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 14, in <module>
    from seleniumwire.webdriver import DriverCommonMixin
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\server.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy import addons
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\addons\__init__.py", line 1, in <module>
    from seleniumwire.thirdparty.mitmproxy.addons import core
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\addons\core.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import command, ctx, exceptions, optmanager, platform
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\ctx.py", line 2, in <module>
    import seleniumwire.thirdparty.mitmproxy.master
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\master.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy import (
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\addonmanager.py", line 8, in <module>
    from seleniumwire.thirdparty.mitmproxy import controller, eventsequence, exceptions
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\eventsequence.py", line 3, in <module>
    from seleniumwire.thirdparty.mitmproxy import controller, http, tcp, websocket
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\websocket.py", line 5, in <module>
    from wsproto.frame_protocol import CloseReason, Opcode
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\wsproto\__init__.py", line 9, in <module>
    from .connection import Connection, ConnectionState, ConnectionType
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\wsproto\connection.py", line 23, in <module>
    from .utilities import LocalProtocolError
  File "C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\wsproto\utilities.py", line 12, in <module>
    from h11._headers import Headers as H11Headers
ImportError: cannot import name 'Headers' from 'h11._headers' (C:\Users\jacob\AppData\Local\Programs\Python\Python311\Lib\site-packages\h11\_headers.py)

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/96850544/6248d3b2-feb3-455a-bcfb-903e8c7e6e40)

### Value of dashboard variable

https://gist.github.com/Uvxtq/01ff3289d8f49b2aaf93d191d9f62118

**Comment by charlesbel** [comment]
Please run `pip install -r requirements.txt --upgrade` in the project folder to make sure every dependencie is up to date

**Comment by Uvxtq** [comment]
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/96850544/f510c882-e562-4500-a042-b88ef998fe2d)

**Comment by charlesbel** [comment]
> ![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/96850544/f510c882-e562-4500-a042-b88ef998fe2d)
> 

You seems to have issues with your installation of pip. Try again with command prompt ran as admin.

**Comment by Uvxtq** [comment]
Okay after running the command in and admin terminal it upgrades everything and when I run main.py it still crashes.

**Comment by charlesbel** [comment]
> Okay after running the command in and admin terminal it upgrades everything and when I run main.py it still crashes and gives the same error.

Try reinstalling h11 with
```pip uninstall h11
pip install h11
```
If you also get "Access denied" error, do it as admin.

**Comment by Uvxtq** [comment]
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/96850544/04de5a1e-da1f-43e7-ad6b-99539867397a)

**Comment by charlesbel** [comment]
> ![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/96850544/04de5a1e-da1f-43e7-ad6b-99539867397a)
> 

What does your accounts.json looks like ?

**Comment by charlesbel** [comment]
Considering resolved with correct file format for accounts.json
