### ISSUE TITLE
[BUG] Chrome unreachable

### ISSUE THREAD

**Issue by xBounceIT** [charlesbel/Microsoft-Rewards-Farmer#269]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

Installed on a Ubuntu Server 22.04.3 LTS

First run was successful, every other run now fails with the error "chrome unreachable".

I've read on multiple occasions that this issue is related to either selenium driver being bugged or chrome and driver not being aligned.

### Copy and paste your error

2023-08-14 09:21:58,682 [INFO] Using default request storage
2023-08-14 09:21:58,689 [INFO] Created proxy listening on 127.0.0.1:34897
2023-08-14 09:21:58,689 [INFO] Using undetected_chromedriver
2023-08-14 09:21:59,150 [INFO] patching driver executable /root/.local/share/undetected_chromedriver/undetected_chromedriver
2023-08-14 09:22:59,710 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:58305
from chrome not reachable
Stacktrace:
#0 0x55803014b4e3 <unknown>
#1 0x55802fe7ab00 <unknown>
#2 0x55802fe68436 <unknown>
#3 0x55802fea79be <unknown>
#4 0x55802fe9f884 <unknown>
#5 0x55802fedeccc <unknown>
#6 0x55802fede47f <unknown>
#7 0x55802fed5de3 <unknown>
#8 0x55802feab2dd <unknown>
#9 0x55802feac34e <unknown>
#10 0x55803010b3e4 <unknown>
#11 0x55803010f3d7 <unknown>
#12 0x558030119b20 <unknown>
#13 0x558030110023 <unknown>
#14 0x5580300de1aa <unknown>
#15 0x5580301346b8 <unknown>
#16 0x558030134847 <unknown>
#17 0x558030144243 <unknown>
#18 0x7f8d088ecb43 <unknown>
Traceback (most recent call last):
  File "/home/daniel/Microsoft-Rewards-Farmer-master/main.py", line 21, in main
    executeBot(currentAccount, argumentParser())
  File "/home/daniel/Microsoft-Rewards-Farmer-master/main.py", line 108, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "/home/daniel/Microsoft-Rewards-Farmer-master/src/browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "/home/daniel/Microsoft-Rewards-Farmer-master/src/browser.py", line 76, in browserSetup
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:58305
from chrome not reachable
Stacktrace:
#0 0x55803014b4e3 <unknown>
#1 0x55802fe7ab00 <unknown>
#2 0x55802fe68436 <unknown>
#3 0x55802fea79be <unknown>
#4 0x55802fe9f884 <unknown>
#5 0x55802fedeccc <unknown>
#6 0x55802fede47f <unknown>
#7 0x55802fed5de3 <unknown>
#8 0x55802feab2dd <unknown>
#9 0x55802feac34e <unknown>
#10 0x55803010b3e4 <unknown>
#11 0x55803010f3d7 <unknown>
#12 0x558030119b20 <unknown>
#13 0x558030110023 <unknown>
#14 0x5580300de1aa <unknown>
#15 0x5580301346b8 <unknown>
#16 0x558030134847 <unknown>
#17 0x558030144243 <unknown>
#18 0x7f8d088ecb43 <unknown>

### Screenshots

No GUI on Ubuntu Server so cant have this info.

### Value of dashboard variable

Tried looking but cant find, any procedure appreciated.

**Comment by charlesbel** [comment]
Please take a look at #266
