### ISSUE TITLE
NoSuchElementException error

### ISSUE THREAD

**Issue by raphalation** [charlesbel/Microsoft-Rewards-Farmer#27]
DevTools listening on ws://127.0.0.1:51248/devtools/browser/119322a7-0111-4a05-a64c-5a90a11c3894
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 19583 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completing quiz of card 2
Traceback (most recent call last):
  File "Z:\Users\rapha\Desktop\ms_rewards_farmer.py", line 604, in <module>
    completeDailySet(browser)
  File "Z:\Users\rapha\Desktop\ms_rewards_farmer.py", line 398, in completeDailySet
    completeDailySetQuiz(browser, cardNumber, 3)
  File "Z:\Users\rapha\Desktop\ms_rewards_farmer.py", line 276, in completeDailySetQuiz
    browser.find_element_by_xpath('//*[@id="rqStartQuiz"]').click()
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="rqStartQuiz"]"}
  (Session info: headless chrome=87.0.4280.88)

**Comment by charlesbel** [comment]
Could you give me a screenshot of the quiz page and also give me the source code of the Microsoft Rewards Dashboard Page with [gist](https://gist.github.com).

**Comment by raphalation** [comment]
sorry for not replying earlier.

I tried again today and got a different error. Failing on this or that
![Capture](https://user-images.githubusercontent.com/29611498/102689679-fc446380-41f7-11eb-9710-8550742896ef.PNG)


[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completing search of card 1
[DAILY SET] Completing quiz of card 2
[DAILY SET] Completing poll of card 3
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
Traceback (most recent call last):
  File "Z:\Users\rapha\Desktop\ms_rewards_farmer.py", line 610, in <module>
    completeMorePromotions(browser)
  File "Z:\Users\rapha\Desktop\ms_rewards_farmer.py", line 560, in completeMorePromotions
    completeMorePromotionThisOrThat(browser, i)
  File "Z:\Users\rapha\Desktop\ms_rewards_farmer.py", line 532, in completeMorePromotionThisOrThat
    answer1.click()
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=87.0.4280.88)



https://gist.github.com/raphalation/d0fae7738220bb8b78695edf44ab49c6

**Comment by charlesbel** [comment]
As I can see on your screenshot, all is not loaded on the page. You may have a slow internet connection I think. So when the bot try to complete, it run very fast, so if an element is not loaded, it crashes with an error. I would recommand you to try with a faster computer or internet. I will also make an update to handle this type of problem.

**Comment by charlesbel** [comment]
I made an update to handle the error
