### ISSUE TITLE
Error: Binary Location Must be a String

### ISSUE THREAD

**Issue by Lectoid** [charlesbel/Microsoft-Rewards-Farmer#271]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Just downloaded latest zip, extracted in to a new folder and moved my accounts.json to that folder. Ran the script and received the below errors. I did re-run the requirements and selenium upgrade.

### Copy and paste your error

2023-08-14 12:24:54,052 [ERROR] TypeError: Binary Location Must be a String
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 372, in __init__
    options.binary_location = (
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\options.py", line 55, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String

### Screenshots

n/a

### Value of dashboard variable

n/a

**Comment by charlesbel** [comment]
Is chrome installed on your computer ?

**Comment by Lectoid** [comment]
No. I've been using your awesome app for about a week and it wasn't installed then either.

**Comment by charlesbel** [comment]
So you need to install it
