### ISSUE TITLE
[BUG] dashboard is not defined

### ISSUE THREAD

**Issue by Legend-Recalls** [charlesbel/Microsoft-Rewards-Farmer#275]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

running the program as intended,
i got an error with dashboard not define, leaving error logs
[activity.log](https://github.com/charlesbel/Microsoft-Rewards-Farmer/files/12338430/activity.log)

### Copy and paste your error

2023-08-14 23:47:35,000 [INFO] ********************EmperorRuling@outlook.com********************
2023-08-14 23:47:36,195 [INFO] Using default request storage
2023-08-14 23:47:36,217 [INFO] Created proxy listening on 127.0.0.1:51706
2023-08-14 23:47:36,219 [INFO] Using undetected_chromedriver
2023-08-14 23:47:36,914 [INFO] patching driver executable C:\Users\Lells\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2023-08-14 23:47:37,871 [INFO] Screen size: 1855x1322
2023-08-14 23:47:37,871 [INFO] Device size: 1800x1171
2023-08-14 23:47:38,013 [INFO] [LOGIN] Logging-in...
2023-08-14 23:48:07,285 [INFO] [LOGIN] Logged-in !
2023-08-14 23:51:23,117 [ERROR] JavascriptException: Message: javascript error: dashboard is not defined
  (Session info: chrome=115.0.5790.171)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x004AA813+48355]
	(No symbol) [0x0043C4B1]
	(No symbol) [0x00345358]
	(No symbol) [0x003487A1]
	(No symbol) [0x0034A19B]
	(No symbol) [0x0039D279]
	(No symbol) [0x0038A73C]
	(No symbol) [0x0039C922]
	(No symbol) [0x0038A536]
	(No symbol) [0x003682DC]
	(No symbol) [0x003693DD]
	GetHandleVerifier [0x0070AABD+2539405]
	GetHandleVerifier [0x0074A78F+2800735]
	GetHandleVerifier [0x0074456C+2775612]
	GetHandleVerifier [0x005351E0+616112]
	(No symbol) [0x00445F8C]
	(No symbol) [0x00442328]
	(No symbol) [0x0044240B]
	(No symbol) [0x00434FF7]
	BaseThreadInitThunk [0x75FD7BA9+25]
	RtlInitializeExceptionChain [0x7727BB3B+107]
	RtlClearBits [0x7727BABF+191]
Traceback (most recent call last):
  File "C:\Users\Lells\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\Lells\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 128, in executeBot
    accountPointsCounter = Login(desktopBrowser).login()
  File "C:\Users\Lells\Desktop\Microsoft-Rewards-Farmer-master\src\login.py", line 43, in login
    points = self.utils.getAccountPoints()
  File "C:\Users\Lells\Desktop\Microsoft-Rewards-Farmer-master\src\utils.py", line 146, in getAccountPoints
    return self.getDashboardData()["userStatus"]["availablePoints"]
  File "C:\Users\Lells\Desktop\Microsoft-Rewards-Farmer-master\src\utils.py", line 116, in getDashboardData
    return self.webdriver.execute_script("return dashboard")
  File "C:\Users\Lells\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 405, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\Lells\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Lells\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: dashboard is not defined
  (Session info: chrome=115.0.5790.171)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x004AA813+48355]
	(No symbol) [0x0043C4B1]
	(No symbol) [0x00345358]
	(No symbol) [0x003487A1]
	(No symbol) [0x0034A19B]
	(No symbol) [0x0039D279]
	(No symbol) [0x0038A73C]
	(No symbol) [0x0039C922]
	(No symbol) [0x0038A536]
	(No symbol) [0x003682DC]
	(No symbol) [0x003693DD]
	GetHandleVerifier [0x0070AABD+2539405]
	GetHandleVerifier [0x0074A78F+2800735]
	GetHandleVerifier [0x0074456C+2775612]
	GetHandleVerifier [0x005351E0+616112]
	(No symbol) [0x00445F8C]
	(No symbol) [0x00442328]
	(No symbol) [0x0044240B]
	(No symbol) [0x00434FF7]
	BaseThreadInitThunk [0x75FD7BA9+25]
	RtlInitializeExceptionChain [0x7727BB3B+107]
	RtlClearBits [0x7727BABF+191]

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/69719681/80a835ba-bd63-492a-a02e-76ebca7eebf9)

### Value of dashboard variable

[https://gist.github.com/Legend-Recalls/11562298686c54d5bc082350eea3d401]

**Comment by charlesbel** [comment]
Can any of you run it with -v argument to see what's happening in the browser when the error occurs

**Comment by evox45** [comment]
With the -v argument I get this:

2023-08-14 20:16:38,618 [INFO] Using default request storage
2023-08-14 20:16:38,623 [INFO] Created proxy listening on 127.0.0.1:11342
2023-08-14 20:16:38,624 [INFO] Using undetected_chromedriver
2023-08-14 20:16:40,456 [INFO] patching driver executable C:\Users\Evan\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2023-08-14 20:17:41,692 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:11346
from chrome not reachable
Stacktrace:
Backtrace:
        GetHandleVerifier [0x008CA813+48355]
        (No symbol) [0x0085C4B1]
        (No symbol) [0x00765220]
        (No symbol) [0x0075B355]
        (No symbol) [0x00785C68]
        (No symbol) [0x007806B4]
        (No symbol) [0x00780491]
        (No symbol) [0x007B0C55]
        (No symbol) [0x007B093C]
        (No symbol) [0x007AA536]
        (No symbol) [0x007882DC]
        (No symbol) [0x007893DD]
        GetHandleVerifier [0x00B2AABD+2539405]
        GetHandleVerifier [0x00B6A78F+2800735]
        GetHandleVerifier [0x00B6456C+2775612]
        GetHandleVerifier [0x009551E0+616112]
        (No symbol) [0x00865F8C]
        (No symbol) [0x00862328]
        (No symbol) [0x0086240B]
        (No symbol) [0x00854FF7]
        BaseThreadInitThunk [0x75F97D59+25]
        RtlInitializeExceptionChain [0x7719B79B+107]
        RtlClearBits [0x7719B71F+191]

Traceback (most recent call last):
  File "C:\Users\Evan\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\Evan\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Evan\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Evan\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:11346
from chrome not reachable
Stacktrace:
Backtrace:
        GetHandleVerifier [0x008CA813+48355]
        (No symbol) [0x0085C4B1]
        (No symbol) [0x00765220]
        (No symbol) [0x0075B355]
        (No symbol) [0x00785C68]
        (No symbol) [0x007806B4]
        (No symbol) [0x00780491]
        (No symbol) [0x007B0C55]
        (No symbol) [0x007B093C]
        (No symbol) [0x007AA536]
        (No symbol) [0x007882DC]
        (No symbol) [0x007893DD]
        GetHandleVerifier [0x00B2AABD+2539405]
        GetHandleVerifier [0x00B6A78F+2800735]
        GetHandleVerifier [0x00B6456C+2775612]
        GetHandleVerifier [0x009551E0+616112]
        (No symbol) [0x00865F8C]
        (No symbol) [0x00862328]
        (No symbol) [0x0086240B]
        (No symbol) [0x00854FF7]
        BaseThreadInitThunk [0x75F97D59+25]
        RtlInitializeExceptionChain [0x7719B79B+107]
        RtlClearBits [0x7719B71F+191]

**Comment by evox45** [comment]
Something that I noticed is that if you restart your computer and run the script it actually works. If you stop the script or close the window it runs the above errors. Not sure to as why though.

**Comment by charlesbel** [comment]
I would need to see screenshots from a browser from someone who doesn't face this "cannot reach chrome" error

**Comment by charlesbel** [comment]
> With the -v argument I get this:
> 
> 2023-08-14 20:16:38,618 [INFO] Using default request storage
> 2023-08-14 20:16:38,623 [INFO] Created proxy listening on 127.0.0.1:11342
> 2023-08-14 20:16:38,624 [INFO] Using undetected_chromedriver
> 2023-08-14 20:16:40,456 [INFO] patching driver executable C:\Users\Evan\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
> 2023-08-14 20:17:41,692 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:11346
> from chrome not reachable
> Stacktrace:
> Backtrace:
>         GetHandleVerifier [0x008CA813+48355]
>         (No symbol) [0x0085C4B1]
>         (No symbol) [0x00765220]
>         (No symbol) [0x0075B355]
>         (No symbol) [0x00785C68]
>         (No symbol) [0x007806B4]
>         (No symbol) [0x00780491]
>         (No symbol) [0x007B0C55]
>         (No symbol) [0x007B093C]
>         (No symbol) [0x007AA536]
>         (No symbol) [0x007882DC]
>         (No symbol) [0x007893DD]
>         GetHandleVerifier [0x00B2AABD+2539405]
>         GetHandleVerifier [0x00B6A78F+2800735]
>         GetHandleVerifier [0x00B6456C+2775612]
>         GetHandleVerifier [0x009551E0+616112]
>         (No symbol) [0x00865F8C]
>         (No symbol) [0x00862328]
>         (No symbol) [0x0086240B]
>         (No symbol) [0x00854FF7]
>         BaseThreadInitThunk [0x75F97D59+25]
>         RtlInitializeExceptionChain [0x7719B79B+107]
>         RtlClearBits [0x7719B71F+191]
> 
> Traceback (most recent call last):
>   File "C:\Users\Evan\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
>     executeBot(currentAccount, notifier, args)
>   File "C:\Users\Evan\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 127, in executeBot
>     with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Evan\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\browser.py", line 41, in __init__
>     self.webdriver = self.browserSetup()
>                      ^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Evan\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\browser.py", line 77, in browserSetup
>     driver = webdriver.Chrome(
>              ^^^^^^^^^^^^^^^^^
>   File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
>     super().__init__(*args, **kwargs)
>   File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
>     super(Chrome, self).__init__(
>   File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
>     super().__init__(
>   File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
>     super().__init__(
>   File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
>     self.start_session(capabilities)
>   File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
>     super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
>   File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
>     response = self.execute(Command.NEW_SESSION, caps)["value"]
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\Evan\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:11346
> from chrome not reachable
> Stacktrace:
> Backtrace:
>         GetHandleVerifier [0x008CA813+48355]
>         (No symbol) [0x0085C4B1]
>         (No symbol) [0x00765220]
>         (No symbol) [0x0075B355]
>         (No symbol) [0x00785C68]
>         (No symbol) [0x007806B4]
>         (No symbol) [0x00780491]
>         (No symbol) [0x007B0C55]
>         (No symbol) [0x007B093C]
>         (No symbol) [0x007AA536]
>         (No symbol) [0x007882DC]
>         (No symbol) [0x007893DD]
>         GetHandleVerifier [0x00B2AABD+2539405]
>         GetHandleVerifier [0x00B6A78F+2800735]
>         GetHandleVerifier [0x00B6456C+2775612]
>         GetHandleVerifier [0x009551E0+616112]
>         (No symbol) [0x00865F8C]
>         (No symbol) [0x00862328]
>         (No symbol) [0x0086240B]
>         (No symbol) [0x00854FF7]
>         BaseThreadInitThunk [0x75F97D59+25]
>         RtlInitializeExceptionChain [0x7719B79B+107]
>         RtlClearBits [0x7719B71F+191]

Please close all other instances of chrome before running the script, should work

**Comment by Legend-Recalls** [comment]
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/69719681/4316306d-d4ba-4b00-b025-5b3be67b5992)
keeps reentering password
checked the json file it is in correct format

**Comment by charlesbel** [comment]
> ![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/69719681/4316306d-d4ba-4b00-b025-5b3be67b5992)
> keeps reentering password
> checked the json file it is in correct format

I see, it is not handled in the script so we need to fix this, will do it

**Comment by royaltongue** [comment]
Any update on this?

**Comment by agustinscaz** [comment]
update?
