### ISSUE TITLE
Linux issues with undetected chromedriver

### ISSUE THREAD

**Issue by J0hnnyRisk** [charlesbel/Microsoft-Rewards-Farmer#278]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

All of a sudden it won't start due to some unknown error when it tries to update undetected chromedriver.
Chrome does not have any issues what so ever.
I tried the no sandbox option as well.
Headless works for some reason.

### Copy and paste your error

johnny@johnny-VirtualBox:~/Schreibtisch/Microsoft-Rewards-Farmer-master$ python3 main.py
2023-08-15 14:40:14,313 [INFO] ********************Diptrip@outlook.de********************
2023-08-15 14:40:14,959 [INFO] Using default request storage
2023-08-15 14:40:14,964 [INFO] Created proxy listening on 127.0.0.1:46521
2023-08-15 14:40:14,964 [INFO] Using undetected_chromedriver
2023-08-15 14:40:15,834 [INFO] patching driver executable /home/johnny/.local/share/undetected_chromedriver/undetected_chromedriver
2023-08-15 14:41:16,396 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:41575
from chrome not reachable
Stacktrace:
#0 0x555c5ca2f4e3 <unknown>
#1 0x555c5c75eb00 <unknown>
#2 0x555c5c74c436 <unknown>
#3 0x555c5c78b9be <unknown>
#4 0x555c5c783884 <unknown>
#5 0x555c5c7c2ccc <unknown>
#6 0x555c5c7c247f <unknown>
#7 0x555c5c7b9de3 <unknown>
#8 0x555c5c78f2dd <unknown>
#9 0x555c5c79034e <unknown>
#10 0x555c5c9ef3e4 <unknown>
#11 0x555c5c9f33d7 <unknown>
#12 0x555c5c9fdb20 <unknown>
#13 0x555c5c9f4023 <unknown>
#14 0x555c5c9c21aa <unknown>
#15 0x555c5ca186b8 <unknown>
#16 0x555c5ca18847 <unknown>
#17 0x555c5ca28243 <unknown>
#18 0x7f210a894b43 <unknown>

Traceback (most recent call last):
  File "/home/johnny/Schreibtisch/Microsoft-Rewards-Farmer-master/main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "/home/johnny/Schreibtisch/Microsoft-Rewards-Farmer-master/main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "/home/johnny/Schreibtisch/Microsoft-Rewards-Farmer-master/src/browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "/home/johnny/Schreibtisch/Microsoft-Rewards-Farmer-master/src/browser.py", line 78, in browserSetup
    driver = webdriver.Chrome(
  File "/home/johnny/.local/lib/python3.10/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/johnny/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/johnny/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/johnny/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/johnny/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/johnny/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/johnny/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/johnny/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/johnny/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:41575
from chrome not reachable
Stacktrace:
#0 0x555c5ca2f4e3 <unknown>
#1 0x555c5c75eb00 <unknown>
#2 0x555c5c74c436 <unknown>
#3 0x555c5c78b9be <unknown>
#4 0x555c5c783884 <unknown>
#5 0x555c5c7c2ccc <unknown>
#6 0x555c5c7c247f <unknown>
#7 0x555c5c7b9de3 <unknown>
#8 0x555c5c78f2dd <unknown>
#9 0x555c5c79034e <unknown>
#10 0x555c5c9ef3e4 <unknown>
#11 0x555c5c9f33d7 <unknown>
#12 0x555c5c9fdb20 <unknown>
#13 0x555c5c9f4023 <unknown>
#14 0x555c5c9c21aa <unknown>
#15 0x555c5ca186b8 <unknown>
#16 0x555c5ca18847 <unknown>
#17 0x555c5ca28243 <unknown>
#18 0x7f210a894b43 <unknown>

### Screenshots

![Screenshot 2023-08-15 144800](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/48529609/f3c6ad28-4798-4152-8fcb-aecc6569234d)

### Value of dashboard variable

![Screenshot 2023-08-15 145019](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/48529609/d7571111-e67a-41d4-926f-2156cfdb5554)

**Comment by charlesbel** [comment]
Does deleting /Default/Preferences file in each sessions folder fix the issue ?

**Comment by SvenQ32** [comment]
I'm also getting the error on ubuntu but i tried  deleting /Default/Preferences file in each sessions folder and it didn't work either.

**Comment by xBounceIT** [comment]
This should be related to #266 

deleting every file and folder into sessions/ should solve the issue

`rm -f sessions/*`

**Comment by EastArctica** [comment]
This will be fixed with undetected-[chromedriver#1505](https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1505). Better workaround than deleting the entire sessions folder is to delete `sessions/*/desktop/SingletonLock`
