### ISSUE TITLE
[BUG] Stuck on login

### ISSUE THREAD

**Issue by Therkelsen** [charlesbel/Microsoft-Rewards-Farmer#281]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

I've followed the installation instructions, step 1 through 6, and both `py main.py` and `py autoupdate_main` hangs on login.

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/37107686/2f6d5e29-5835-4b4d-a2de-e0d4d26c2bac)

I have an accounts.json file with the following structure
`[
    {
        "username": "email@email.com",
        "password": "my_password"
    }
]`

I'll post the output when doing Ctrl + C when it hangs.

Any idea how to solve?

### Copy and paste your error

Traceback (most recent call last):
  File "C:\Users\surfs\Downloads\Microsoft-Rewards-Farmer-master\src\login.py", line 23, in login
    self.utils.waitUntilVisible(
  File "C:\Users\surfs\Downloads\Microsoft-Rewards-Farmer-master\src\utils.py", line 25, in waitUntilVisible
    WebDriverWait(self.webdriver, timeToWait).until(
  File "C:\Users\surfs\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0057A813+48355]
        (No symbol) [0x0050C4B1]
        (No symbol) [0x00415358]
        (No symbol) [0x004409A5]
        (No symbol) [0x00440B3B]
        (No symbol) [0x0046E232]
        (No symbol) [0x0045A784]
        (No symbol) [0x0046C922]
        (No symbol) [0x0045A536]
        (No symbol) [0x004382DC]
        (No symbol) [0x004393DD]
        GetHandleVerifier [0x007DAABD+2539405]
        GetHandleVerifier [0x0081A78F+2800735]
        GetHandleVerifier [0x0081456C+2775612]
        GetHandleVerifier [0x006051E0+616112]
        (No symbol) [0x00515F8C]
        (No symbol) [0x00512328]
        (No symbol) [0x0051240B]
        (No symbol) [0x00504FF7]
        BaseThreadInitThunk [0x753600C9+25]
        RtlGetAppContainerNamedObjectPath [0x76FA7B1E+286]
        RtlGetAppContainerNamedObjectPath [0x76FA7AEE+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\surfs\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 175, in <module>
    main()
  File "C:\Users\surfs\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\surfs\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 128, in executeBot
    accountPointsCounter = Login(desktopBrowser).login()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\surfs\Downloads\Microsoft-Rewards-Farmer-master\src\login.py", line 30, in login
    self.utils.waitUntilVisible(By.ID, "loginHeader", 0.1)
  File "C:\Users\surfs\Downloads\Microsoft-Rewards-Farmer-master\src\utils.py", line 25, in waitUntilVisible
    WebDriverWait(self.webdriver, timeToWait).until(
  File "C:\Users\surfs\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 92, in until
    time.sleep(self._poll)
KeyboardInterrupt

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/37107686/1a18cd46-f628-4c08-80a9-fcb21402f3d2)

### Value of dashboard variable

https://gist.github.com/Therkelsen/c956cb4ee5df1bad77963c4ee782ea8c

**Comment by charlesbel** [comment]
Are all your python packages up to date ? could your run `pip install -r requirements.txt --upgrade` to make sure ?

**Comment by Therkelsen** [comment]
> Are all your python packages up to date ? could your run `pip install -r requirements.txt --upgrade` to make sure ?

I have it a try, to no avail:
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/37107686/ea62d599-3def-4d47-9342-23254cd5cda1)


I also tried running cmd as admin, didnt help.

**Comment by Therkelsen** [comment]
I just tried it on a different machine, same account.

This time it got to writing email and password, then froze and blue screened.
