### ISSUE TITLE
[BUG] TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by omarwastaken** [charlesbel/Microsoft-Rewards-Farmer#285]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

UD Chromedriver error?

### Copy and paste your error

2023-08-17 14:23:49,265 [INFO] ********************#####********************
2023-08-17 14:23:49,886 [INFO] Using default request storage
2023-08-17 14:23:49,892 [INFO] Created proxy listening on 127.0.0.1:59721
2023-08-17 14:23:49,892 [INFO] Using undetected_chromedriver
2023-08-17 14:23:49,899 [ERROR] TypeError: '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "D:\Microsoft-Rewards-Farmer\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "D:\Microsoft-Rewards-Farmer\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "D:\Microsoft-Rewards-Farmer\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "D:\Microsoft-Rewards-Farmer\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 386, in __init__
    if self.patcher.version_main < 108:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### Screenshots

Browser doesn't launch

### Value of dashboard variable

Browser doesn't launch

**Comment by charlesbel** [comment]
Are all your python packages up to date ? could your run `pip install -r requirements.txt --upgrade` to make sure ?

**Comment by omarwastaken** [comment]
That fixed it! Thank you 💖
