### ISSUE TITLE
[BUG] It's not doing anything

### ISSUE THREAD

**Issue by SecretLUL** [charlesbel/Microsoft-Rewards-Farmer#291]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

I did every step in the README and startet the main.py. After I started it multiple times it just keeps spitting out the same line of codes which I do not understand.

### Copy and paste your error

C:\Users\Ammar-980\Downloads\Microsoft-Rewards-Farmer-master>python main.py -v
Traceback (most recent call last):
  File "C:\Users\Ammar-980\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 175, in <module>
    main()
  File "C:\Users\Ammar-980\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 21, in main
    loadedAccounts = setupAccounts()
  File "C:\Users\Ammar-980\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 118, in setupAccounts
    loadedAccounts = json.loads(accountPath.read_text(encoding="utf-8"))
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 3 (char 82)

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/18047775/a3e2f120-8b21-457e-b167-5ea6958453ab)

### Value of dashboard variable

https://gist.github.com/SecretLUL/758c31b3d80871b4ad3c7444e3e68ec5

**Comment by charlesbel** [comment]
Take a look at #290
