### ISSUE TITLE
[BUG] WebDriverException: Session deleted because of page crash

### ISSUE THREAD

**Issue by mellodoot** [charlesbel/Microsoft-Rewards-Farmer#292]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

i've just done a clean git clone of MRF, paired with a fresh install of debian (headless) with chrome 114 installed. not sure what causes this error, but happy to provide any other details that might be needed!

### Copy and paste your error

```
2023-08-17 21:58:04,620 [INFO] Using default request storage
2023-08-17 21:58:04,626 [INFO] Created proxy listening on 127.0.0.1:40131
2023-08-17 21:58:04,626 [INFO] Using undetected_chromedriver
2023-08-17 21:58:06,008 [INFO] patching driver executable /root/.local/share/undetected_chromedriver/undetected_chromedriver
2023-08-17 21:58:06,954 [INFO] Capturing request: https://clientservices.googleapis.com/chrome-variations/seed?osname=linux&channel=stable&milestone=114
2023-08-17 21:58:06,957 [INFO] Capturing request: https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard
2023-08-17 21:58:06,996 [INFO] Capturing request: https://redirector.gvt1.com/edgedl/chrome/dict/en-us-10-1.bdic
2023-08-17 21:58:07,014 [INFO] Screen size: 1645x1414
2023-08-17 21:58:07,014 [INFO] Device size: 1590x1263
2023-08-17 21:58:07,297 [INFO] [LOGIN] Logging-in...
2023-08-17 21:58:10,647 [INFO] [LOGIN] Writing email...
2023-08-17 21:58:12,063 [INFO] [LOGIN] Writing password...
2023-08-17 21:58:37,460 [INFO] [LOGIN] Logged-in !
2023-08-17 21:58:45,435 [ERROR] WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=114.0.5735.133)
Stacktrace:
#0 0x5647340a74e3 <unknown>
#1 0x564733dd6b00 <unknown>
#2 0x564733dc1b69 <unknown>
#3 0x564733dc1066 <unknown>
#4 0x564733dc0168 <unknown>
#5 0x564733dbffa0 <unknown>
#6 0x564733dbe9bf <unknown>
#7 0x564733dbf162 <unknown>
#8 0x564733dcd0d5 <unknown>
#9 0x564733dce222 <unknown>
#10 0x564733de0bcb <unknown>
#11 0x564733de53ab <unknown>
#12 0x564733dbf703 <unknown>
#13 0x564733de0810 <unknown>
#14 0x564733e4a523 <unknown>
#15 0x564733e31de3 <unknown>
#16 0x564733e072dd <unknown>
#17 0x564733e0834e <unknown>
#18 0x5647340673e4 <unknown>
#19 0x56473406b3d7 <unknown>
#20 0x564734075b20 <unknown>
#21 0x56473406c023 <unknown>
#22 0x56473403a1aa <unknown>
#23 0x5647340906b8 <unknown>
#24 0x564734090847 <unknown>
#25 0x5647340a0243 <unknown>
#26 0x7fa381db9ea7 start_thread
Traceback (most recent call last):
  File "/root/Microsoft-Rewards-Farmer/main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "/root/Microsoft-Rewards-Farmer/main.py", line 128, in executeBot
    accountPointsCounter = Login(desktopBrowser).login()
  File "/root/Microsoft-Rewards-Farmer/src/login.py", line 42, in login
    self.utils.goHome()
  File "/root/Microsoft-Rewards-Farmer/src/utils.py", line 86, in goHome
    self.webdriver.get(BASE_URL)
  File "/usr/local/lib/python3.9/dist-packages/undetected_chromedriver/__init__.py", line 629, in get_wrapped
    return orig_get(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=114.0.5735.133)
Stacktrace:
#0 0x5647340a74e3 <unknown>
#1 0x564733dd6b00 <unknown>
#2 0x564733dc1b69 <unknown>
#3 0x564733dc1066 <unknown>
#4 0x564733dc0168 <unknown>
#5 0x564733dbffa0 <unknown>
#6 0x564733dbe9bf <unknown>
#7 0x564733dbf162 <unknown>
#8 0x564733dcd0d5 <unknown>
#9 0x564733dce222 <unknown>
#10 0x564733de0bcb <unknown>
#11 0x564733de53ab <unknown>
#12 0x564733dbf703 <unknown>
#13 0x564733de0810 <unknown>
#14 0x564733e4a523 <unknown>
#15 0x564733e31de3 <unknown>
#16 0x564733e072dd <unknown>
#17 0x564733e0834e <unknown>
#18 0x5647340673e4 <unknown>
#19 0x56473406b3d7 <unknown>
#20 0x564734075b20 <unknown>
#21 0x56473406c023 <unknown>
#22 0x56473403a1aa <unknown>
#23 0x5647340906b8 <unknown>
#24 0x564734090847 <unknown>
#25 0x5647340a0243 <unknown>
#26 0x7fa381db9ea7 start_thread
```

### Screenshots

i'm running the app in a headless LXC, so can't run this in visible mode. apologies if that's not how this works ;p

### Value of dashboard variable

https://gist.github.com/mellodoot/edfc3c635b80403488876c53291ad3cb

**Comment by charlesbel** [comment]
It's because you're /dev/shm partition is too tiny for chrome, I can fix that by disable dev shm usage by default.

**Comment by mellodoot** [comment]
> It's because you're /dev/shm partition is too tiny for chrome, I can fix that by disable dev shm usage by default.

ah cool! should i wait on a commit for this or is there a quick patch i could try on my end?

**Comment by MaRcoB85** [comment]
hi! I have the same. Which way to resolve this?
