### ISSUE TITLE
[ERROR] TypeError: 'in <string>' requires string as left operand, not list

### ISSUE THREAD

**Issue by deadman36g** [charlesbel/Microsoft-Rewards-Farmer#294]
I get the following error when trying to use the script. I just upgraded my computer and it worked fine on MacBookPro but my new computer is an iMac and this is the error I recieve

```
deadman36g@iMac Microsoft-Rewards-Farmer % python3 main.py   
/Users/deadman36g/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
2023-08-18 09:02:39,199 [INFO] ********************?@outlook.com********************
2023-08-18 09:02:39,770 [INFO] Using default request storage
2023-08-18 09:02:39,782 [INFO] Created proxy listening on ::ffff:127.0.0.1:57814
2023-08-18 09:02:39,782 [INFO] Using undetected_chromedriver
2023-08-18 09:02:39,783 [ERROR] TypeError: 'in <string>' requires string as left operand, not list
Traceback (most recent call last):
  File "/Users/deadman36g/Library/Mobile Documents/com~apple~CloudDocs/Microsoft-Rewards-Farmer/main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "/Users/deadman36g/Library/Mobile Documents/com~apple~CloudDocs/Microsoft-Rewards-Farmer/main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "/Users/deadman36g/Library/Mobile Documents/com~apple~CloudDocs/Microsoft-Rewards-Farmer/src/browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "/Users/deadman36g/Library/Mobile Documents/com~apple~CloudDocs/Microsoft-Rewards-Farmer/src/browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
  File "/Users/deadman36g/Library/Python/3.9/lib/python/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/deadman36g/Library/Mobile Documents/com~apple~CloudDocs/Microsoft-Rewards-Farmer/src/undetected-chromedriver/undetected_chromedriver/__init__.py", line 251, in __init__
    self.patcher = Patcher(
  File "/Users/deadman36g/Library/Mobile Documents/com~apple~CloudDocs/Microsoft-Rewards-Farmer/src/undetected-chromedriver/undetected_chromedriver/patcher.py", line 66, in __init__
    self._set_platform_name()
  File "/Users/deadman36g/Library/Mobile Documents/com~apple~CloudDocs/Microsoft-Rewards-Farmer/src/undetected-chromedriver/undetected_chromedriver/patcher.py", line 115, in _set_platform_name
    self.platform_name = self._get_mac_platform_name()
  File "/Users/deadman36g/Library/Mobile Documents/com~apple~CloudDocs/Microsoft-Rewards-Farmer/src/undetected-chromedriver/undetected_chromedriver/patcher.py", line 123, in _get_mac_platform_name
    is_arm_arch = any(["aarch64", "arm"] in platform.machine())
TypeError: 'in <string>' requires string as left operand, not list
```

**Comment by kkrusher** [comment]
same issue

**Comment by kkrusher** [comment]
fixed it: https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/283#issuecomment-1685259697
