### ISSUE TITLE
TypeError: WebDriver.__init__() got an unexpected keyword argument 'seleniumwire_options'

### ISSUE THREAD

**Issue by ItzAlexx05** [charlesbel/Microsoft-Rewards-Farmer#295]
Traceback (most recent call last):
  File "C:\Users\Deval\Desktop\None\!!! MICRO\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\Deval\Desktop\None\!!! MICRO\Microsoft-Rewards-Farmer-master\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Deval\Desktop\None\!!! MICRO\Microsoft-Rewards-Farmer-master\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Deval\Desktop\None\!!! MICRO\Microsoft-Rewards-Farmer-master\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\Deval\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 53, in __new__
    instance.__init__(*args, **kwargs)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'seleniumwire_options'

**Comment by udu3324** [comment]
Can you update selenium wire? `pip install selenium selenium-wire undetected-chromedriver --upgrade`

**Comment by LevSky22** [comment]
> Can you update selenium wire? `pip install selenium selenium-wire undetected-chromedriver --upgrade`

That fixed it for me =)
