### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by darkspecs** [charlesbel/Microsoft-Rewards-Farmer#30]
**Error Log**
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 170 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 751, in <module>
    remainingSearches, remainingSearchesM = getRemainingSearches(browser)
  File "ms_rewards_farmer.py", line 690, in getRemainingSearches
    progressDesktop = counters['pcSearch'][0]['pointProgress'] + counters['pcSearch'][1]['pointProgress']
KeyError: 'pcSearch'

**Source code of dashboard**
https://gist.github.com/darkspecs/5b8c064bad6991f9830a14117365e587

**Comment by darkspecs** [comment]
Was accessing from non-usa ip address. My apologies. Using USA ip fixed issue
