### ISSUE TITLE
Chromedriver Issues

### ISSUE THREAD

**Issue by pearlheartgtr** [charlesbel/Microsoft-Rewards-Farmer#303]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Nothing is working. 

### Copy and paste your error

2023-08-21 17:46:57,900 [INFO] ********************xxx@hotmail.com********************
2023-08-21 17:46:58,798 [INFO] Using default request storage
2023-08-21 17:46:58,813 [INFO] Created proxy listening on 127.0.0.1:57261
2023-08-21 17:46:58,813 [INFO] Using undetected_chromedriver
2023-08-21 17:46:59,735 [INFO] patching driver executable C:\Users\xxx\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2023-08-21 17:48:01,470 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:57264
from chrome not reachable
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00F5A813+48355]
	(No symbol) [0x00EEC4B1]
	(No symbol) [0x00DF5220]
	(No symbol) [0x00DEB355]
	(No symbol) [0x00E15C68]
	(No symbol) [0x00E106B4]
	(No symbol) [0x00E10491]
	(No symbol) [0x00E40C55]
	(No symbol) [0x00E4093C]
	(No symbol) [0x00E3A536]
	(No symbol) [0x00E182DC]
	(No symbol) [0x00E193DD]
	GetHandleVerifier [0x011BAABD+2539405]
	GetHandleVerifier [0x011FA78F+2800735]
	GetHandleVerifier [0x011F456C+2775612]
	GetHandleVerifier [0x00FE51E0+616112]
	(No symbol) [0x00EF5F8C]
	(No symbol) [0x00EF2328]
	(No symbol) [0x00EF240B]
	(No symbol) [0x00EE4FF7]
	BaseThreadInitThunk [0x765D7D49+25]
	RtlInitializeExceptionChain [0x774CB74B+107]
	RtlClearBits [0x774CB6CF+191]
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\New Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\xxx\Desktop\New Microsoft-Rewards-Farmer-master\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "C:\Users\xxx\Desktop\New Microsoft-Rewards-Farmer-master\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "C:\Users\xxx\Desktop\New Microsoft-Rewards-Farmer-master\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:57264
from chrome not reachable
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00F5A813+48355]
	(No symbol) [0x00EEC4B1]
	(No symbol) [0x00DF5220]
	(No symbol) [0x00DEB355]
	(No symbol) [0x00E15C68]
	(No symbol) [0x00E106B4]
	(No symbol) [0x00E10491]
	(No symbol) [0x00E40C55]
	(No symbol) [0x00E4093C]
	(No symbol) [0x00E3A536]
	(No symbol) [0x00E182DC]
	(No symbol) [0x00E193DD]
	GetHandleVerifier [0x011BAABD+2539405]
	GetHandleVerifier [0x011FA78F+2800735]
	GetHandleVerifier [0x011F456C+2775612]
	GetHandleVerifier [0x00FE51E0+616112]
	(No symbol) [0x00EF5F8C]
	(No symbol) [0x00EF2328]
	(No symbol) [0x00EF240B]
	(No symbol) [0x00EE4FF7]
	BaseThreadInitThunk [0x765D7D49+25]
	RtlInitializeExceptionChain [0x774CB74B+107]
	RtlClearBits [0x774CB6CF+191]

### Screenshots

.

### Value of dashboard variable

[https://gist.github.com/pearlheartgtr/80aa4fce4853231ddc4100aec69bd57c](url)

**Comment by udu3324** [comment]
Possible duplicate of #283

**Comment by Ranini** [comment]
i have the same problem
