### ISSUE TITLE
[BUG] Title "Chrome driver not compatible with version 116"

### ISSUE THREAD

**Issue by Ranini** [charlesbel/Microsoft-Rewards-Farmer#316]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

I have an error saying the chrome driver is not compatible with chrome version 116(it is compatible with the 114) after patching the webdriver

(i'm french) 

### Copy and paste your error

2023-08-25 17:48:23,734 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60801
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00FCA813+48355]
        (No symbol) [0x00F5C4B1]
        (No symbol) [0x00E65358]
        (No symbol) [0x00E861AC]
        (No symbol) [0x00E806B4]
        (No symbol) [0x00E80491]
        (No symbol) [0x00EB0C55]
        (No symbol) [0x00EB093C]
        (No symbol) [0x00EAA536]
        (No symbol) [0x00E882DC]
        (No symbol) [0x00E893DD]
        GetHandleVerifier [0x0122AABD+2539405]
        GetHandleVerifier [0x0126A78F+2800735]
        GetHandleVerifier [0x0126456C+2775612]
        GetHandleVerifier [0x010551E0+616112]
        (No symbol) [0x00F65F8C]
        (No symbol) [0x00F62328]
        (No symbol) [0x00F6240B]
        (No symbol) [0x00F54FF7]
        BaseThreadInitThunk [0x76507D59+25]
        RtlInitializeExceptionChain [0x779BB79B+107]
        RtlClearBits [0x779BB71F+191]

Traceback (most recent call last):
  File "C:\Users\bjouz\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\bjouz\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bjouz\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bjouz\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\bjouz\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\bjouz\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\bjouz\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\bjouz\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    super().__init__(
  File "C:\Users\bjouz\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\bjouz\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 589, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\bjouz\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bjouz\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bjouz\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:60801
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00FCA813+48355]
        (No symbol) [0x00F5C4B1]
        (No symbol) [0x00E65358]
        (No symbol) [0x00E861AC]
        (No symbol) [0x00E806B4]
        (No symbol) [0x00E80491]
        (No symbol) [0x00EB0C55]
        (No symbol) [0x00EB093C]
        (No symbol) [0x00EAA536]
        (No symbol) [0x00E882DC]
        (No symbol) [0x00E893DD]
        GetHandleVerifier [0x0122AABD+2539405]
        GetHandleVerifier [0x0126A78F+2800735]
        GetHandleVerifier [0x0126456C+2775612]
        GetHandleVerifier [0x010551E0+616112]
        (No symbol) [0x00F65F8C]
        (No symbol) [0x00F62328]
        (No symbol) [0x00F6240B]
        (No symbol) [0x00F54FF7]
        BaseThreadInitThunk [0x76507D59+25]
        RtlInitializeExceptionChain [0x779BB79B+107]
        RtlClearBits [0x779BB71F+191]

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/72881692/1818e2e5-8716-4811-a552-1a00f3aa521d)
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/72881692/36cbe54b-fd85-421c-9958-4cf670cd32e7)
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/72881692/90b5a5cb-6a2e-4f94-ae39-7201829dba3b)
the browser opens and closes in not even a second

### Value of dashboard variable

nothing

**Comment by EastArctica** [comment]
Should be fixed when updating to https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1478 which was merged and released ~8 hours ago

**Comment by EastArctica** [comment]
@Ranini Any updates? Is this issue still present?

**Comment by Ranini** [comment]
i have the same error sorry

**Comment by EastArctica** [comment]
> i have the same error sorry

You ran `pip install -r requirements.txt` again? Can you run `pip show undetected-chromedriver` and show the output?

It should look something like this:
```
Name: undetected-chromedriver
Version: 3.5.3
Summary: ('Selenium.webdriver.Chrome replacement with compatiblity for Brave, and other Chromium based browsers.', 'Not triggered by CloudFlare/Imperva/hCaptcha and such.', 'NOTE: results may vary due to many factors. No guarantees are given, except for ongoing efforts in understanding detection algorithms.')
Home-page: https://github.com/ultrafunkamsterdam/undetected-chromedriver
Author: UltrafunkAmsterdam
Author-email: info@blackhat-security.nl
License: GPL-3.0
Location: /home/eastarctica/src/microsoft-rewards/Other/Microsoft-Rewards-Farmer-main/venv/lib/python3.11/site-packages
Requires: requests, selenium, websockets
Required-by:
```

**Comment by Wind-user** [comment]
PS C:\Users\Error\Documents\Body> & "C:/Program Files/Python311/python.exe" c:/Users/Error/Documents/Body/speak.py
c:\Users\Error\Documents\Body\speak.py:4: DeprecationWarning: 'msilib' is deprecated and slated for removal in Python 3.13
  from msilib.schema import ServiceControl

DevTools listening on ws://127.0.0.1:51079/devtools/browser/65d8968b-892f-46a4-833d-87791f6811b2
Traceback (most recent call last):
  File "c:\Users\Error\Documents\Body\speak.py", line 11, in <module>
    webdriver.Chrome()
  File "C:\Users\Error\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\chrome\webdriver.py", line 49, in __init__
    super().__init__(
  File "C:\Users\Error\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\chromium\webdriver.py", line 54, in __init__
    super().__init__(
  File "C:\Users\Error\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\Error\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Error\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Error\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.140 with binary path C:\Program Files\Google\Chrome\Application\chrome.exeStacktrace:
Backtrace:
        GetHandleVerifier [0x011AA813+48355]
        (No symbol) [0x0113C4B1]
        (No symbol) [0x01045358]
        (No symbol) [0x010661AC]
        (No symbol) [0x01061EF3]
        (No symbol) [0x01060579]
        (No symbol) [0x01090C55]
        (No symbol) [0x0109093C]
        (No symbol) [0x0108A536]
        (No symbol) [0x010682DC]
        (No symbol) [0x010693DD]
        GetHandleVerifier [0x0140AABD+2539405]
        GetHandleVerifier [0x0144A78F+2800735]
        GetHandleVerifier [0x0144456C+2775612]
        GetHandleVerifier [0x012351E0+616112]
        (No symbol) [0x01145F8C]
        (No symbol) [0x01142328]
        (No symbol) [0x0114240B]
        (No symbol) [0x01134FF7]
        BaseThreadInitThunk [0x75C400C9+25]
        RtlGetAppContainerNamedObjectPath [0x778F7B1E+286]
        RtlGetAppContainerNamedObjectPath [0x778F7AEE+238]


PLZ anyone Help For this problem

**Comment by Ranini** [comment]
Hello i reinstalled manually the undetected-chromdriver.
Look the output :
Summary: ('Selenium.webdriver.Chrome replacement with compatiblity for Brave, and other Chromium based browsers.', 'Not triggered by CloudFlare/Imperva/hCaptcha and such.', 'NOTE: results may vary due to many factors. No guarantees are given, except for ongoing efforts in understanding detection algorithms.')
Home-page: https://github.com/ultrafunkamsterdam/undetected-chromedriver
Author: UltrafunkAmsterdam
Author-email: info@blackhat-security.nl
License: GPL-3.0
Location: C:\Users\bjouz\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: requests, selenium, websockets
Required-by: hcaptcha-challenger
after this it work but i have a pip error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hcaptcha-challenger 0.4.3.3 requires selenium~=4.4.3, but you have selenium 4.12.0 which is incompatible.
hcaptcha-challenger 0.4.3.3 requires undetected-chromedriver==3.1.5.post4, but you have undetected-chromedriver 3.5.3 which is incompatible.

**Comment by klept0** [comment]
If your problem is resolved - please close this issue out.

**Comment by Ranini** [comment]
OK

**Comment by Ranini** [comment]
THANK
