### ISSUE TITLE
how do i use the Launch arguments

### ISSUE THREAD

**Issue by Fr0go1** [charlesbel/Microsoft-Rewards-Farmer#327]

**Comment by udu3324** [comment]
In terminal, type 
python main.py (flags here)

You can see the example flags in the readme of the repo

**Comment by Fr0go1** [comment]
how would i use discord, where do i put the webhook

**Comment by Fr0go1** [comment]
←[38;5;196m2023-08-31 16:32:01,640 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:65116
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x00F437C3+48947]
        (No symbol) [0x00ED8551]
        (No symbol) [0x00DDC7F0]
        (No symbol) [0x00DD1011]
        (No symbol) [0x00DFEDB7]
        (No symbol) [0x00DF95E1]
        (No symbol) [0x00DF9447]
        (No symbol) [0x00E2B840]
        (No symbol) [0x00E2B3CC]
        (No symbol) [0x00E24E86]
        (No symbol) [0x00E016C7]
        (No symbol) [0x00E0284D]
        GetHandleVerifier [0x0118FDF9+2458985]
        GetHandleVerifier [0x011D744F+2751423]
        GetHandleVerifier [0x011D1361+2726609]
        GetHandleVerifier [0x00FC0680+560624]
        (No symbol) [0x00EE238C]
        (No symbol) [0x00EDE268]
        (No symbol) [0x00EDE392]
        (No symbol) [0x00ED10B7]
        BaseThreadInitThunk [0x76037BA9+25]
        RtlInitializeExceptionChain [0x7733B79B+107]
        RtlClearBits [0x7733B71F+191]
←[0m
Traceback (most recent call last):
  File "D:\AI-image\shit\Microsoft-Rewards-Farmer\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "D:\AI-image\shit\Microsoft-Rewards-Farmer\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "D:\AI-image\shit\Microsoft-Rewards-Farmer\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "D:\AI-image\shit\Microsoft-Rewards-Farmer\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
  File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:65116
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x00F437C3+48947]
        (No symbol) [0x00ED8551]
        (No symbol) [0x00DDC7F0]
        (No symbol) [0x00DD1011]
        (No symbol) [0x00DFEDB7]
        (No symbol) [0x00DF95E1]
        (No symbol) [0x00DF9447]
        (No symbol) [0x00E2B840]
        (No symbol) [0x00E2B3CC]
        (No symbol) [0x00E24E86]
        (No symbol) [0x00E016C7]
        (No symbol) [0x00E0284D]
        GetHandleVerifier [0x0118FDF9+2458985]
        GetHandleVerifier [0x011D744F+2751423]
        GetHandleVerifier [0x011D1361+2726609]
        GetHandleVerifier [0x00FC0680+560624]
        (No symbol) [0x00EE238C]
        (No symbol) [0x00EDE268]
        (No symbol) [0x00EDE392]
        (No symbol) [0x00ED10B7]
        BaseThreadInitThunk [0x76037BA9+25]
        RtlInitializeExceptionChain [0x7733B79B+107]
        RtlClearBits [0x7733B71F+191]

**Comment by klept0** [comment]
> ←[38;5;196m2023-08-31 16:32:01,640 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:65116 from chrome not reachable Stacktrace: GetHandleVerifier [0x00F437C3+48947] (No symbol) [0x00ED8551] (No symbol) [0x00DDC7F0] (No symbol) [0x00DD1011] (No symbol) [0x00DFEDB7] (No symbol) [0x00DF95E1] (No symbol) [0x00DF9447] (No symbol) [0x00E2B840] (No symbol) [0x00E2B3CC] (No symbol) [0x00E24E86] (No symbol) [0x00E016C7] (No symbol) [0x00E0284D] GetHandleVerifier [0x0118FDF9+2458985] GetHandleVerifier [0x011D744F+2751423] GetHandleVerifier [0x011D1361+2726609] GetHandleVerifier [0x00FC0680+560624] (No symbol) [0x00EE238C] (No symbol) [0x00EDE268] (No symbol) [0x00EDE392] (No symbol) [0x00ED10B7] BaseThreadInitThunk [0x76037BA9+25] RtlInitializeExceptionChain [0x7733B79B+107] RtlClearBits [0x7733B71F+191] ←[0m Traceback (most recent call last): File "D:\AI-image\shit\Microsoft-Rewards-Farmer\main.py", line 24, in main executeBot(currentAccount, notifier, args) File "D:\AI-image\shit\Microsoft-Rewards-Farmer\main.py", line 127, in executeBot with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser: File "D:\AI-image\shit\Microsoft-Rewards-Farmer\src\browser.py", line 41, in **init** self.webdriver = self.browserSetup() File "D:\AI-image\shit\Microsoft-Rewards-Farmer\src\browser.py", line 77, in browserSetup driver = webdriver.Chrome( File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in **init** super().**init**(*args, **kwargs) File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver__init__.py", line 466, in **init** super(Chrome, self).**init**( File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in **init** super().**init**( File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in **init** super().**init**( File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in **init** self.start_session(capabilities) File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver__init__.py", line 724, in start_session super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session( File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session response = self.execute(Command.NEW_SESSION, caps)["value"] File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute self.error_handler.check_response(response) File "C:\Users\numbe\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:65116 from chrome not reachable Stacktrace: GetHandleVerifier [0x00F437C3+48947] (No symbol) [0x00ED8551] (No symbol) [0x00DDC7F0] (No symbol) [0x00DD1011] (No symbol) [0x00DFEDB7] (No symbol) [0x00DF95E1] (No symbol) [0x00DF9447] (No symbol) [0x00E2B840] (No symbol) [0x00E2B3CC] (No symbol) [0x00E24E86] (No symbol) [0x00E016C7] (No symbol) [0x00E0284D] GetHandleVerifier [0x0118FDF9+2458985] GetHandleVerifier [0x011D744F+2751423] GetHandleVerifier [0x011D1361+2726609] GetHandleVerifier [0x00FC0680+560624] (No symbol) [0x00EE238C] (No symbol) [0x00EDE268] (No symbol) [0x00EDE392] (No symbol) [0x00ED10B7] BaseThreadInitThunk [0x76037BA9+25] RtlInitializeExceptionChain [0x7733B79B+107] RtlClearBits [0x7733B71F+191]

taskkill /pid chrome.exe /t /f

**Comment by Fr0go1** [comment]
> taskkill /pid chrome.exe /t /f

so i put that in cmd, will it close chrome?

**Comment by udu3324** [comment]
> > taskkill /pid chrome.exe /t /f
> 
> so i put that in cmd, will it close chrome?

You should really learn more about how command line works before using the farmer

**Comment by klept0** [comment]
If your problem is resolved - please close this issue out.
