### ISSUE TITLE
Error on debian 11 main.py line 24

### ISSUE THREAD

**Issue by Ices-Eyes** [charlesbel/Microsoft-Rewards-Farmer#336]
Hi,
i'm trying to use this script on a debian 11 distro, but I'm receving an error whnever I lunch it, both main and autoupdate, any help? Here the stacktrace:

```
python3 main.py -t xxxxx
2023-09-05 10:46:03,490 [INFO] ********************xxxxxxx@outlook.it********************
2023-09-05 10:46:04,267 [INFO] Using default request storage
2023-09-05 10:46:04,277 [INFO] Created proxy listening on 127.0.0.1:43485
2023-09-05 10:46:04,277 [INFO] Using undetected_chromedriver
2023-09-05 10:46:06,611 [INFO] patching driver executable /root/.local/share/undetected_chromedriver/undetected_chromedriver
2023-09-05 10:47:07,185 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:40345
from chrome not reachable
Stacktrace:
#0 0x55cef63a6e23 <unknown>
#1 0x55cef60cf5f6 <unknown>
#2 0x55cef60ba63a <unknown>
#3 0x55cef60fe9ab <unknown>
#4 0x55cef60f6b39 <unknown>
#5 0x55cef6137d92 <unknown>
#6 0x55cef61373af <unknown>
#7 0x55cef612ede3 <unknown>
#8 0x55cef6102a7b <unknown>
#9 0x55cef610381e <unknown>
#10 0x55cef6368638 <unknown>
#11 0x55cef636c507 <unknown>
#12 0x55cef6376c4c <unknown>
#13 0x55cef636d136 <unknown>
#14 0x55cef633b9cf <unknown>
#15 0x55cef6390b98 <unknown>
#16 0x55cef6390d68 <unknown>
#17 0x55cef639fcb3 <unknown>
#18 0x7f30863b0044 <unknown>

Traceback (most recent call last):
  File "/home/deb/Microsoft-Rewards-Farmer-master/main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "/home/deb/Microsoft-Rewards-Farmer-master/main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deb/Microsoft-Rewards-Farmer-master/src/browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/deb/Microsoft-Rewards-Farmer-master/src/browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.11/dist-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:40345
from chrome not reachable
Stacktrace:
#0 0x55cef63a6e23 <unknown>
#1 0x55cef60cf5f6 <unknown>
#2 0x55cef60ba63a <unknown>
#3 0x55cef60fe9ab <unknown>
#4 0x55cef60f6b39 <unknown>
#5 0x55cef6137d92 <unknown>
#6 0x55cef61373af <unknown>
#7 0x55cef612ede3 <unknown>
#8 0x55cef6102a7b <unknown>
#9 0x55cef610381e <unknown>
#10 0x55cef6368638 <unknown>
#11 0x55cef636c507 <unknown>
#12 0x55cef6376c4c <unknown>
#13 0x55cef636d136 <unknown>
#14 0x55cef633b9cf <unknown>
#15 0x55cef6390b98 <unknown>
#16 0x55cef6390d68 <unknown>
#17 0x55cef639fcb3 <unknown>
#18 0x7f30863b0044 <unknown>
```

**Comment by klept0** [comment]
Verify all Chrome processes are closed and all requirements are updated

**Comment by Ices-Eyes** [comment]
Hi. No chrome running, and requirements seems to be ok.

```
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: selenium in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 2)) (4.12.0)
Requirement already satisfied: ipapi in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 3)) (1.0.4)
Requirement already satisfied: undetected-chromedriver in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 4)) (3.5.3)
Requirement already satisfied: selenium-wire in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 5)) (5.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 1)) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 1)) (2022.9.24)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.11/dist-packages (from selenium->-r requirements.txt (line 2)) (0.22.2)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.11/dist-packages (from selenium->-r requirements.txt (line 2)) (0.10.3)
Requirement already satisfied: websockets in /usr/local/lib/python3.11/dist-packages (from undetected-chromedriver->-r requirements.txt (line 4)) (11.0.3)
Requirement already satisfied: blinker>=1.4 in /usr/lib/python3/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (1.5)
Requirement already satisfied: brotli>=1.0.9 in /usr/local/lib/python3.11/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (1.0.9)
Requirement already satisfied: kaitaistruct>=0.7 in /usr/local/lib/python3.11/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (0.10)
Requirement already satisfied: pyasn1>=0.3.1 in /usr/local/lib/python3.11/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (0.5.0)
Requirement already satisfied: pyOpenSSL>=22.0.0 in /usr/local/lib/python3.11/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (23.2.0)
Requirement already satisfied: pyparsing>=2.4.2 in /usr/lib/python3/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (3.0.9)
Requirement already satisfied: pysocks>=1.7.1 in /usr/local/lib/python3.11/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (1.7.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.11/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (1.2.0)
Requirement already satisfied: zstandard>=0.14.1 in /usr/local/lib/python3.11/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (0.21.0)
Requirement already satisfied: h2>=4.0 in /usr/local/lib/python3.11/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (4.1.0)
Requirement already satisfied: hyperframe>=6.0 in /usr/local/lib/python3.11/dist-packages (from selenium-wire->-r requirements.txt (line 5)) (6.0.1)
Requirement already satisfied: hpack<5,>=4.0 in /usr/local/lib/python3.11/dist-packages (from h2>=4.0->selenium-wire->-r requirements.txt (line 5)) (4.0.0)
Requirement already satisfied: cryptography!=40.0.0,!=40.0.1,<42,>=38.0.0 in /usr/lib/python3/dist-packages (from pyOpenSSL>=22.0.0->selenium-wire->-r requirements.txt (line 5)) (38.0.4)
Requirement already satisfied: attrs>=20.1.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from trio~=0.17->selenium->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.11/dist-packages (from trio-websocket~=0.9->selenium->-r requirements.txt (line 2)) (1.1.2)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from wsproto>=0.14->selenium-wire->-r requirements.txt (line 5)) (0.14.0)
```

**Comment by EastArctica** [comment]
Verify you have chromium/chrome/we driver installed. Other than that, check the undetected-chromedriver repo for similar issues.

**Comment by tuxfollower** [comment]
Got the same issue on archlinux. Activating the window with -v seems to solve it.

**Comment by Ices-Eyes** [comment]
Ok, it seems the problem was some permissions on 'Local State' file in session folder... Solved those, all worked.
Btw, I try with another question... Is there a way to start the farm unattended? The script asks for xserver at launch, both with or without -v option, making it impossible to schedule it on a shell on a server... :)

**Comment by Ices-Eyes** [comment]
Well... Update... It seems the problem is related to the session folder... The first time the script il launched, without the session folder, it correctly run. The second time, with the session saved, it produce di above error :(

**Comment by EastArctica** [comment]
> Well... Update... It seems the problem is related to the session folder... The first time the script il launched, without the session folder, it correctly run. The second time, with the session saved, it produce di above error :(

can you try this? https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/278#issuecomment-1693774447

**Comment by Ices-Eyes** [comment]
That solve the problem!!! Thanks

**Comment by klept0** [comment]
If your problem is resolved - please close this issue out.
