### ISSUE TITLE
Can not run program

### ISSUE THREAD

**Issue by 123321abccba1** [charlesbel/Microsoft-Rewards-Farmer#337]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

I get error message when i run program

### Copy and paste your error

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "/home/rock/Microsoft-Rewards-Farmer-master/src/__init__.py", line 1, in <module>
    from .browser import Browser
  File "/home/rock/Microsoft-Rewards-Farmer-master/src/browser.py", line 12, in <module>
    from src.userAgentGenerator import GenerateUserAgent
  File "/home/rock/Microsoft-Rewards-Farmer-master/src/userAgentGenerator.py", line 8, in <module>
    class GenerateUserAgent:
  File "/home/rock/Microsoft-Rewards-Farmer-master/src/userAgentGenerator.py", line 34, in GenerateUserAgent
    browserConfig: dict[str, Any],
TypeError: 'type' object is not subscriptable
rock@rock-3a:~/Microsoft-Rewards-Farmer-master$ ^C
rock@rock-3a:~/Microsoft-Rewards-Farmer-master$ python main.py -v
  File "main.py", line 26
    logging.exception(f"{e.__class__.__name__}: {e}")
                                                   ^
SyntaxError: invalid syntax

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/47651072/a2fb096f-8424-4748-949b-686f5effbeee)

### Value of dashboard variable

[<script src="https://gist.github.com/123321abccba1/f7c55352c3a1f5abbf8ff1d0b12f1ac1.js"></script>](https://gist.github.com/123321abccba1/f7c55352c3a1f5abbf8ff1d0b12f1ac1)

**Comment by klept0** [comment]
Did you install the required files? 
What version of Python are you running? 
What OS are you running on?

**Comment by 123321abccba1** [comment]
required files I installed,python version 3.8 and i running in Ubuntu 20.04.6 LTS

**Comment by EastArctica** [comment]
> required files I installed,python version 3.8 and i running in Ubuntu 20.04.6 LTS

Can you rerun this in a venv? They tend to produce more stable results.

**Comment by JG0078** [comment]
updating to Ubuntu 22 LTS does resolve this issue.  There is some conflict on Ubuntu 20 and python.  I'm not sure how to debug that though

**Comment by alessiouw** [comment]
Run it as a non-root user

**Comment by klept0** [comment]
If your problem is resolved - please close this issue out.
