### ISSUE TITLE
[BUG] OSError: [Errno 8] Exec format error:

### ISSUE THREAD

**Issue by Riffcat** [charlesbel/Microsoft-Rewards-Farmer#340]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Installed and reinstalled every requirement multiple times and I stell get this error

### Copy and paste your error

username@raspberrypi:~/Microsoft-Rewards-Farmer $ python main.py
2023-09-09 13:45:38,262 [INFO] ********************username@icloud.com********************
2023-09-09 13:45:39,536 [INFO] Using default request storage
2023-09-09 13:45:39,619 [INFO] Created proxy listening on 127.0.0.1:42207
2023-09-09 13:45:39,621 [INFO] Using undetected_chromedriver
2023-09-09 13:45:41,687 [INFO] patching driver executable /home/username/.local/share/undetected_chromedriver/undetected_chromedriver
2023-09-09 13:45:41,984 [ERROR] OSError: [Errno 8] Exec format error: '/home/username/.local/share/undetected_chromedriver/undetected_chromedriver'
Traceback (most recent call last):
  File "/home/username/Microsoft-Rewards-Farmer/main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "/home/username/Microsoft-Rewards-Farmer/main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "/home/username/Microsoft-Rewards-Farmer/src/browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "/home/username/Microsoft-Rewards-Farmer/src/browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
  File "/home/username/.local/lib/python3.9/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/username/.local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/username/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/username/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    self.service.start()
  File "/home/username/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 105, in start
    self._start_process(self._path)
  File "/home/username/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 206, in _start_process
    self.process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/username/.local/share/undetected_chromedriver/undetected_chromedriver'

### Screenshots

The -v doesn't do anything as far as im concerned

### Value of dashboard variable

        var dashboard = {"userStatus":{"levelInfo":{"activeLevel":"Level2","activeLevelName":"Level 2","progress":1754,"progressMax":500,"levels":

**Comment by simon511000** [comment]
Are you on arm64 ?

**Comment by Riffcat** [comment]
> Are you on arm64 ?

Yes, rasperry pi 3

**Comment by simon511000** [comment]
So you have to download Chrome Driver manually for arm64 : https://github.com/electron/electron/releases/

**Comment by Riffcat** [comment]
> So you have to download Chrome Driver manually for arm64 : https://github.com/electron/electron/releases/

I still get the same error message after installing Chrome Driver from the link provided

**Comment by theskid31** [comment]
> > So you have to download Chrome Driver manually for arm64 : https://github.com/electron/electron/releases/
> 
> I still get the same error message after installing Chrome Driver from the link provided

did you fix this,if so what is the command to download in pi terminal

**Comment by Riffcat** [comment]
> > > So you have to download Chrome Driver manually for arm64 : https://github.com/electron/electron/releases/
> > 
> > 
> > I still get the same error message after installing Chrome Driver from the link provided
> 
> did you fix this,if so what is the command to download in pi terminal

Sadly I have not fixed this issue

**Comment by theskid31** [comment]
> > > > So you have to download Chrome Driver manually for arm64 : https://github.com/electron/electron/releases/
> > > 
> > > 
> > > I still get the same error message after installing Chrome Driver from the link provided
> > 
> > 
> > did you fix this,if so what is the command to download in pi terminal
> 
> Sadly I have not fixed this issue

but how did you install the chromedriver

**Comment by theskid31** [comment]
> > > > So you have to download Chrome Driver manually for arm64 : https://github.com/electron/electron/releases/
> > > 
> > > 
> > > I still get the same error message after installing Chrome Driver from the link provided
> > 
> > 
> > did you fix this,if so what is the command to download in pi terminal
> 
> Sadly I have not fixed this issue

i found this i suppose if you can figure how to install it ,please let me know
[https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/459](url)

**Comment by theskid31** [comment]
on my way to making this work
i just need to find where i can point msrewards farmer to the new chromedriver
take a look here they've done something similar
https://github.com/Yudaotor/EsportsHelper/issues/30#issuecomment-1515617281
