### ISSUE TITLE
[BUG] Ubuntu VPS

### ISSUE THREAD

**Issue by ridai260** [charlesbel/Microsoft-Rewards-Farmer#349]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Running on Ubuntu 20.04, does this work on VPS? If not that might explain this issue.

### Copy and paste your error

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "/home/ridai/scripts/Microsoft-Rewards-Farmer/src/__init__.py", line 1, in <module>
    from .browser import Browser
  File "/home/ridai/scripts/Microsoft-Rewards-Farmer/src/browser.py", line 12, in <module>
    from src.userAgentGenerator import GenerateUserAgent
  File "/home/ridai/scripts/Microsoft-Rewards-Farmer/src/userAgentGenerator.py", line 8, in <module>
    class GenerateUserAgent:
  File "/home/ridai/scripts/Microsoft-Rewards-Farmer/src/userAgentGenerator.py", line 34, in GenerateUserAgent
    browserConfig: dict[str, Any],
TypeError: 'type' object is not subscriptable

### Screenshots

ridai:~/scripts/Microsoft-Rewards-Farmer$ python3 main.py -v
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "/home/ridai/scripts/Microsoft-Rewards-Farmer/src/__init__.py", line 1, in <module>
    from .browser import Browser
  File "/home/ridai/scripts/Microsoft-Rewards-Farmer/src/browser.py", line 12, in <module>
    from src.userAgentGenerator import GenerateUserAgent
  File "/home/ridai/scripts/Microsoft-Rewards-Farmer/src/userAgentGenerator.py", line 8, in <module>
    class GenerateUserAgent:
  File "/home/ridai/scripts/Microsoft-Rewards-Farmer/src/userAgentGenerator.py", line 34, in GenerateUserAgent
    browserConfig: dict[str, Any],
TypeError: 'type' object is not subscriptable

### Value of dashboard variable

I can't find this?

**Comment by TeamakerScarlet** [comment]
Same Error In Ubuntu 20 with Python3.8 
```
python main.py 
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.4) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "/home/davexue/workSpace/MRF/Microsoft-Rewards-Farmer/src/__init__.py", line 1, in <module>
    from .browser import Browser
  File "/home/davexue/workSpace/MRF/Microsoft-Rewards-Farmer/src/browser.py", line 12, in <module>
    from src.userAgentGenerator import GenerateUserAgent
  File "/home/davexue/workSpace/MRF/Microsoft-Rewards-Farmer/src/userAgentGenerator.py", line 8, in <module>
    class GenerateUserAgent:
  File "/home/davexue/workSpace/MRF/Microsoft-Rewards-Farmer/src/userAgentGenerator.py", line 34, in GenerateUserAgent
    browserConfig: dict[str, Any],
TypeError: 'type' object is not subscriptable
```

>
