### ISSUE TITLE
i keep getting this error when i run it on idle, i'm not that good at this... any help

### ISSUE THREAD

**Issue by ikkiv2** [charlesbel/Microsoft-Rewards-Farmer#35]
Traceback (most recent call last):
  File "C:\Windows\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 735, in <module>
    browser = browserSetup(True, PC_USER_AGENT)
  File "C:\Windows\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 39, in browserSetup
    chrome_browser_obj = webdriver.Chrome(options=options)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

**Comment by charlesbel** [comment]
![Screenshot](https://i.stack.imgur.com/ZNbYA.png)
Make sure you have chrome installed on this location.
If not, install it there and it will correct the problem.
