### ISSUE TITLE
[BUG] Title I can't use it on Windows 11.

### ISSUE THREAD

**Issue by coco3t** [charlesbel/Microsoft-Rewards-Farmer#350]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

python3.10.8

### Copy and paste your error

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "C:\rewards\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "C:\rewards\src\browser.py", line 12, in <module>
    from src.userAgentGenerator import GenerateUserAgent
  File "C:\rewards\src\userAgentGenerator.py", line 8, in <module>
    class GenerateUserAgent:
  File "C:\rewards\src\userAgentGenerator.py", line 34, in GenerateUserAgent
    browserConfig: dict[str, Any],
TypeError: 'type' object is not subscriptable
I also try on venv，but not working

### Screenshots

![{EDA7FAD1-F218-479f-83DC-624A1EC08020}](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/98016714/15b5230f-f596-479f-9585-ebacf52c7853)

### Value of dashboard variable

don't have

**Comment by theskid31** [comment]
im on windows 11 ,fine here 
did you download all the things in requirements.txt?
as explained in the readme

**Comment by null774** [comment]
You're missing some packages, if you look at console it tells you issues are stemming from line 9 on main.py which is a reference to other class's in the src folder that require packages from requirements.txt dev needs to add an exception handler for expected errors

**Comment by klept0** [comment]
If your problem is resolved - please close this issue out.

**Comment by DarkFlyper** [comment]
Close issue if prob is solved
