### ISSUE TITLE
[BUG] Stuck at Logging-in

### ISSUE THREAD

**Issue by evox45** [charlesbel/Microsoft-Rewards-Farmer#352]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

If ran with the -v argument it opens the browser but doesnt go anywhere. 

### Copy and paste your error

2023-09-14 21:37:34,326 [INFO] Using default request storage
2023-09-14 21:37:34,333 [INFO] Created proxy listening on 127.0.0.1:5316
2023-09-14 21:37:34,334 [INFO] Using undetected_chromedriver
2023-09-14 21:37:35,272 [INFO] patching driver executable C:\Users\Evan\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2023-09-14 21:37:35,898 [INFO] Screen size: 1651x1214
2023-09-14 21:37:35,899 [INFO] Device size: 1596x1063
2023-09-14 21:37:35,915 [INFO] [LOGIN] Logging-in...

### Screenshots

![msrewards](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/39143517/f1fca36b-102c-45ff-9139-0dea54be0f3d)

### Value of dashboard variable

https://gist.github.com/evox45/615d8763efd06389fd68760ee08e127a

**Comment by yuuyuu0514** [comment]
Hey, I have the same problem for 2 days. In my case, after struggling to log in, the error message below will be displayed:

> 2023-09-14 18:18:31,819 [ERROR] TimeoutException: Message: timeout: Timed out receiving message from renderer: -306.606
>   (Session info: chrome=117.0.5938.63)
> Stacktrace:
> 	GetHandleVerifier [0x00B8CE43+45171]
> 	(No symbol) [0x00B19091]
> 	(No symbol) [0x00A0BE1D]
> 	(No symbol) [0x009FE1F8]
> 	(No symbol) [0x009FE05A]
> 	(No symbol) [0x009FCDD2]
> 	(No symbol) [0x009FD5DA]
> 	(No symbol) [0x00A06EA5]
> 	(No symbol) [0x00A13C4A]
> 	(No symbol) [0x00A16C56]
> 	(No symbol) [0x009FDAFC]
> 	(No symbol) [0x00A13B60]
> 	(No symbol) [0x00A6DC55]
> 	(No symbol) [0x00A5AE46]
> 	(No symbol) [0x00A3675E]
> 	(No symbol) [0x00A378FD]
> 	GetHandleVerifier [0x00E45449+2897529]
> 	GetHandleVerifier [0x00E8DBFB+3194411]
> 	GetHandleVerifier [0x00E879D1+3169281]
> 	GetHandleVerifier [0x00C160C0+606960]
> 	(No symbol) [0x00B22E0C]
> 	(No symbol) [0x00B1EF98]
> 	(No symbol) [0x00B1F0BF]
> 	(No symbol) [0x00B117B7]
> 	BaseThreadInitThunk [0x771FFCC9+25]
> 	RtlGetAppContainerNamedObjectPath [0x77C77B1E+286]
> 	RtlGetAppContainerNamedObjectPath [0x77C77AEE+238]
> Traceback (most recent call last):
>   File "D:\Coding\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
>     executeBot(currentAccount, notifier, args)
>   File "D:\Coding\Microsoft-Rewards-Farmer-master\main.py", line 128, in executeBot
>     accountPointsCounter = Login(desktopBrowser).login()
>   File "D:\Coding\Microsoft-Rewards-Farmer-master\src\login.py", line 19, in login
>     self.webdriver.get("https://login.live.com/")
>   File "c:\users\*USERNAME*\src\undetected-chromedriver\undetected_chromedriver\__init__.py", line 629, in get_wrapped
>     return orig_get(*args, **kwargs)
>   File "c:\users\*USERNAME*\src\undetected-chromedriver\undetected_chromedriver\__init__.py", line 665, in get
>     return super().get(url)
>   File "C:\Users\*USERNAME*\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in get
>     self.execute(Command.GET, {"url": url})
>   File "C:\Users\*USERNAME*\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\*USERNAME*\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -306.606
>   (Session info: chrome=117.0.5938.63)
> Stacktrace:
> 	GetHandleVerifier [0x00B8CE43+45171]
> 	(No symbol) [0x00B19091]
> 	(No symbol) [0x00A0BE1D]
> 	(No symbol) [0x009FE1F8]
> 	(No symbol) [0x009FE05A]
> 	(No symbol) [0x009FCDD2]
> 	(No symbol) [0x009FD5DA]
> 	(No symbol) [0x00A06EA5]
> 	(No symbol) [0x00A13C4A]
> 	(No symbol) [0x00A16C56]
> 	(No symbol) [0x009FDAFC]
> 	(No symbol) [0x00A13B60]
> 	(No symbol) [0x00A6DC55]
> 	(No symbol) [0x00A5AE46]
> 	(No symbol) [0x00A3675E]
> 	(No symbol) [0x00A378FD]
> 	GetHandleVerifier [0x00E45449+2897529]
> 	GetHandleVerifier [0x00E8DBFB+3194411]
> 	GetHandleVerifier [0x00E879D1+3169281]
> 	GetHandleVerifier [0x00C160C0+606960]
> 	(No symbol) [0x00B22E0C]
> 	(No symbol) [0x00B1EF98]
> 	(No symbol) [0x00B1F0BF]
> 	(No symbol) [0x00B117B7]
> 	BaseThreadInitThunk [0x771FFCC9+25]
> 	RtlGetAppContainerNamedObjectPath [0x77C77B1E+286]
> 	RtlGetAppContainerNamedObjectPath [0x77C77AEE+238]
Note: my username of Windows has been replaced for privacy reasons. I hope this info helps to solve the problem.

**Comment by klept0** [comment]
nuke your sessions folder contents and try again - if that resolves the issue please close this

**Comment by evox45** [comment]
I now get stuck on this screen. I did nuke the sessions folder as well. 

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/39143517/8e7162ec-ceb5-4e67-8d81-f0e52bd92734)

**Comment by klept0** [comment]
1) kill that screenshot with your email else big brother might feel the need to do their thing
2) after clearing the sessions folder give it a reboot and see if it works then
3) proxy or no?

**Comment by evox45** [comment]
No Proxy

**Comment by klept0** [comment]
I assume you can login to the account with any issues on the same connection you are using. If you can and it takes a moment then you might need to increase some timing in the script - which is pretty easy.

**Comment by evox45** [comment]
I can yeah. Can you share where I'd increase this time. I'll have to look at it later tonight but maybe you could save me a bit of work. Thanks.

**Comment by shopbuy11** [comment]
I too started experiencing this issue today.   All worked fine yesterday, but somehow today none of my accounts work.   I can log into all of them manually without issue, but the bot is stuck at Logging in and then eventually times out.   Deleting the content of Sessions folder and rebooting don't help.  Any idea please?

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/136040705/5fb2c18e-9bed-4bee-8307-4c1d32ad503f)

**Comment by shopbuy11** [comment]
My issue seems identical to the OP.   When I disable headless, I can see that it just stays on the Google search screen, instead of going to the MS Rewards site.   That's got to be where the problem is.   Anyone please?

**Comment by GlitteringReturn** [comment]
> nuke your sessions folder contents and try again - if that resolves the issue please close this

Sorry, if I may ask what is the point of the sessions folder then? Why doesn't the bot remove this folder if it is unnecessary?

**Comment by GlitteringReturn** [comment]
By the way the reason I got this issue where I was stuck logging-in was because my accounts were locked by Microsoft.

**Comment by evox45** [comment]
> By the way the reason I got this issue where I was stuck logging-in was because my accounts were locked by Microsoft.

Is there any way to unlock it? Also how did you figure out they were locked? I seem to be able to log in normally.

**Comment by GlitteringReturn** [comment]
> > By the way the reason I got this issue where I was stuck logging-in was because my accounts were locked by Microsoft.
> 
> Is there any way to unlock it? Also how did you figure out they were locked? I seem to be able to log in normally.

I just tried to log in and my account was locked and I unlocked it using my phone number. It seems there must be something wrong with you bot, I would just redownload the bot and/or apply this to your bot: https://github.com/charlesbel/Microsoft-Rewards-Farmer/pull/276.

**Comment by shopbuy11** [comment]
Mine started working again today out of the blue, after being stuck for 2 weeks.   So maybe it's a M$FT issue...

**Comment by shopbuy11** [comment]
Well, it's stuck again today.   Guess it will be hit-and-miss from now on.  Thanks, Micros**t!

**Comment by GlitteringReturn** [comment]
> Well, it's stuck again today. Guess it will be hit-and-miss from now on. Thanks, Micros**t!

Sorry I cannot help, honestly issue doesn't happen with me anymore, might be something to do with your region, internet or your bot.

**Comment by shopbuy11** [comment]
> GlitteringReturn

Thanks.  Applying https://github.com/charlesbel/Microsoft-Rewards-Farmer/pull/276 seems to have helped so far for 2 days...

**Comment by GlitteringReturn** [comment]
> > GlitteringReturn
> 
> Thanks. Applying #276 seems to have helped so far for 2 days...

Wow, I completely forgot to recommend that you add #276, my bad.

**Comment by shopbuy11** [comment]
After 2 weeks of smooth sailing, the problem resurfaced today, even with #276 in place...  Again, it gets stuck at logging in, even when I do it manually in the browser, by going to https://login.live.com.    So it appears to be a MSFT problem, but if I log in from the rewards site, then it works because it adds a bunch of code to the URL.   Anyone have any ideas?

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/136040705/94beb688-9023-48e2-97b1-d8efb34e3085)

**Comment by bruno-lambreht** [comment]
I was having those problems, and I only reboot the router and, lol, it works!

**Comment by shopbuy11** [comment]
18 of my 20 accounts got banned today.   They are stepping things up or figured out a way to detect this bot.  No point doing this any more.  Party is over :(

**Comment by GlitteringReturn** [comment]
> 19 of my 20 accounts got banned today. They are stepping things up or figured out a way to detect this bot. No point doing this any more. Party is over :(

Where you redeeming only one gift per day? Maybe, you were using too many accounts?

**Comment by shopbuy11** [comment]
No, I was saving up my points on each account before redeeming.   So usually redeem once a week.   Too bad coz several of them had 20K+ points....

**Comment by GlitteringReturn** [comment]
> No, I was saving up my points on each account before redeeming. So usually redeem once a week. Too bad coz several of them had 20K+ points....

Redeem more regularly once per day, so that you do not accumulate too many points before getting banned. That is BS from Microsoft.

**Comment by Beusts** [comment]
same here
