### ISSUE TITLE
[BUG] JSONDecodeError : Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by beenruuu** [charlesbel/Microsoft-Rewards-Farmer#355]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

I have this error, how i can fix this?

### Copy and paste your error

2023-09-18 16:25:31,140 [ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\beenruuu\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\beenruuu\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 141, in executeBot
    accountPointsCounter = Searches(desktopBrowser).bingSearches(
  File "C:\Users\beenruuu\Desktop\Microsoft-Rewards-Farmer-master\src\searches.py", line 57, in bingSearches
    search_terms = self.getGoogleTrends(numberOfSearches)
  File "C:\Users\beenruuu\Desktop\Microsoft-Rewards-Farmer-master\src\searches.py", line 27, in getGoogleTrends
    trends = json.loads(r.text[6:])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Screenshots

![Windows PowerShell 18_09_2023 16_25_54](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/111244523/184dc6e9-56e3-4692-ad9d-bc9192da1ed6)

### Value of dashboard variable

idk

**Comment by beenruuu** [comment]
I have closed the cookies pop-up window and it has not given me an error again. If you could make it remove it automatically it would be fine, I also deleted the log.
I also want to know how I can make the window full screen since it recognizes a screen size that I don't have.

**Comment by Lemon553311-dev** [comment]
I have the same problem :(
