### ISSUE TITLE
[BUG] Error running via raspberry pi rasbian os

### ISSUE THREAD

**Issue by theskid31** [charlesbel/Microsoft-Rewards-Farmer#361]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

hi 
Can anyone help getting this error trying to run script via pi4

has anyone a solution please?

### Copy and paste your error

2023-09-23 11:21:41,635 [INFO] Using default request storage
2023-09-23 11:21:41,650 [INFO] Created proxy listening on 127.0.0.1:45229
2023-09-23 11:21:41,651 [INFO] Using undetected_chromedriver
2023-09-23 11:21:43,192 [INFO] patching driver executable /home/theskid/.local/share/undetected_chromedriver/undetected_chromedriver
2023-09-23 11:21:43,383 [ERROR] OSError: [Errno 8] Exec format error: '/home/theskid/.local/share/undetected_chromedriver/undetected_chromedriver'
Traceback (most recent call last):
  File "/home/theskid/rewards/main.py", line 26, in main
    executeBot(currentAccount, notifier, args)
  File "/home/theskid/rewards/main.py", line 138, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "/home/theskid/rewards/src/browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "/home/theskid/rewards/src/browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
  File "/home/theskid/.local/lib/python3.9/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/theskid/.local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/theskid/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/theskid/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    self.service.start()
  File "/home/theskid/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 105, in start
    self._start_process(self._path)
  File "/home/theskid/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 206, in _start_process
    self.process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/theskid/.local/share/undetected_chromedriver/undetected_chromedriver'

### Screenshots

none

### Value of dashboard variable

none

**Comment by AngelCanovas** [comment]
Had the same issue on my Pi 2, I solved it with the help of Vincent's comment [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/727#issuecomment-1216199477)

**Comment by theskid31** [comment]
getting error: dont know why it is saying file,directory doesnt exist ,any help tried renaming the file so many times
and using electrons driver?
`theskid@raspberrypi:~/rewards` $ python main.py
Traceback (most recent call last):
  File "/home/theskid/rewards/main.py", line 9, in <module>
    driver = uc.Chrome(
  File "/home/theskid/.local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/home/theskid/.local/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 150, in auto
    return self.patch_exe()
  File "/home/theskid/.local/lib/python3.9/site-packages/undetected_chromedriver/patcher.py", line 347, in patch_exe
    with io.open(self.executable_path, "r+b") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/theskid/.local/share/undetected_chromedriver/undeteted_chromedriver'

**Comment by AngelCanovas** [comment]
Might sound dumb but did you execute `cp /usr/bin/chromedriver /home/myuser/.local/share/undetected_chromedriver/chromedriver_copy` as it without changing `myuser` to your current user ?

Also in `browser.py` you need to change line 80 to `driver_executable_path="/home/myuser/.local/share/undetected_chromedriver/chromedriver_copy",` like vincent's comment said

**Comment by theskid31** [comment]
> Might sound dumb but did you execute `cp /usr/bin/chromedriver /home/myuser/.local/share/undetected_chromedriver/chromedriver_copy` as it without changing `myuser` to your current user ?
> 
> Also in `browser.py` you need to change line 80 to `driver_executable_path="/home/myuser/.local/share/undetected_chromedriver/chromedriver_copy",` like vincent's comment said

yes I change the myuser to theskid as i posted above,but i didnt try with the sudo command,but i think my os is screwed up with all the things ive been trying as i tried the cp command as root and that copied but would not run

as for line 80 in browser.py i didnt do that but also where do you add the code:
`import undetected_chromedriver as uc
driver = uc.Chrome(
    driver_executable_path="/home/myuser/.local/share/undetected_chromedriver/chromedriver_copy"
)
driver.get('https://nowsecure.nl')`

I added that to the start of main.py where did you add yours to?

**Comment by AngelCanovas** [comment]
@theskid31 
The steps I followed for it to work for me:
- First making sure chromedriver is installed `sudo apt install chromium-chromedriver`
- Copying chromedriver `cp /usr/bin/chromedriver /home/myuser/.local/share/undetected_chromedriver/chromedriver_copy`
- Changing driver implementation in browser.py (lines 77-81) to:
`driver = webdriver.Chrome(
            options=options,
            seleniumwire_options=seleniumwireOptions,
            driver_executable_path="/home/myuser/.local/share/undetected_chromedriver/chromedriver_copy",
        )
`
No need to add more code to main.py or browser.py

**Comment by theskid31** [comment]
> @theskid31 The steps I followed for it to work for me:
> 
> * First making sure chromedriver is installed `sudo apt install chromium-chromedriver`
> * Copying chromedriver `cp /usr/bin/chromedriver /home/myuser/.local/share/undetected_chromedriver/chromedriver_copy`
> * Changing driver implementation in browser.py (lines 77-81) to:
>   `driver = webdriver.Chrome( options=options, seleniumwire_options=seleniumwireOptions, driver_executable_path="/home/myuser/.local/share/undetected_chromedriver/chromedriver_copy", ) `
>   No need to add more code to main.py or browser.py

thanks for your reply
got it running but get the error:
[WARNING] could not detect version_main.therefore, we are assuming it is chrome 108 or higher

also there is a line in browser.py line 79:
`user_data_dir=self.userDataDir.as_posix(),`
did you remove this as it seems to error on it?

**Comment by theskid31** [comment]
@AngelCanovas Thanks I’ve solved the above issue by adding my chromium browser version directly in undetected-chromedriver’s python init.py file
Script is running okay but it doesn’t half fail a lot ,even using klepts fork with the mobile search fixes,got it running on pi 64bit os won fast sd card ,but I suspect it’s chromium browser, @AngelCanovas what os do you run it on and have you altered chromium browser as to run better?thanks

**Comment by DeadlyOmega** [comment]
> @theskid31 The steps I followed for it to work for me:
> 
> * First making sure chromedriver is installed `sudo apt install chromium-chromedriver`
> * Copying chromedriver `cp /usr/bin/chromedriver /home/myuser/.local/share/undetected_chromedriver/chromedriver_copy`
> * Changing driver implementation in browser.py (lines 77-81) to:
>   `driver = webdriver.Chrome( options=options, seleniumwire_options=seleniumwireOptions, driver_executable_path="/home/myuser/.local/share/undetected_chromedriver/chromedriver_copy", ) `
>   No need to add more code to main.py or browser.py

Hello, I did followed every step like explained but now I do get This error right here :
2023-10-15 18:39:58,538 [INFO] Using default request storage
2023-10-15 18:39:58,573 [INFO] Created proxy listening on 127.0.0.1:43985
2023-10-15 18:39:58,575 [INFO] Using undetected_chromedriver
2023-10-15 18:39:58,577 [ERROR] IsADirectoryError: [Errno 21] Is a directory: '/home/ubuntu/.local/share/undetected_chromedriver/chromedriver_copy'
Traceback (most recent call last):
  File "/home/mspoints/main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "/home/mspoints/main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mspoints/src/browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/mspoints/src/browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/dist-packages/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/usr/local/lib/python3.11/dist-packages/undetected_chromedriver/patcher.py", line 148, in auto
    ispatched = self.is_binary_patched(self.executable_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/undetected_chromedriver/patcher.py", line 339, in is_binary_patched
    with io.open(executable_path, "rb") as fh:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/ubuntu/.local/share/undetected_chromedriver/chromedriver_copy'



What can I do? Please help, im kinda new to linux, btw im using ubuntu server.

**Comment by AngelCanovas** [comment]
> > @theskid31 The steps I followed for it to work for me:
> > 
> > * First making sure chromedriver is installed `sudo apt install chromium-chromedriver`
> > * Copying chromedriver `cp /usr/bin/chromedriver /home/myuser/.local/share/undetected_chromedriver/chromedriver_copy`
> > * Changing driver implementation in browser.py (lines 77-81) to:
> >   `driver = webdriver.Chrome( options=options, seleniumwire_options=seleniumwireOptions, driver_executable_path="/home/myuser/.local/share/undetected_chromedriver/chromedriver_copy", ) `
> >   No need to add more code to main.py or browser.py
> 
> Hello, I did followed every step like explained but now I do get This error right here :
> 
> _2023-10-15 18:39:58,538 [INFO] Using default request storage 2023-10-15 18:39:58,573 [INFO] Created proxy listening on 127.0.0.1:43985 2023-10-15 18:39:58,575 [INFO] Using undetected_chromedriver 2023-10-15 18:39:58,577 [ERROR] IsADirectoryError: [Errno 21] Is a directory: '/home/ubuntu/.local/share/undetected_chromedriver/chromedriver_copy' Traceback (most recent call last): File "/home/mspoints/main.py", line 24, in main executeBot(currentAccount, notifier, args) File "/home/mspoints/main.py", line 127, in executeBot with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/mspoints/src/browser.py", line 41, in **init** self.webdriver = self.browserSetup() ^^^^^^^^^^^^^^^^^^^ File "/home/mspoints/src/browser.py", line 77, in browserSetup driver = webdriver.Chrome( ^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/dist-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in **init** super().**init**(*args, **kwargs) File "/usr/local/lib/python3.11/dist-packages/undetected_chromedriver/**init**.py", line 258, in **init** self.patcher.auto() File "/usr/local/lib/python3.11/dist-packages/undetected_chromedriver/patcher.py", line 148, in auto ispatched = self.is_binary_patched(self.executable_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/dist-packages/undetected_chromedriver/patcher.py", line 339, in is_binary_patched with io.open(executable_path, "rb") as fh: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ IsADirectoryError: [Errno 21] Is a directory: '/home/ubuntu/.local/share/undetected_chromedriver/chromedriver_copy'_
> 
> What can I do? Please help, im kinda new to linux, btw im using ubuntu server.

Seems like the error is related to not locating the chromedriver, maybe ubuntu server have other path to the chromedriver idk.
Try locating the chromedriver `sudo find / -type f -name chromedriver` and then modify the copy command according to the correct path.
Also check the /home/ubuntu/.local/share/undetected_chromedriver path to see if it exists, if not create that path and try again.
