### ISSUE TITLE
exceptions.NoSuchElementException[BUG]

### ISSUE THREAD

**Issue by raphalation** [charlesbel/Microsoft-Rewards-Farmer#37]
Restarting the program fixed the problem, but it happens fairly regularly and means that I have to often manually restart it (as I have it running automatically in task sheduler) 

**Error Log**
Paste the error log here.
5/44
[BING] 6/44
[BING] 7/44
[BING] 8/44
[BING] 9/44
[BING] 10/44
[BING] 11/44
[BING] 12/44
[BING] 13/44
[BING] 14/44
[BING] 15/44
Traceback (most recent call last):
  File "Z:\Users\rapha\Desktop\ms_rewards_farmer.py", line 759, in <module>
    bingSearches(browser, remainingSearches)
  File "Z:\Users\rapha\Desktop\ms_rewards_farmer.py", line 227, in bingSearches
    points = bingSearch(browser, word, isMobile)
  File "Z:\Users\rapha\Desktop\ms_rewards_farmer.py", line 240, in bingSearch
    searchbar = browser.find_element_by_id('sb_form_q')
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="sb_form_q"]"}
  (Session info: headless chrome=88.0.4324.150)

**Screenshot of the page**
Add a screenshot of the page where the error apeared.

**Source code of dashboard**
https://gist.github.com/raphalation/8f75f7225be18348b913f57bc2e7278a

**Comment by larakel1** [comment]
[BING] Starting Desktop and Edge Bing searches...
Traceback (most recent call last):
  File "C:\Users\quake\Desktop\m\ms_rewards_farmer.py", line 751, in <module>
    bingSearches(browser, remainingSearches)
  File "C:\Users\quake\Desktop\m\ms_rewards_farmer.py", line 215, in bingSearches
    search_terms = getGoogleTrends(numberOfSearches)
  File "C:\Users\quake\Desktop\m\ms_rewards_farmer.py", line 178, in getGoogleTrends
    google_trends = json.loads(r.text[6:])
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by charlesbel** [comment]
Mhhh, it seems to be a loading problem... Do you run it on a goob computer with a great internet speed ?

**Comment by charlesbel** [comment]
I close the issue due to no answer, you can reopen it when you want
