### ISSUE TITLE
[BUG] Error when run main.py

### ISSUE THREAD

**Issue by real-fbdn** [charlesbel/Microsoft-Rewards-Farmer#378]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [x] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Traceback (most recent call last):
  File "C:\Users\ayaan\Downloads\MSFARM\main.py", line 175, in <module>
    main()
  File "C:\Users\ayaan\Downloads\MSFARM\main.py", line 21, in main
    loadedAccounts = setupAccounts()
  File "C:\Users\ayaan\Downloads\MSFARM\main.py", line 118, in setupAccounts
    loadedAccounts = json.loads(accountPath.read_text(encoding="utf-8"))
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 5 (char 90)

### Copy and paste your error

Traceback (most recent call last):
  File "C:\Users\ayaan\Downloads\MSFARM\main.py", line 175, in <module>
    main()
  File "C:\Users\ayaan\Downloads\MSFARM\main.py", line 21, in main
    loadedAccounts = setupAccounts()
  File "C:\Users\ayaan\Downloads\MSFARM\main.py", line 118, in setupAccounts
    loadedAccounts = json.loads(accountPath.read_text(encoding="utf-8"))
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 5 (char 90)

### Screenshots

Traceback (most recent call last):
  File "C:\Users\ayaan\Downloads\MSFARM\main.py", line 175, in <module>
    main()
  File "C:\Users\ayaan\Downloads\MSFARM\main.py", line 21, in main
    loadedAccounts = setupAccounts()
  File "C:\Users\ayaan\Downloads\MSFARM\main.py", line 118, in setupAccounts
    loadedAccounts = json.loads(accountPath.read_text(encoding="utf-8"))
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ayaan\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 5 (char 90)

### Value of dashboard variable

null

**Comment by CodeBanana69** [comment]
what is your accounts.json file format? Should be this:
[
  {
    "username": "Your Email 1",
    "password": "Your Password 1",
    "proxy": "http://user:pass@host1:port"
  },
  {
    "username": "Your Email 2",
    "password": "Your Password 2",
    "proxy": "http://user:pass@host2:port"
  }
]
No proxy format:
[
  {
    "username": "Your Email 1",
    "password": "Your Password 1"
  },
  {
    "username": "Your Email 2",
    "password": "Your Password 2"
  }
]

**Make sure you remove the commas after the password text, common error**

**Comment by Totesfleisch** [comment]
Since OP hasnt replied and its been 5 Days, i just want to mention that i had the EXACT same Error, and fixed it by deleting the comma behind "password"

**Comment by royaltongue** [comment]
@Totesfleisch Can you show your config?

**Comment by real-fbdn** [comment]
> what is your accounts.json file format? Should be this:
> 
> [
> 
>   {
> 
>     "username": "Your Email 1",
> 
>     "password": "Your Password 1",
> 
>     "proxy": "http://user:pass@host1:port"
> 
>   },
> 
>   {
> 
>     "username": "Your Email 2",
> 
>     "password": "Your Password 2",
> 
>     "proxy": "http://user:pass@host2:port"
> 
>   }
> 
> ]
> 
> 
> 
> 
> 
> 
> 
> 
> 
> No proxy format:
> 
> [
> 
>   {
> 
>     "username": "Your Email 1",
> 
>     "password": "Your Password 1"
> 
>   },
> 
>   {
> 
>     "username": "Your Email 2",
> 
>     "password": "Your Password 2"
> 
>   }
> 
> ]
> 
> 
> 
> **Make sure you remove the commas after the password text, common error**

Im on my phone rn tomorrow ill show you. I used the non proxy format that looks like yours however since i used 1 account i removed the second account completely...

**Comment by real-fbdn** [comment]
> Since OP hasnt replied and its been 5 Days, i just want to mention that i had the EXACT same Error, and fixed it by deleting the comma behind "password"

YOOOOO I JUST REALISED I ACCIDENTALLY KEPT THE COMMA AFTER PASSWORD WHEN I TOOK AWAY THE PROXY LINE... i am so stupid, i will check and see if it works and if it works ill close issue.

**Comment by real-fbdn** [comment]
works tysm all of you

**Comment by CodeBanana69** [comment]
congratulations
