### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Sentaku1129** [charlesbel/Microsoft-Rewards-Farmer#384]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

python main.py Prompt the following error

### Copy and paste your error

2023-10-23 17:56:08,385 [INFO] ********************xxxxxx@outlook.com********************
2023-10-23 17:56:10,624 [INFO] Using default request storage
2023-10-23 17:56:10,629 [INFO] Created proxy listening on 127.0.0.1:34031
2023-10-23 17:56:10,629 [INFO] Using undetected_chromedriver
2023-10-23 17:56:12,554 [INFO] patching driver executable /home/sentaku/.local/share/undetected_chromedriver/undetected_chromedriver
2023-10-23 17:57:13,120 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:46405
from chrome not reachable
Stacktrace:
#0 0x55b3606f2fb3 <unknown>
#1 0x55b3603c62f6 <unknown>
#2 0x55b3603b1ffa <unknown>
#3 0x55b3603fda3c <unknown>
#4 0x55b3603f52a9 <unknown>
#5 0x55b360438ac6 <unknown>
#6 0x55b36042f713 <unknown>
#7 0x55b36040218b <unknown>
#8 0x55b360402f7e <unknown>
#9 0x55b3606b88d8 <unknown>
#10 0x55b3606bc800 <unknown>
#11 0x55b3606c6cfc <unknown>
#12 0x55b3606bd418 <unknown>
#13 0x55b36068a42f <unknown>
#14 0x55b3606e14e8 <unknown>
#15 0x55b3606e16b4 <unknown>
#16 0x55b3606f2143 <unknown>
#17 0x7f7a324a0ac3 <unknown>

Traceback (most recent call last):
  File "/home/sentaku/Desktop/Microsoft-Rewards-Farmer/main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "/home/sentaku/Desktop/Microsoft-Rewards-Farmer/main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "/home/sentaku/Desktop/Microsoft-Rewards-Farmer/src/browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "/home/sentaku/Desktop/Microsoft-Rewards-Farmer/src/browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
  File "/home/sentaku/.local/lib/python3.10/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/sentaku/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/sentaku/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/sentaku/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/sentaku/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/home/sentaku/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/sentaku/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/sentaku/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/home/sentaku/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:46405
from chrome not reachable
Stacktrace:
#0 0x55b3606f2fb3 <unknown>
#1 0x55b3603c62f6 <unknown>
#2 0x55b3603b1ffa <unknown>
#3 0x55b3603fda3c <unknown>
#4 0x55b3603f52a9 <unknown>
#5 0x55b360438ac6 <unknown>
#6 0x55b36042f713 <unknown>
#7 0x55b36040218b <unknown>
#8 0x55b360402f7e <unknown>
#9 0x55b3606b88d8 <unknown>
#10 0x55b3606bc800 <unknown>
#11 0x55b3606c6cfc <unknown>
#12 0x55b3606bd418 <unknown>
#13 0x55b36068a42f <unknown>
#14 0x55b3606e14e8 <unknown>
#15 0x55b3606e16b4 <unknown>
#16 0x55b3606f2143 <unknown>
#17 0x7f7a324a0ac3 <unknown>

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/71433417/41a894a3-839c-4956-92a9-78ea3414bab9)

### Value of dashboard variable

var dashboard = {"userStatus":{"levelInfo":{"activeLevel":"Level2","activeLevelName":"第 2 級","progress":663,"progressMax":500,"levels":[{"key":"Level1","active":false,"name":"第 1 級","tasks":[{"text":"免費內含於 Microsoft 帳戶","url":null}],"privileges":[{"text":"Microsoft Store でのお支払い 100 円ごとに 1 ポイント、さらに特定のご購入時にボーナス ポイントを獲得","url":"//www.microsoftstore.com"},{"text":"Microsoft Rewards のキャンペーンを参照してポイントを獲得","url":"/rewards/dashboard"},{"text":"メンバー限定セールや割引へのアクセス","url":null},{"text":"ポイントをギフト カード、抽選への応募、チャリティへの募金に引き換え","url":"/rewards/redeem"}]},{"key":"Level2","active":true,"name":"第 2 級","tasks":[{"text":"每個月至少賺取 500 點。","url":null}],"privileges":[{"text":"レベル 1 の Microsoft Store の特典と、レベル 2 限定のボーナス特典","url":null},{"text":"Microsoft Rewards のキャンペーンを参照してポイントを獲得","url":"/rewards/dashboard"},{"text":"メンバー限定セールや割引へのアクセス (レベル 2 メンバー向けの限定提供あり)","url":null},{"text":"Microsoft ブランドのリワードの引き換えが最大 10% オフ","url":null}]}],"benefitsPromotion":{"benefits":[{"key":"BingSearch","text":"Daily Bing search point limit (3 points per search)*","url":"https://www.bing.com/?FORM=MA1368","helpText":"* The Level 2 Bing search benefit is the sum of 150 points on PC and 100 points on mobile","supportedLevels":{"level1":"50","level2":"250","level2XBoxGold":"250"}},{"key":"EdgeSearch","text":"Bing search bonus daily cap for Microsoft Edge ","url":"https://www.microsoft.com/rewards/edge-bonus?form=ML18S8\u0026OCID=ML18S8\u0026rtc=1","helpText":null,"supportedLevels":{"level1":"5","level2":"20","level2XBoxGold":"20"}},{"key":"PointsDollarSpent","text":"Points earned per $ spent in Microsoft Store online**","url":"https://www.microsoft.com/store/b/home?rtc=1","helpText":"**Qualifying content only. \u003ca class=\u0027c-hyperlink\u0027 href=\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\u0027\u003eSee more\u003c/a\u003e for details.","supportedLevels":{"level1":"1:1","level2":"10:1","level2XBoxGold":"20:1"}},{"key":"PointsSeeDailyOffers","text":"Points for exploring daily offers","url":"https://account.microsoft.com/rewards","helpText":null,"supportedLevels":{"level1":"","level2":"","level2XBoxGold":""}},{"key":"MemberDiscounts","text":"Access to exclusive member sales and discounts","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"MemberInvites","text":"Occasional surprise invites to exclusive member-only events","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"RedeemOff","text":"Up to 10% off when redeeming from Microsoft brands","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}}],"supportedLevelKeys":["level1","level2","level2XBoxGold"],"supportedLevelTitles":["Level 1","Level 2","Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Game Pass Ultimate\u003c/span\u003e"],"supportedLevelTitlesMobile":["Level 1","Level 2","Level 2 +Xbox Game Pass Ultimate"],"activeLevel":"level2","name":"level_benefits","priority":1,"attributes":{"activeLevel":"level2","benefits":"[{ key: \u0027BingSearch\u0027, text: \u0027Daily Bing search point limit (3 points per search)*\u0027, url: \u0027https://www.bing.com/?FORM=MA1368\u0027, helpText: \u0027* The Level 2 Bing search benefit is the sum of 150 points on PC and 100 points on mobile\u0027, supportedLevels: { \u0027level1\u0027: \u002750\u0027, \u0027level2\u0027: \u0027250\u0027, level2XBoxGold: \u0027250\u0027 } }, { key: \u0027EdgeSearch\u0027, text: \u0027Bing search bonus daily cap for Microsoft Edge \u0027, url: \u0027https://www.microsoft.com/rewards/edge-bonus?form=ML18S8\u0026OCID=ML18S8\u0026rtc=1\u0027, supportedLevels: { \u0027level1\u0027: \u00275\u0027, \u0027level2\u0027: \u002720\u0027, level2XBoxGold: \u002720\u0027 } }, { key: \u0027PointsDollarSpent\u0027, text: \u0027Points earned per $ spent in Microsoft Store online**\u0027, url: \u0027https://www.microsoft.com/store/b/home?rtc=1\u0027, helpText: \u0027**Qualifying content only. \u003ca class=\\\u0027c-hyperlink\\\u0027 href=\\\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\\\u0027\u003eSee more\u003c/a\u003e for details.\u0027, supportedLevels: { \u0027level1\u0027: \u00271:1\u0027, \u0027level2\u0027: \u002710:1\u0027, level2XBoxGold: \u002720:1\u0027 } }, { key: \u0027PointsSeeDailyOffers\u0027, text: \u0027Points for exploring daily offers\u0027, url: \u0027https://account.microsoft.com/rewards\u0027, supportedLevels: { \u0027level1\u0027: \u0027\u0027, \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 } }, { key: \u0027MemberDiscounts\u0027, text: \u0027Access to exclusive member sales and discounts\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }  }, { key: \u0027MemberInvites\u0027, text: \u0027Occasional surprise invites to exclusive member-only events\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}, { key: \u0027RedeemOff\u0027, text: \u0027Up to 10% off when redeeming from Microsoft brands\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}]","hidden":"True","levelTitleMobile":"Level 1;Level 2;Level 2 +Xbox Game Pass Ultimate","supportedLevelKeys":"level1;level2;level2XBoxGold","supportedLevelTitle":"Level 1;Level 2;Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Game Pass Ultimate\u003c/span\u003e","give_eligible":"False","destination":""},"offerId":"","complete":false,"counter":0,"activityProgress":0,"activityProgressMax":0,"pointProgressMax":0,"pointProgress":0,"promotionType":"","promotionSubtype":"","title":"","extBannerTitle":"","titleStyle":"","theme":"","description":"","extBannerDescription":"","descriptionStyle":"","showcaseTitle":"","showcaseDescription":"","imageUrl":"","dynamicImage":"","smallImageUrl":"","backgroundImageUrl":"","showcaseBackgroundImageUrl":"","showcaseBackgroundLargeImageUrl":"","promotionBackgroundLeft":"","promotionBackgroundRight":"","iconUrl":"","animatedIconUrl":"","animatedLargeBackgroundImageUrl":"","destinationUrl":"","linkText":"","hash":"53b28ef7f02a15ccbb5b13e737b1ea7b4998ba9b611090e43e25a4e5f224c0da","activityType":"11","isRecurring":false,"isHidden":true,"isTestOnly":false,"isGiveEligible":false,"level":"","slidesCount":0,"legalText":"","legalLinkText":"","deviceType":""}},"availablePoints":7662,"lifetimePoints":20772,"lifetimePointsRedeemed":13110,"ePuid":"OQ_ZuocRLzAz8CY9CqFY-7NSbXHEWKqpSgTzn8bTXJr07mBu6t5p2rSbA3ZronYoaWVqGuJOG6Oxc2RbCYs4Tw","redeemGoal":{"name":null,"price":0,"provider":null,"disabled":false,"category":"","title":"","variableGoalSpecificTitle":"","smallImageUrl":"","mediumImageUrl":"","largeImageUrl":"","largeShowcaseImageUrl":"","description":{"itemGroupText":"","smallText":"","largeText":"","legalText":"","showcaseTitle":"","showcaseDescription":""},"showcase":false,"showcaseInAllCategory":false,"originalPrice":0,"discountedPrice":0,"popular":false,"isTestOnly":false,"groupId":"","inGroup":false,"isDefaultItemInGroup":false,"groupTitle":"","groupImageUrl":"","groupShowcaseImageUrl":"","instantWinGameId":"","instantWinPlayAgainSku":"","isLowInStock":false,"isOutOfStock":false,"getCodeMessage":"","disableEmail":false,"stockMessage":"","comingSoonFlag":false,"isGenericDonation":false,"isVariableRedemptionItem":false,"variableRedemptionItemCurrencySymbol":null,"variableRedemptionItemMin":0,"variableRedemptionItemMax":0,"variableItemConfigPointsToCurrencyConversionRatio":0.0,"isAutoRedeem":false},"counters":{"pcSearch":[{"name":"JAJP_search_level2_PC_MemberCenter","priority":5,"attributes":{"layout":"MissionTaskLayout","foreground _color":"#00B294","state":"Complete","schemaName":"Rewards.Message","title":"パソコンで検索","link_text":"検索で稼ぐ","description":"パソコン検索で3ポイント、1日ごとに最大90ポイント獲得","destination":"/news?q=ニュース\u0026FORM=ML11Z9\u0026CREA=ML11Z9\u0026wt.mc_id=ML11Z9\u0026rnoreward=1\u0026rnoreward=1","image":"//az15297.vo.msecnd.net/images/rewards/membercenter/missions/PC-SearchEarn_108x70.jpg","small_image":"//az15297.vo.msecnd.net/images/rewards/membercenter/missions/Mobile/Laptop-yellow-75x75px.png","xboxapp_icon":"//az15297.vo.msecnd.net/images/rewards/xboxapp/75x75/bing_v2.png","xboxapp_modal_header":"パソコンとXboxで検索してポイント獲得","xboxapp_modal_description":"パソコンとXboxで3ポイント獲得、1日ごとに最大90ポイント獲得.","xboxapp_modal_primary_link_text":"マイクロソフトBingで検索","xboxapp_modal_primary_link_destination":"bing://home?ref=rewardscounter","app_package_family_name":"Microsoft.BingXbox_8wekyb3d8bbwe","xboxapp_modal_image":"http://az15297.vo.msecnd.net/images/rewards/xboxapp/counters/coins.png","answerScenario.Tag":"PCSearch","classification.Tag":"PCSearch","classification.ShowProgress":"True","type":"search","recurring":"true","progress":"90","max":"90","complete":"True","offerid":"WW_search_global_level2_PC","give_eligible":"True"},"offerId":"WW_search_global_level2_PC","complete":true,"counter":0,"activityProgress":0,"activityProgressMax":0,"pointProgressMax":90,"pointProgress":90,"promotionType":"search","promotionSubtype":"","title":"パソコンで検索","extBannerTitle":"","titleStyle":"","theme":"","description":"パソコン検索で3ポイント、1日ごとに最大90ポイント獲得","extBannerDescription":"","descriptionStyle":"","showcaseTitle":"","showcaseDescription":"","imageUrl":"//az15297.vo.msecnd.net/images/rewards/membercenter/missions/PC-SearchEarn_108x70.jpg","dynamicImage":"","smallImageUrl":"//az15297.vo.msecnd.net/images/rewards/membercenter/missions/Mobile/Laptop-yellow-75x75px.png","backgroundImageUrl":"","showcaseBackgroundImageUrl":"","showcaseBackgroundLargeImageUrl":"","promotionBackgroundLeft":"","promotionBackgroundRight":"","iconUrl":"","animatedIconUrl":"","animatedLargeBackgroundImageUrl":"","destinationUrl":"/news?q=ニュース\u0026FORM=ML11Z9\u0026CREA=ML11Z9\u0026wt.mc_id=ML11Z9\u0026rnoreward=1\u0026rnoreward…

**Comment by shopbuy11** [comment]
Make sure you have Chrome installed and is running the latest 118 release

**Comment by jordicli** [comment]
I'm having the same error, chrome is installed and updated.

**Comment by guoliang** [comment]
I have same issue. Worked fine yesterday. And I have chrome 119 installed.

**Comment by wgajuraj** [comment]
Here's [solution](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/743#issuecomment-1219382829)

**Comment by SilentDelirium** [comment]
In the event the above solution from @wgajuraj doesn't work, or is confusing, take a look at [what I did to fix this and a couple other errors](https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/404#issue-2003193726) I have now and again.
