### ISSUE TITLE
no module named 'ipapi'

### ISSUE THREAD

**Issue by zqold** [charlesbel/Microsoft-Rewards-Farmer#390]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

i was trying to do the last step of install but then it didnt work. i even tried downloading ipapi and importing it into python but i didnt work out how to do that.

### Copy and paste your error

Microsoft Windows [Version 10.0.19045.3570]
(c) Microsoft Corporation. All rights reserved.

C:\Users\patry>python C:\Users\patry\Desktop\Microsoft-Rewards-Farmer-master\main.py
Traceback (most recent call last):
  File "C:\Users\patry\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "C:\Users\patry\Desktop\Microsoft-Rewards-Farmer-master\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "C:\Users\patry\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 8, in <module>
    import ipapi
ModuleNotFoundError: No module named 'ipapi'

C:\Users\patry>

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/123830266/c7b35d7f-e586-4820-b8ce-60a52bebf6c3)

### Value of dashboard variable

didnt get to that part

**Comment by julian12517** [comment]
also having this bug

**Comment by ohioohio** [comment]
same here

**Comment by CodeBanana69** [comment]
Install ipapi:

pip install ipapi


Tell me what happens after that

**Comment by SilentDelirium** [comment]
I got this issue when i had a different python version installed. guessing it's an issue with the virtual environment of the script playing nicely with a console command. If installing ipapi doesn't solve the issue, consider removing any version of python that might be incompatible. I can't recall of the brain-top, is this built with 3.8? I feel like it's 3.8...
