### ISSUE TITLE
[ERROR] TypeError: Binary Location Must be a String

### ISSUE THREAD

**Issue by Shirotaku** [charlesbel/Microsoft-Rewards-Farmer#399]
When I run the script, I get the following error. Is this an error on my site? If so, anybody knows how to fix it?

```2023-11-12 17:02:34 2023-11-12 16:02:34,799 [INFO] Using default request storage
2023-11-12 17:02:34 2023-11-12 16:02:34,806 [INFO] Created proxy listening on 127.0.0.1:37113
2023-11-12 17:02:34 2023-11-12 16:02:34,806 [INFO] Using undetected_chromedriver
2023-11-12 17:02:35 2023-11-12 16:02:35,523 [INFO] patching driver executable /root/.local/share/undetected_chromedriver/undetected_chromedriver
2023-11-12 17:02:35 2023-11-12 16:02:35,551 [ERROR] TypeError: Binary Location Must be a String
2023-11-12 17:02:35 Traceback (most recent call last):
2023-11-12 17:02:35   File "/python/main.py", line 24, in main
2023-11-12 17:02:35     executeBot(currentAccount, notifier, args)
2023-11-12 17:02:35   File "/python/main.py", line 127, in executeBot
2023-11-12 17:02:35     with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
2023-11-12 17:02:35          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-12 17:02:35   File "/python/src/browser.py", line 41, in __init__
2023-11-12 17:02:35     self.webdriver = self.browserSetup()
2023-11-12 17:02:35                      ^^^^^^^^^^^^^^^^^^^
2023-11-12 17:02:35   File "/python/src/browser.py", line 77, in browserSetup
2023-11-12 17:02:35     driver = webdriver.Chrome(
2023-11-12 17:02:35              ^^^^^^^^^^^^^^^^^
2023-11-12 17:02:35   File "/usr/local/lib/python3.12/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
2023-11-12 17:02:35     super().__init__(*args, **kwargs)
2023-11-12 17:02:35   File "/usr/local/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 372, in __init__
2023-11-12 17:02:35     options.binary_location = (
2023-11-12 17:02:35     ^^^^^^^^^^^^^^^^^^^^^^^
2023-11-12 17:02:35   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/options.py", line 52, in binary_location
2023-11-12 17:02:35     raise TypeError(self.BINARY_LOCATION_ERROR)
2023-11-12 17:02:35 TypeError: Binary Location Must be a String```

**Comment by bruno-lambreht** [comment]
Try:
pip install setuptools

**Comment by Shirotaku** [comment]
setuptools is actually installed

**Comment by masterherby88** [comment]
i think your local chrome installation is missing.

**Comment by paul0665** [comment]
update your undetected-chromedriver

**Comment by twintersx** [comment]
> i think your local chrome installation is missing.

LOL, this worked for me :)
Thanks!

**Comment by whte** [comment]
> > i think your local chrome installation is missing.
> 
> LOL, this worked for me :) Thanks!

did you install chrome?
