### ISSUE TITLE
[BUG] Google Search Trends - JSONDecodeError

### ISSUE THREAD

**Issue by charlesbel** [charlesbel/Microsoft-Rewards-Farmer#40]
[BING] Starting Desktop and Edge Bing searches...
Traceback (most recent call last):
  File "C:\Users\quake\Desktop\m\ms_rewards_farmer.py", line 751, in <module>
    bingSearches(browser, remainingSearches)
  File "C:\Users\quake\Desktop\m\ms_rewards_farmer.py", line 215, in bingSearches
    search_terms = getGoogleTrends(numberOfSearches)
  File "C:\Users\quake\Desktop\m\ms_rewards_farmer.py", line 178, in getGoogleTrends
    google_trends = json.loads(r.text[6:])
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

_Originally posted by @larakel1 in https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/37#issuecomment-783489119_

**Comment by charlesbel** [comment]
Could you add `print(r.text)` between line 177 and 178 and give me the output ?

**Comment by link2Eps1lon** [comment]
I met the same problem, JSONDecodeError. Could you please tell me how you solved it?

**Comment by ExperesSo** [comment]
> Could you add `print(r.text)` between line 177 and 178 and give me the output ?
WHAT py ?

**Comment by ExperesSo** [comment]
> Could you add `print(r.text)` between line 177 and 178 and give me the output ?
where add this
