### ISSUE TITLE
[BUG] JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Lemon553311-dev** [charlesbel/Microsoft-Rewards-Farmer#408]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

When the bot starts desktop edge bing searches ([BING] Starting Desktop Edge Bing searches...) it crashes because of this error

### Copy and paste your error

```py
 [ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 141, in executeBot
    accountPointsCounter = Searches(desktopBrowser).bingSearches(
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\src\searches.py", line 57, in bingSearches
    search_terms = self.getGoogleTrends(numberOfSearches)
  File "C:\Users\user\Downloads\Microsoft-Rewards-Farmer-master\src\searches.py", line 27, in getGoogleTrends
    trends = json.loads(r.text[6:])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/60439353/2f0dd6e7-1d7b-42e2-a47c-a4c9cb974c9a)

### Value of dashboard variable

https://gist.github.com/Lemon553311-dev/8a756f4181dcea9d70d48ad0b99ea81c

**Comment by Lectoid** [comment]
> Just use the corrected program made by nicoacu, he already solved it the last week: https://github.com/nicoacu/Microsoft-Rewards-Farmer/tree/8dd874c4853e787e754fe5bcf3a69480921de6dd

Seconded. I just downloaded this, unzipped it and let it run from the folder it created and it's working great so far.

**Comment by gufunkt-tacos** [comment]
> Just use the corrected program made by nicoacu, he already solved it the last week: https://github.com/nicoacu/Microsoft-Rewards-Farmer/tree/8dd874c4853e787e754fe5bcf3a69480921de6dd

I am having the same problem. I tried this, but I got the same error.

**Comment by Lemon553311-dev** [comment]
Me too. The fork attached there did not solve any issue.

пт, 15 дек. 2023 г., 12:50 gufunkt-tacos ***@***.***>:

**Comment by albertnica** [comment]
It's been a while since I had this error. I recommend you using the original one with Visual Studio Code, I'm using the script rn and works with less errors than with the terminal. Make sure you have Chrome and the requirements.txt updated.

**Comment by gufunkt-tacos** [comment]
> It's been a while since I had this error. I recommend you using the original one with Visual Studio Code, I'm using the script rn and works with less errors than with the terminal. Make sure you have Chrome and the requirements.txt updated.

Thanks for the quick reply. I tried to do what you said but I am still getting the same error. Any more help would be greatly appreciated. Hopefully, I'm not doing anything stupid.

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/99559662/c1ad48f2-7407-4805-853f-2e388bde2b4d)

**Comment by Lemon553311-dev** [comment]
Any update on this?

((((I used to use a website called Bing rewards farmer as an alternative
and it doesn't work for some reason (likely Microsoft put up some
restriction/filter on types of searches) )))).

 Is this project no longer maintained?

сб, 16 дек. 2023 г., 00:51 gufunkt-tacos ***@***.***>:
