### ISSUE TITLE
[BUG] Main.py not detecting undetected_chromedriver

### ISSUE THREAD

**Issue by GreenSussy** [charlesbel/Microsoft-Rewards-Farmer#424]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Upon running main.py after installing all requirements, I get this error (it's in VSCode so I could see the error)
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/114675511/e2487ec6-3018-4123-af8d-8eb296f0ad71)

Yes, I have correctly installed all requirements including undetected_chromedriver. Any fixes?

### Copy and paste your error

PS C:\Users\toni_\Downloads> & "C:/Program Files/Python312/python.exe" c:/Users/toni_/Downloads/Microsoft-Rewards-Farmer-master/main.py
Traceback (most recent call last):
  File "C:\Users\toni_\AppData\Roaming\Python\Python312\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 6, in <module>
    import undetected_chromedriver as uc
  File "C:\Users\toni_\AppData\Roaming\Python\Python312\site-packages\undetected_chromedriver\__init__.py", line 44, in <module>
    from .patcher import IS_POSIX
  File "C:\Users\toni_\AppData\Roaming\Python\Python312\site-packages\undetected_chromedriver\patcher.py", line 4, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\toni_\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "c:\Users\toni_\Downloads\Microsoft-Rewards-Farmer-master\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "c:\Users\toni_\Downloads\Microsoft-Rewards-Farmer-master\src\browser.py", line 9, in <module>
    import seleniumwire.undetected_chromedriver as webdriver
  File "C:\Users\toni_\AppData\Roaming\Python\Python312\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "C:\Users\toni_\AppData\Roaming\Python\Python312\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 8, in <module>
    raise ImportError(
ImportError: undetected_chromedriver not found. Install it with `pip install undetected_chromedriver`.

### Screenshots

None

### Value of dashboard variable

None

**Comment by MCTRACO** [comment]
Same issue

**Comment by 02tz** [comment]
install setuptools

**Comment by recklessop** [comment]
> install setuptools

I have setuptools installed, but still have the issue.

**Comment by albertnica** [comment]
just delete **sessions** folder and run it again, also you can verify if undetected_chromedriver is correctly installed and reconized by Code by opening a powershell terminal (with the + symbol, next to the trash bin) and typing pip install undetected_chromedriver

**Comment by GreenSussy** [comment]
@alfaplays I cannot find a sessions folder.

@02tz Doing that gives me a new error:

PS C:\Users\toni_> & "C:/Program Files/Python312/python.exe" c:/Users/toni_/Downloads/Microsoft-Rewards-Farmer-master/main.py
Traceback (most recent call last):
  File "c:\Users\toni_\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 175, in <module>   
    main()
  File "c:\Users\toni_\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 18, in main        
    setupLogging() 
    ^^^^^^^^^^^^^^
  File "c:\Users\toni_\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 40, in setupLogging
    handlers.TimedRotatingFileHandler(
  File "C:\Program Files\Python312\Lib\logging\handlers.py", line 214, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding=encoding,
  File "C:\Program Files\Python312\Lib\logging\handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1231, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\logging\__init__.py", line 1263, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\toni_\\logs\\activity.log'

Upon creating a folder called logs with activity.log inside of it, another error appears:

PS C:\Users\toni_> & "C:/Program Files/Python312/python.exe" c:/Users/toni_/Downloads/Microsoft-Rewards-Farmer-master/main.py
Traceback (most recent call last):
  File "c:\Users\toni_\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 175, in <module>
    main()
  File "c:\Users\toni_\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 21, in main
    loadedAccounts = setupAccounts()
                     ^^^^^^^^^^^^^^^
  File "c:\Users\toni_\Downloads\Microsoft-Rewards-Farmer-master\main.py", line 118, in setupAccounts
    loadedAccounts = json.loads(accountPath.read_text(encoding="utf-8"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 3 (char 81)

**Comment by albertnica** [comment]
Did you verified that you have installed undetected chromedriver? Can you send a screenshot of the console complete console of Visual Studio Code? I can't see the lower part in the one you sent.

**Comment by recklessop** [comment]
Deleting the Sessions folder fixed this issue for me on Ubuntu.

**Comment by GreenSussy** [comment]
@recklessop where is the sessions folder? Here is what mine looks like:
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/114675511/bd9684ac-f696-414a-b3fe-411bc5d0e0fb)

@alfaplays 
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/114675511/6db221b2-6412-4942-a375-66ead2493f20)

Yes, I verified that undetected chromedriver is uninstalled.

**Comment by RiotRuth** [comment]
is your chrome version up too date?

**Comment by Sunny-Shani** [comment]
Same issue my friend, any fixes?

**Comment by SapitoSucio** [comment]
`pip install setuptools` fixed it for me, I'm using python 3.12

**Comment by Sunny-Shani** [comment]
> `pip install setuptools` fixed it for me, I'm using python 3.12

Thankyou so much :) This is working.

**Comment by GreenSussy** [comment]
@SapitoSucio that didn't work for me unfortunately. Oh well....

**Comment by xnegx** [comment]
Same issue

after pip install setuptools
the error changed to ModuleNotFoundError: No module named 'blinker._saferef'

**Comment by aymaners** [comment]
> Same issue
> 
> after pip install setuptools the error changed to ModuleNotFoundError: No module named 'blinker._saferef'

same problem

**Comment by naughtok** [comment]
> Same issue
> 
> after pip install setuptools the error changed to ModuleNotFoundError: No module named 'blinker._saferef'

https://www.marekrost.cz/selenium-wire-how-to-resolve-blinker-saferef

**Comment by naughtok** [comment]
yeah. just install version 1.7.0 of blinker

**Comment by naughtok** [comment]
might have to downgrade selenium too

**Comment by tiipolp** [comment]
@naughtok installing 1.7 blinker worked for me, thanks alot
