### ISSUE TITLE
Error on bing searches

### ISSUE THREAD

**Issue by Nicksw21** [charlesbel/Microsoft-Rewards-Farmer#427]
I get this error message when it gets to the part of bing searches:

Traceback (most recent call last):
  File "C:\Users\xxxx\Documents\clothings\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\xxxx\Documents\clothings\Microsoft-Rewards-Farmer-master\main.py", line 141, in executeBot
    accountPointsCounter = Searches(desktopBrowser).bingSearches(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\Documents\clothings\Microsoft-Rewards-Farmer-master\src\searches.py", line 57, in bingSearches
    search_terms = self.getGoogleTrends(numberOfSearches)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\Documents\clothings\Microsoft-Rewards-Farmer-master\src\searches.py", line 27, in getGoogleTrends
    trends = json.loads(r.text[6:])
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by RiotRuth** [comment]
hi! ive experienced id say every bug imaginable. today when trying too startup, i got a new bug! my fix too so far every bug ive had is the following:

(also i love your \Documents\clothings. gotta keep the bot safe hahaha.) anyways:

1: go to Windows Settings

2: Type Reset in search.

3: Factory reset your computer, make sure you choose the option too only remove apps and NOT User files. itll uninstall all your apps (this includes python and all the modules, plus all other PIP, Visual studio code issues that may cause your bug) 

4: when finished, download MSwebdriver that matches your edge, same with chrome. have these in the directory that your bot is in.

5: install Python 3.11. DO NOT install 3.12 as it removed some stuff from earlier python versions which is needed for this bot.

6:  When in account.json, if you removed the proxy crap, it should look something like this: 
[
    {
        "username": "riogrghu",
        "password": "wqetwryeturytkuly"
    }
]

not this: 

[
    {
        "username": "riogrghu",
        "password": "wqetwryeturytkuly",
    }
]

(if you noticed, after password field, you do not want the , after it. this wont work.)

umm i have beginner friendly fixes. ill add them as i think of more, i hope these help!
(fyi i am new too python, this project as with other microsoft rewards farming repos has been my learning experiance. keep me in touch! id love too learn and or help)
