### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Endermagegg** [charlesbel/Microsoft-Rewards-Farmer#43]
Traceback (most recent call last):
  File "C:\Users\Jose Moreira\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 738, in <module>
    browser.get('https://account.microsoft.com/rewards/')
  File "C:\Users\Jose Moreira\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Jose Moreira\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Jose Moreira\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: headless chrome=88.0.4324.190)

**Comment by charlesbel** [comment]
As written, connection timed out. So check your internet connection and make it available while runing the bot. Il also could be an overload on bing servers but i dont think.
