### ISSUE TITLE
javascript error: dashboard is not defined

### ISSUE THREAD

**Issue by ArtesVilla92** [charlesbel/Microsoft-Rewards-Farmer#430]
I've had this problem for about a day.
I've tried doing the following things, but nothing seems to work:

2024-01-24 21:15:54,685 [ERROR] JavascriptException: Message: javascript error: dashboard is not defined
  (Session info: chrome=121.0.6167.85)
Stacktrace:
#0 0x5619aec8ed93 <unknown>
#1 0x5619ae972337 <unknown>
#2 0x5619ae97769a <unknown>
#3 0x5619ae979c47 <unknown>
#4 0x5619aea0005a <unknown>
#5 0x5619ae9e0442 <unknown>
#6 0x5619ae9ff12d <unknown>
#7 0x5619ae9e01e3 <unknown>
#8 0x5619ae9b0135 <unknown>
#9 0x5619ae9b113e <unknown>
#10 0x5619aec52e4b <unknown>
#11 0x5619aec56dfa <unknown>
#12 0x5619aec3f6d5 <unknown>
#13 0x5619aec57a6f <unknown>
#14 0x5619aec2369f <unknown>
#15 0x5619aec7c098 <unknown>
#16 0x5619aec7c262 <unknown>
#17 0x5619aec8df34 <unknown>
#18 0x7f399a322ac3 <unknown>

Traceback (most recent call last):
  File "/home/mattia/Scrivania/Project/Microsoft-Rewards-Farmer/main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "/home/mattia/Scrivania/Project/Microsoft-Rewards-Farmer/main.py", line 128, in executeBot
    accountPointsCounter = Login(desktopBrowser).login()
  File "/home/mattia/Scrivania/Project/Microsoft-Rewards-Farmer/src/login.py", line 43, in login
    points = self.utils.getAccountPoints()
  File "/home/mattia/Scrivania/Project/Microsoft-Rewards-Farmer/src/utils.py", line 146, in getAccountPoints
    return self.getDashboardData()["userStatus"]["availablePoints"]
  File "/home/mattia/Scrivania/Project/Microsoft-Rewards-Farmer/src/utils.py", line 116, in getDashboardData
    return self.webdriver.execute_script("return dashboard")
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 408, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: dashboard is not defined
  (Session info: chrome=121.0.6167.85)
Stacktrace:
#0 0x5619aec8ed93 <unknown>
#1 0x5619ae972337 <unknown>
#2 0x5619ae97769a <unknown>
#3 0x5619ae979c47 <unknown>
#4 0x5619aea0005a <unknown>
#5 0x5619ae9e0442 <unknown>
#6 0x5619ae9ff12d <unknown>
#7 0x5619ae9e01e3 <unknown>
#8 0x5619ae9b0135 <unknown>
#9 0x5619ae9b113e <unknown>
#10 0x5619aec52e4b <unknown>
#11 0x5619aec56dfa <unknown>
#12 0x5619aec3f6d5 <unknown>
#13 0x5619aec57a6f <unknown>
#14 0x5619aec2369f <unknown>
#15 0x5619aec7c098 <unknown>
#16 0x5619aec7c262 <unknown>
#17 0x5619aec8df34 <unknown>
#18 0x7f399a322ac3 <unknown>

1) I deleted the session
2) I uninstalled and reinstalled Chrome
3) I uninstalled and reinstalled the requirements
4) I used Autoupdate_main.py

OS: Linux Mint 21.2 Victoria
Python 3.10.12
requests  2.25.1
selenium 4.17.2
ipapi 1.0.4
undetected-chromedriver 3.5.4
selenium-wire 5.1.0

Log File:
[activity.log](https://github.com/charlesbel/Microsoft-Rewards-Farmer/files/14043542/activity.log)

**Comment by ExtremeMemes** [comment]
Same thing happening to me, on macos

Any solutions yet?

**Comment by ExtremeMemes** [comment]
Tested on windows, still continutes to occur.
