### ISSUE TITLE
[BUG] HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by paul0665** [charlesbel/Microsoft-Rewards-Farmer#439]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

latest chrome and package
py 3.10.6

### Copy and paste your error

2024-02-15 20:57:50,845 [INFO] Using default request storage
2024-02-15 20:57:50,859 [INFO] Created proxy listening on 127.0.0.1:51948
2024-02-15 20:57:50,859 [INFO] Using undetected_chromedriver
2024-02-15 20:57:51,817 [ERROR] HTTPError: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "F:\etc\Microsoft-Rewards-FarmerF1\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "F:\etc\Microsoft-Rewards-FarmerF1\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "F:\etc\Microsoft-Rewards-FarmerF1\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "F:\etc\Microsoft-Rewards-FarmerF1\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
  File "C:\etc\Python\Python310\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\etc\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\etc\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "C:\etc\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
  File "C:\etc\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\etc\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\etc\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\etc\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\etc\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\etc\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\etc\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/47947919/a70b5665-2c35-49e2-b61c-93090194a5bb)

### Value of dashboard variable

n/a

**Comment by Lectoid** [comment]
Seeing this too. Deleting the session folder doesn't do anything.

**Comment by Germanmv93** [comment]
Igual a mi, estaba funcionando sin problemas y de buenas a primeras me da ese error y no me deja entrar. Problema con las versiones de chrome/chormiun.

**Comment by xnuit** [comment]
My script was freezing I deleted the sessions folders, it finally worked but I had to cancel the script and now I have this error too.
I tried uninstalling/ reinstalling the pip libraries and alswo the whole folder but nothing worked.

**Comment by xnuit** [comment]
> My script was freezing I deleted the sessions folders, it finally worked but I had to cancel the script and now I have this error too. I tried uninstalling/ reinstalling the pip libraries and alswo the whole folder but nothing worked.

I went to my chrome parameters and updated the browser. I restarted the browser and the script is working fine again.
Seems like the pending update was the problem.

**If you have troubles launch the script with py main.py -v** to disable headless mode and see if there is any cookie/other popup that the script isn't handling well.

**Comment by Lectoid** [comment]
I changed nothing from this morning and it's working now.

**Comment by paul0665** [comment]
It work angan, weird bug.
Still dont know what cause this.

**Comment by Lectoid** [comment]
Getting this again. Working fine all morning.

**Comment by paul0665** [comment]
seem cause by undetected-chromedriver

[ultrafunkamsterdam/undetected-chromedriver/#1743](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1743)

**Comment by Lectoid** [comment]
> seem cause by undetected-chromedriver
> 
> [ultrafunkamsterdam/undetected-chromedriver/#1743](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1743)

Looks like changing a URL will fix it. Any idea where to fix it?

EDIT: I found it and fixed it with the new link in that post above. 
Path: C:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver

edit the patcher.py file
Change line 283 from:
download_url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/%s/%s/%s"
to
download_url = "https://storage.googleapis.com/chrome-for-testing-public/%s/%s/%s"

**Comment by paul0665** [comment]
If you cant find site-packages, run `python -m site`

**Comment by Sunny-Shani** [comment]
> > seem cause by undetected-chromedriver
> > [ultrafunkamsterdam/undetected-chromedriver/#1743](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1743)
> 
> Looks like changing a URL will fix it. Any idea where to fix it?
> 
> EDIT: I found it and fixed it with the new link in that post above. Path: C:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver
> 
> edit the patcher.py file Change line 283 from: download_url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/%s/%s/%s" to download_url = "https://storage.googleapis.com/chrome-for-testing-public/%s/%s/%s"

Thankyou so much, working fine now
