### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Endermagegg** [charlesbel/Microsoft-Rewards-Farmer#44]
Traceback (most recent call last):
  File "C:\Users\Jose Moreira\Desktop\Essenciais\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 748, in <module>
    remainingSearches, remainingSearchesM = getRemainingSearches(browser)
  File "C:\Users\Jose Moreira\Desktop\Essenciais\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 687, in getRemainingSearches
    progressDesktop = counters['pcSearch'][0]['pointProgress'] + counters['pcSearch'][1]['pointProgress']
KeyError: 'pcSearch'

**Comment by charlesbel** [comment]
In which country are you running ?

**Comment by Endermagegg** [comment]
> In which country are you running ?

Brazil
