### ISSUE TITLE
[BUG] Stuck at Logged-In!

### ISSUE THREAD

**Issue by Germanmv93** [charlesbel/Microsoft-Rewards-Farmer#440]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Hi, I'm from Spain. The program gets stuck on the rewards page. The page always keeps loading but doesn't move forward or do anything. I tried both the -v argument and the non-v argument.

### Copy and paste your error

2024-02-16 09:23:39,454 [INFO] ****************************************
2024-02-16 09:23:40,475 [INFO] Using default request storage
2024-02-16 09:23:40,480 [INFO] Created proxy listening on 127.0.0.1:52336
2024-02-16 09:23:40,480 [INFO] Using undetected_chromedriver
2024-02-16 09:23:41,080 [INFO] patching driver executable C:\Users\germa\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2024-02-16 09:23:41,665 [INFO] Screen size: 2012x1220
2024-02-16 09:23:41,666 [INFO] Device size: 1957x1069
2024-02-16 09:23:41,686 [INFO] [LOGIN] Logging-in...
2024-02-16 09:23:44,441 [INFO] [LOGIN] Writing email...
2024-02-16 09:23:45,552 [INFO] [LOGIN] Writing password...
2024-02-16 09:26:05,027 [INFO] [LOGIN] Logged-in !

### Screenshots

![Captura de pantalla 2024-02-16 092906](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/153599463/04597e1b-eda4-4538-b3f2-0a94c71f92d5)

### Value of dashboard variable

2024-02-16 09:31:05,200 [ERROR] TimeoutException: Message: timeout: Timed out receiving message from renderer: 296.970
  (Session info: chrome=121.0.6167.185)
Stacktrace:
        GetHandleVerifier [0x00DD1673+52979]
        (No symbol) [0x00D57961]
        (No symbol) [0x00C3DD3D]
        (No symbol) [0x00C2F03A]
        (No symbol) [0x00C2EE94]
        (No symbol) [0x00C2D84D]
        (No symbol) [0x00C2E0ED]
        (No symbol) [0x00C38A8A]
        (No symbol) [0x00C46F16]
        (No symbol) [0x00C4A176]
        (No symbol) [0x00C2E56D]
        (No symbol) [0x00C46D99]
        (No symbol) [0x00CAB6F9]
        (No symbol) [0x00C94286]
        (No symbol) [0x00C6C063]
        (No symbol) [0x00C6CECD]
        GetHandleVerifier [0x010E8D83+3294723]
        GetHandleVerifier [0x01126CC2+3548482]
        GetHandleVerifier [0x01121C9C+3527964]
        GetHandleVerifier [0x00E6870E+671630]
        (No symbol) [0x00D61EB4]
        (No symbol) [0x00D5D808]
        (No symbol) [0x00D5D92D]
        (No symbol) [0x00D4F7E0]
        BaseThreadInitThunk [0x769F7BA9+25]
        RtlInitializeExceptionChain [0x77C0BD2B+107]
        RtlClearBits [0x77C0BCAF+191]

**Comment by Emrys-Lee-XD** [comment]
https://github.com/klept0/MS-Rewards-Farmer
this fork should solve the problem

**Comment by Germanmv93** [comment]
2024-02-17 09:47:31,002 [INFO] Using default request storage
2024-02-17 09:47:31,006 [INFO] Created proxy listening on 127.0.0.1:50445
2024-02-17 09:47:31,006 [INFO] Using undetected_chromedriver
2024-02-17 09:47:31,257 [ERROR] HTTPError: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\germa\OneDrive\Escritorio\MS-Rewards-Farmer-master\main.py", line 47, in main
    earned_points = executeBot(currentAccount, notifier, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\germa\OneDrive\Escritorio\MS-Rewards-Farmer-master\main.py", line 221, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\germa\OneDrive\Escritorio\MS-Rewards-Farmer-master\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\germa\OneDrive\Escritorio\MS-Rewards-Farmer-master\src\browser.py", line 86, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\germa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\germa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\germa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\germa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by Emrys-Lee-XD** [comment]
Use Win+R to run
 %LOCALAPPDATA%\Programs\Python\**PythonVERSION**\Lib\site-packages
change PythonVERSION to your version like Python38, Python311,etc.
Then find
patcher.py
Open it with notpad o any coding program like Visual Studio Code
Using Ctrl+F find
download_url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/%s/%s/%s"
should be in line 238
then replace it with
download_url = "https://storage.googleapis.com/chrome-for-testing-public/%s/%s/%s"
save and quit
run script as usual

**Comment by proyb213** [comment]
> Use Win+R to run %LOCALAPPDATA%\Programs\Python*_PythonVERSION_*\Lib\site-packages change PythonVERSION to your version like Python38, Python311,etc. Then find patcher.py Open it with notpad o any coding program like Visual Studio Code Using Ctrl+F find download_url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/%s/%s/%s" should be in line 238 then replace it with download_url = "https://storage.googleapis.com/chrome-for-testing-public/%s/%s/%s" save and quit run script as usual

I dont have patcher.py in any of my site-packages folders

**Comment by Emrys-Lee-XD** [comment]
> > Use Win+R to run %LOCALAPPDATA%\Programs\Python*_PythonVERSION_*\Lib\site-packages change PythonVERSION to your version like Python38, Python311,etc. Then find patcher.py Open it with notpad o any coding program like Visual Studio Code Using Ctrl+F find download_url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/%s/%s/%s" should be in line 238 then replace it with download_url = "https://storage.googleapis.com/chrome-for-testing-public/%s/%s/%s" save and quit run script as usual
> 
> I dont have patcher.py in any of my site-packages folders

this is already fixed, try this version
https://github.com/klept0/MS-Rewards-Farmer
