### ISSUE TITLE
[BUG] Stuck at logged in

### ISSUE THREAD

**Issue by Shivamroy05** [charlesbel/Microsoft-Rewards-Farmer#441]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Traceback (most recent call last):
  File "C:\Users\shiva\OneDrive\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\shiva\OneDrive\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shiva\OneDrive\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shiva\OneDrive\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\shiva\AppData\Roaming\Python\Python312\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\shiva\AppData\Roaming\Python\Python312\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\shiva\AppData\Roaming\Python\Python312\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shiva\AppData\Roaming\Python\Python312\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

### Copy and paste your error

Traceback (most recent call last):
  File "C:\Users\shiva\OneDrive\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\shiva\OneDrive\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shiva\OneDrive\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shiva\OneDrive\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\shiva\AppData\Roaming\Python\Python312\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\shiva\AppData\Roaming\Python\Python312\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\shiva\AppData\Roaming\Python\Python312\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shiva\AppData\Roaming\Python\Python312\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

### Screenshots

![Screenshot (224)](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/142077320/e90ec993-2602-49d4-ac20-4a090d54d33c)

### Value of dashboard variable

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/142077320/7d1169af-d84b-4c65-a86e-f657f9d21189)

**Comment by Germanmv93** [comment]
Same for me

**Comment by Natriumpikant** [comment]
+1

**Comment by Emrys-Lee-XD** [comment]
Use Win+R to run
 %LOCALAPPDATA%\Programs\Python\**PythonVERSION**\Lib\site-packages
change PythonVERSION to your version like Python38, Python311,etc.
Then find
patcher.py
Open it with notpad o any coding program like Visual Studio Code
Using Ctrl+F find
download_url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/%s/%s/%s"
should be in line 238
then replace it with
download_url = "https://storage.googleapis.com/chrome-for-testing-public/%s/%s/%s"
save and quit
run script as usual

**Comment by Shivamroy05** [comment]
Thanks 🤩
Love u sir🧡🧡
