### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by hwhlee** [charlesbel/Microsoft-Rewards-Farmer#447]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Runtime error
HTTP Error 404
Browser does not open

### Copy and paste your error

D:\Microsoft-Rewards-Farmer-master-bk>main.py
←[38;5;39m2024-02-25 19:19:21,995 [INFO] ********************msrewards1234567@gmail.com********************←[0m
←[38;5;39m2024-02-25 19:19:22,423 [INFO] Using default request storage←[0m
←[38;5;39m2024-02-25 19:19:22,429 [INFO] Created proxy listening on 127.0.0.1:60858←[0m
←[38;5;39m2024-02-25 19:19:22,429 [INFO] Using undetected_chromedriver←[0m
←[38;5;196m2024-02-25 19:19:23,159 [ERROR] HTTPError: HTTP Error 404: Not Found←[0m
Traceback (most recent call last):
  File "D:\Microsoft-Rewards-Farmer-master-bk\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "D:\Microsoft-Rewards-Farmer-master-bk\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "D:\Microsoft-Rewards-Farmer-master-bk\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "D:\Microsoft-Rewards-Farmer-master-bk\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\hwhle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

### Screenshots

n/a browser does not open

### Value of dashboard variable

n/a browser does not open

**Comment by Emrys-Lee-XD** [comment]
https://github.com/klept0/MS-Rewards-Farmer
check this version

**Comment by hwhlee** [comment]
> https://github.com/klept0/MS-Rewards-Farmer check this version

Thanks.  Tried that but it still throws the same HTTP Error 404

**Comment by Emrys-Lee-XD** [comment]
> > https://github.com/klept0/MS-Rewards-Farmer check this version
> 
> Thanks. Tried that but it still throws the same HTTP Error 404

under the forlder try
pip install --upgrade -r requirements.txt

or use this in PowerShell to update all 
pip freeze | %{$_ -split '==' | Select -First 1} | %{pip install --upgrade $_}

**Comment by Speechy13** [comment]
> > > https://github.com/klept0/MS-Rewards-Farmer check this version
> > 
> > 
> > Thanks. Tried that but it still throws the same HTTP Error 404
> 
> under the forlder try pip install --upgrade -r requirements.txt
> 
> or use this in PowerShell to update all pip freeze | %{$_.split('==')[0]} | %{pip install --upgrade $_}

Yep this fixed it for me by running the 'pip install --upgrade -r requirements.txt'. Thanks!

**Comment by ChiIIerr** [comment]
Also fixed it for me! Thank you @Emrys-Lee-XD
