### ISSUE TITLE
[BUG] ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by gekkefries21** [charlesbel/Microsoft-Rewards-Farmer#453]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

every time I run main.py this happens. 

### Copy and paste your error

←[38;5;196m2024-03-26 14:04:16,985 [ERROR] WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.59)
Stacktrace:
        GetHandleVerifier [0x00BC4CE3+225091]
        (No symbol) [0x00AF4E31]
        (No symbol) [0x00999A7A]
        (No symbol) [0x009960BF]
        (No symbol) [0x0098B13C]
        (No symbol) [0x0098C1CF]
        (No symbol) [0x0098B3A3]
        (No symbol) [0x0098ADC3]
        (No symbol) [0x0098ACF3]
        (No symbol) [0x009893C3]
        (No symbol) [0x00989A1B]
        (No symbol) [0x0099BC78]
        (No symbol) [0x00A063D1]
        (No symbol) [0x009EF55C]
        (No symbol) [0x00A05CB0]
        (No symbol) [0x009EF2F6]
        (No symbol) [0x009C79B9]
        (No symbol) [0x009C879D]
        sqlite3_dbdata_init [0x01039A83+4064547]
        sqlite3_dbdata_init [0x0104108A+4094762]
        sqlite3_dbdata_init [0x0103B988+4072488]
        sqlite3_dbdata_init [0x00D3C9E9+930953]
        (No symbol) [0x00B00804]
        (No symbol) [0x00AFAD28]
        (No symbol) [0x00AFAE51]
        (No symbol) [0x00AECAC0]
        BaseThreadInitThunk [0x761EFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77917C5E+286]
        RtlGetAppContainerNamedObjectPath [0x77917C2E+238]
←[0m
Traceback (most recent call last):
  File "D:\downloads\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "D:\downloads\Microsoft-Rewards-Farmer-master\main.py", line 128, in executeBot
    accountPointsCounter = Login(desktopBrowser).login()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\downloads\Microsoft-Rewards-Farmer-master\src\login.py", line 19, in login
    self.webdriver.get("https://login.live.com/")
  File "C:\Users\Sam\AppData\Roaming\Python\Python311\site-packages\undetected_chromedriver\__init__.py", line 629, in get_wrapped
    return orig_get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sam\AppData\Roaming\Python\Python311\site-packages\undetected_chromedriver\__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Sam\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\Sam\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Sam\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=123.0.6312.59)
Stacktrace:
        GetHandleVerifier [0x00BC4CE3+225091]
        (No symbol) [0x00AF4E31]
        (No symbol) [0x00999A7A]
        (No symbol) [0x009960BF]
        (No symbol) [0x0098B13C]
        (No symbol) [0x0098C1CF]
        (No symbol) [0x0098B3A3]
        (No symbol) [0x0098ADC3]
        (No symbol) [0x0098ACF3]
        (No symbol) [0x009893C3]
        (No symbol) [0x00989A1B]
        (No symbol) [0x0099BC78]
        (No symbol) [0x00A063D1]
        (No symbol) [0x009EF55C]
        (No symbol) [0x00A05CB0]
        (No symbol) [0x009EF2F6]
        (No symbol) [0x009C79B9]
        (No symbol) [0x009C879D]
        sqlite3_dbdata_init [0x01039A83+4064547]
        sqlite3_dbdata_init [0x0104108A+4094762]
        sqlite3_dbdata_init [0x0103B988+4072488]
        sqlite3_dbdata_init [0x00D3C9E9+930953]
        (No symbol) [0x00B00804]
        (No symbol) [0x00AFAD28]
        (No symbol) [0x00AFAE51]
        (No symbol) [0x00AECAC0]
        BaseThreadInitThunk [0x761EFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77917C5E+286]
        RtlGetAppContainerNamedObjectPath [0x77917C2E+238]

D:\downloads\Microsoft-Rewards-Farmer-master>python main.py
←[38;5;39m2024-03-26 14:05:17,935 [INFO] ********************gekkefriesgen1********************←[0m
←[38;5;39m2024-03-26 14:05:18,881 [INFO] Using default request storage←[0m
←[38;5;39m2024-03-26 14:05:18,887 [INFO] Created proxy listening on 127.0.0.1:63536←[0m
←[38;5;39m2024-03-26 14:05:18,887 [INFO] Using undetected_chromedriver←[0m
←[38;5;39m2024-03-26 14:05:19,470 [INFO] patching driver executable C:\Users\Sam\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe←[0m
←[38;5;39m2024-03-26 14:05:20,141 [INFO] Screen size: 2309x1159←[0m
←[38;5;39m2024-03-26 14:05:20,141 [INFO] Device size: 2254x1008←[0m
←[38;5;39m2024-03-26 14:05:20,154 [INFO] [LOGIN] Logging-in...←[0m
←[38;5;196m2024-03-26 14:05:20,316 [ERROR] WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED

### Screenshots

.

### Value of dashboard variable

.

**Comment by MintOcha** [comment]
same issue here

**Comment by GrrGrrMan** [comment]
Same
