### ISSUE TITLE
[BUG] No module named 'blinker._saferef'

### ISSUE THREAD

**Issue by roie-r** [charlesbel/Microsoft-Rewards-Farmer#455]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

As the error says, missing module... not much to describe.

### Copy and paste your error

```
D:\Docs\_Code\Microsoft-Rewards-Farmer-master>python main.py -v
Traceback (most recent call last):
  File "D:\Docs\_Code\Microsoft-Rewards-Farmer-master\main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "D:\Docs\_Code\Microsoft-Rewards-Farmer-master\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "D:\Docs\_Code\Microsoft-Rewards-Farmer-master\src\browser.py", line 9, in <module>
    import seleniumwire.undetected_chromedriver as webdriver
  File "C:\Program Files\Python312\Lib\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "C:\Program Files\Python312\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 12, in <module>
    from seleniumwire.inspect import InspectRequestsMixin
  File "C:\Program Files\Python312\Lib\site-packages\seleniumwire\inspect.py", line 7, in <module>
    from seleniumwire import har
  File "C:\Program Files\Python312\Lib\site-packages\seleniumwire\har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "C:\Program Files\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "C:\Program Files\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tls.py", line 15, in <module>
    import seleniumwire.thirdparty.mitmproxy.options
  File "C:\Program Files\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\options.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import optmanager
  File "C:\Program Files\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\optmanager.py", line 9, in <module>
    import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef'
```

### Screenshots

1

### Value of dashboard variable

1

**Comment by cal4** [comment]
Fixed [here](https://github.com/charlesbel/Microsoft-Rewards-Farmer/pull/450/commits/f5f4fe45736701da4eca7b32b894ecb85032ece9). h/t https://www.marekrost.cz/selenium-wire-how-to-resolve-blinker-saferef

**Comment by roie-r** [comment]
Problem solved :)

**Comment by cal4** [comment]
@roie-r, might want to leave this open to get more visibility since my project is a fork

**Comment by PNP-MA** [comment]
added : blinker<1.8.0 to your requirements.txt and then : pip install -r requirements.txt
