### ISSUE TITLE
[BUG] Not pasting the email id and continuously clicking "Next"

### ISSUE THREAD

**Issue by pradumn29** [charlesbel/Microsoft-Rewards-Farmer#457]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

While trying to loging-in it is continuously hitting "Next" button without pasting the email-id

### Copy and paste your error

2024-06-03 03:56:31,768 [ERROR] ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=125.0.6422.141)
Stacktrace:
        GetHandleVerifier [0x00CAB8E3+45827]
        (No symbol) [0x00C3DCC4]
        (No symbol) [0x00B3138D]
        (No symbol) [0x00B6CED9]
        (No symbol) [0x00B6B825]
        (No symbol) [0x00B92DFC]
        (No symbol) [0x00B68075]
        (No symbol) [0x00B93094]
        (No symbol) [0x00BAC034]
        (No symbol) [0x00B92B96]
        (No symbol) [0x00B66998]
        (No symbol) [0x00B6751D]
        GetHandleVerifier [0x00F64513+2899763]
        GetHandleVerifier [0x00FB793D+3240797]
        GetHandleVerifier [0x00D313B4+593364]
        GetHandleVerifier [0x00D382DC+621820]
        (No symbol) [0x00C470A4]
        (No symbol) [0x00C437A8]
        (No symbol) [0x00C43947]
        (No symbol) [0x00C359FE]
        BaseThreadInitThunk [0x75D17BA9+25]
        RtlInitializeExceptionChain [0x7742BD2B+107]
        RtlClearBits [0x7742BCAF+191]

Traceback (most recent call last):
  File "C:\Users\Mohi\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\Mohi\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 128, in executeBot
    accountPointsCounter = Login(desktopBrowser).login()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mohi\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\login.py", line 37, in login
    self.executeLogin()
  File "C:\Users\Mohi\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\login.py", line 53, in executeLogin
    self.webdriver.find_element(By.NAME, "loginfmt").send_keys(
  File "C:\Users\Mohi\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 231, in send_keys
    self._execute(
  File "C:\Users\Mohi\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mohi\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Mohi\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=125.0.6422.141)
Stacktrace:
        GetHandleVerifier [0x00CAB8E3+45827]
        (No symbol) [0x00C3DCC4]
        (No symbol) [0x00B3138D]
        (No symbol) [0x00B6CED9]
        (No symbol) [0x00B6B825]
        (No symbol) [0x00B92DFC]
        (No symbol) [0x00B68075]
        (No symbol) [0x00B93094]
        (No symbol) [0x00BAC034]
        (No symbol) [0x00B92B96]
        (No symbol) [0x00B66998]
        (No symbol) [0x00B6751D]
        GetHandleVerifier [0x00F64513+2899763]
        GetHandleVerifier [0x00FB793D+3240797]
        GetHandleVerifier [0x00D313B4+593364]
        GetHandleVerifier [0x00D382DC+621820]
        (No symbol) [0x00C470A4]
        (No symbol) [0x00C437A8]
        (No symbol) [0x00C43947]
        (No symbol) [0x00C359FE]
        BaseThreadInitThunk [0x75D17BA9+25]
        RtlInitializeExceptionChain [0x7742BD2B+107]
        RtlClearBits [0x7742BCAF+191]

### Screenshots

![Screenshot (9)](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/171517231/6335a0f8-f756-4867-a735-4e300e16123d)

### Value of dashboard variable

-

**Comment by XRominjol** [comment]
the same problem, I think Microsoft has changed something in authorization

**Comment by Giorgio145** [comment]
I'm pretty sure is because the CSS class that is used to check the mail field (.find_element(By.ID, f"{id}") has been changed, I've checked in the code but I'm too dumb to understand anything, the only thing I know is that now the id of the field is something like this "iNNNN" where N stands for a random number, where before was like "userInput" or smth like that hopefully it get fixed soon .-.

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/140664876/dbad94c3-d5e2-4f0f-81b4-60088a3d21e5)

**Comment by sealldeveloper** [comment]
To those here I'd move to: https://github.com/klept0/MS-Rewards-Farmer
