### ISSUE TITLE
[BUG] Typo In Code Solved With ChatGpt json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 5

### ISSUE THREAD

**Issue by nitaybl** [charlesbel/Microsoft-Rewards-Farmer#459]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

the bug happend because the accounts.json file have a , after the quotes on 4 line can be fixed by removing it

### Copy and paste your error

C:\Users\nitay\Downloads\MS-Rewards-Farmer-master>python main.py
Traceback (most recent call last):
  File "C:\Users\nitay\Downloads\MS-Rewards-Farmer-master\main.py", line 316, in <module>
    main()
  File "C:\Users\nitay\Downloads\MS-Rewards-Farmer-master\main.py", line 33, in main
    loadedAccounts = setupAccounts()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\nitay\Downloads\MS-Rewards-Farmer-master\main.py", line 179, in setupAccounts
    loadedAccounts = json.loads(accountPath.read_text(encoding="utf-8"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nitay\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nitay\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nitay\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 5 (char 90)

### Screenshots

idk

### Value of dashboard variable

idk

**Comment by vialonitasuhardiman** [comment]
format it like this :
[
    {
        "username": "email",
        "password": "password"
    }
]
