### ISSUE TITLE
[BUG] ConnectionResetError

### ISSUE THREAD

**Issue by Topfunplus** [charlesbel/Microsoft-Rewards-Farmer#467]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

cannot connect to the internet? i dont know

### Copy and paste your error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ml\Desktop\yitian\farmer\Microsoft-Rewards-Farmer\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\ml\Desktop\yitian\farmer\Microsoft-Rewards-Farmer\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "C:\Users\ml\Desktop\yitian\farmer\Microsoft-Rewards-Farmer\src\browser.py", line 37, in __init__
    ) = GenerateUserAgent().userAgent(self.browserConfig, mobile)
  File "C:\Users\ml\Desktop\yitian\farmer\Microsoft-Rewards-Farmer\src\userAgentGenerator.py", line 48, in userAgent
    app = self.getAppComponents(mobile)
  File "C:\Users\ml\Desktop\yitian\farmer\Microsoft-Rewards-Farmer\src\userAgentGenerator.py", line 119, in getAppComponents
    chromeVersion = self.getChromeVersion()
  File "C:\Users\ml\Desktop\yitian\farmer\Microsoft-Rewards-Farmer\src\userAgentGenerator.py", line 175, in getChromeVersion
    response = self.getWebdriverPage(
  File "C:\Users\ml\Desktop\yitian\farmer\Microsoft-Rewards-Farmer\src\userAgentGenerator.py", line 184, in getWebdriverPage
    response = requests.get(url)
  File "C:\Users\ml\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\ml\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\ml\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ml\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ml\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

### Screenshots

123

### Value of dashboard variable

123

**Comment by zhaojinshan1993** [comment]
Same issue
