### ISSUE TITLE
Sorry!

### ISSUE THREAD

**Issue by bucks9052** [charlesbel/Microsoft-Rewards-Farmer#5]
Sorry i have made many issues but the last one i just was missing dependencies but i had this error while running the farmer
Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 299, in <module>
    completeDailySet(browser)
  File "ms_rewards_farmer.py", line 191, in completeDailySet
    completeDailySetSurvey(browser, cardNumber)
  File "ms_rewards_farmer.py", line 137, in completeDailySetSurvey
    browser.find_element_by_id("btoption" + str(random.randint(0, 1))).click()
  File "/home/someone/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/someone/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/someone/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/someone/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="btoption1"]"}
  (Session info: chrome=86.0.4240.183)

**Comment by charlesbel** [comment]
This error is from the function that complete the daily survey of the day.
Could you please add `input('Arrived at the error')` before line 137, re-run the script, wait until the script arrive to the input line, and then make Ctrl+U on the Survey page and send me the source code of the page using a pastebin
