### ISSUE TITLE
[BUG] Closes when run

### ISSUE THREAD

**Issue by Nicknamewwwsss** [charlesbel/Microsoft-Rewards-Farmer#52]
**Error Log**
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002418C527F40>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002418C527F40>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Microsoft-Rewards-Farmer-master(1)\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 724, in <module>
    LANG, GEO, TZ = getCCodeLangAndOffset()
  File "C:\Users\Administrator\Downloads\Microsoft-Rewards-Farmer-master(1)\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 160, in getCCodeLangAndOffset
    nfo = ipapi.location()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\ipapi\ipapi.py", line 76, in location
    resp = get(url, headers=headers, **options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002418C527F40>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Screenshot of the page**
There is no screenshot since it closes almost instantly, but I have run it in IDLE, that's where I got the error above, if you would like I can provide a screenshot of that.

**Source code of dashboard**
Copy the source code of the [Microsoft Rewards Dashboard Page](https://account.microsoft.com/rewards) and paste it on [Gist](https://gist.github.com). Then share the link of the gist here.
Not sure how to do this step

Btw yes, all the requirements have been installed, Chrome is up to date same as the chromedriver

**Comment by charlesbel** [comment]
Are you able to access to ipapi.co/json from the same computer ?

**Comment by Nicknamewwwsss** [comment]
Sorry for the late reply, no ive not been able to access ipapi.co/json

**Comment by Nicknamewwwsss** [comment]
Okay so update, I was able to fix it, seems it was because I was using a different DNS server, switched back to Google DNS and it fixed it.
