### ISSUE TITLE
Name ipapi isn't defined

### ISSUE THREAD

**Issue by Trappy69420** [charlesbel/Microsoft-Rewards-Farmer#57]
Traceback (most recent call last):
  File "C:\Users\XXX\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 723, in <module>
    LANG, GEO, TZ = getCCodeLangAndOffset()
  File "C:\Users\XXX\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 159, in getCCodeLangAndOffset
    nfo = ipapi.location()
NameError: name 'ipapi' is not defined

**Comment by charlesbel** [comment]
Did you deleted "import ipapi" ??

**Comment by Trappy69420** [comment]
Nope

**Comment by charlesbel** [comment]
If there is the "import ipapi", there is no way to have this error, I don't really understand...

**Comment by charlesbel** [comment]
could you just open an idle, write `import ipapi` and then make `ipapi.location()` to check if this works well

**Comment by Trappy69420** [comment]
Ah sorry man. Yes you were correct the ipapi was gone. I opened it up in atom because i got a connection error which was only because I had a vpn active and thought it was something else and accidentally removed ipapi. Thank you so much and have a nice day.
