### ISSUE TITLE
[BUG] Connection refused

### ISSUE THREAD

**Issue by hh16201** [charlesbel/Microsoft-Rewards-Farmer#59]
*MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE*
hi . i triyed with 2 system
**Error Log**
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f122ac38a00>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f122ac38a00>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 724, in <module>
    LANG, GEO, TZ = getCCodeLangAndOffset()
  File "ms_rewards_farmer.py", line 160, in getCCodeLangAndOffset
    nfo = ipapi.location()
  File "/usr/local/lib/python3.8/dist-packages/ipapi/ipapi.py", line 76, in location
    resp = get(url, headers=headers, **options)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ipapi.co', port=443): Max retries exceeded with url: /json/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f122ac38a00>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Screenshot of the page**
![Screenshot from 2021-03-30 07-41-43](https://user-images.githubusercontent.com/81625325/112984336-c551e800-912c-11eb-9aea-1b3378007efd.png)
![Screenshot from 2021-03-30 07-48-26](https://user-images.githubusercontent.com/81625325/112984347-c71bab80-912c-11eb-97f7-ccf75306f388.png)

**Source code of dashboard**
Copy the source code of the [Microsoft Rewards Dashboard Page](https://account.microsoft.com/rewards) and paste it on [Gist](https://gist.github.com). Then share me the link of the gist here.

**Comment by charlesbel** [comment]
Are you able to access https://ipapi.co/json from these computers ?
