### ISSUE TITLE
Not finding css elements

### ISSUE THREAD

**Issue by njhughesSAS** [charlesbel/Microsoft-Rewards-Farmer#6]
My bot has had some issues finding css elements for buttons

`DevTools listening on ws://127.0.0.1:51992/devtools/browser/9e758f92-490e-417e-809d-8f025439ec09
[8104:8312:1110/094620.890:ERROR:display_layout.cc(562)] PlacementList must be sorted by first 8 bits of display_id
[5508:8944:1110/094645.061:ERROR:ssl_client_socket_impl.cc(960)] handshake failed; returned -1, SSL error code 1, net_error -101
Traceback (most recent call last):
  File "C:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer.py", line 299, in <module>
    completeDailySet(browser)
  File "C:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer.py", line 191, in completeDailySet
    completeDailySetSurvey(browser, cardNumber)
  File "C:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer.py", line 137, in completeDailySetSurvey
    browser.find_element_by_id("btoption" + str(random.randint(0, 1))).click()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="btoption0"]"}
  (Session info: chrome=86.0.4240.193)`

**Comment by charlesbel** [comment]
This error is from the function that complete the daily survey of the day.
Could you please add `input('Arrived at the error')` just before line 137, re-run the script, wait until the script arrive to the input line.
When it arrive to the survey page, make 'Inspect Element' on one of the answer button, and make a screenshot. Send me that screenshot here.

**Comment by njhughesSAS** [comment]
![error_button](https://user-images.githubusercontent.com/69064506/98734792-54fe2200-2357-11eb-86e6-785307fd325a.JPG)

**Comment by charlesbel** [comment]
Thanks, I think I know where is the error, could you please go to your microsoft rewards dashboard and make Ctrl+U to view the source code.
Then go to https://gist.github.com and follow this screenshot to create a gist, then share me the link of the gist : 
![Inkedgist-tuto_LI](https://user-images.githubusercontent.com/37935727/98736774-91f10580-23a5-11eb-9020-ab613051a1a7.jpg)

**Comment by njhughesSAS** [comment]
This is the source for the page with truth or dare creating the error 
https://gist.github.com/njhughesSAS/47161d5fa37c3e17b0edf75d7e807e54

this is may dashboard for the account source
https://gist.github.com/njhughesSAS/1da856e80a17ed0e7e34eda4220e8eac

**Comment by charlesbel** [comment]
I updated the script and I think it should work now

**Comment by njhughesSAS** [comment]
`DevTools listening on ws://127.0.0.1:4047/devtools/browser/4fc099ba-62ee-4a30-b2d8-d084893e4d5a
[3500:14440:1110/153350.242:ERROR:display_layout.cc(562)] PlacementList must be sorted by first 8 bits of display_id
[3500:14440:1110/153432.704:ERROR:display_layout.cc(562)] PlacementList must be sorted by first 8 bits of display_id
Traceback (most recent call last):
  File "C:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer.py", line 331, in <module>
    completeDailySet(browser)
  File "C:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer.py", line 223, in completeDailySet
    completeDailySetTrueOrFalse(browser, cardNumber)
  File "C:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer.py", line 179, in completeDailySetTrueOrFalse
    quizInfo = json.loads(browser.execute_script("return _w.rewardsQuizRenderInfo"))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict`
source
https://gist.github.com/njhughesSAS/86078641aa0f5245dee7d04f97da5110

**Comment by charlesbel** [comment]
I updated the script, could you retry ?

**Comment by njhughesSAS** [comment]
`DevTools listening on ws://127.0.0.1:50351/devtools/browser/92d8cf4b-a48e-4094-9af6-9bc551c7dee8
[11944:12508:1111/070813.342:ERROR:display_layout.cc(562)] PlacementList must be sorted by first 8 bits of display_id
Traceback (most recent call last):
  File "C:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer.py", line 332, in <module>
    completePunchCards(browser)
  File "C:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer.py", line 243, in completePunchCards
    if punchCard['parentPromotion']['complete'] == False and punchCard['parentPromotion']['promotionType'].split(',')[0] == "urlreward":
TypeError: 'NoneType' object is not subscriptable`

**Comment by charlesbel** [comment]
I fixed it !

**Comment by njhughesSAS** [comment]
For me the lightening quiz is just being skipped now and it moves on to the search function. My other thought is I could add a run menu to it for easier testing of each function.
