### ISSUE TITLE
error[BUG]

### ISSUE THREAD

**Issue by raphalation** [charlesbel/Microsoft-Rewards-Farmer#69]
*MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE*

DevTools listening on ws://127.0.0.1:63321/devtools/browser/25e41c89-b253-4a3f-b1f9-33a5d6a01650
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
Traceback (most recent call last):
  File "z:\Users\rapha\Documents\Microsoft-Rewards-Farmer\ms_rewards_farmer.py", line 754, in <module>
    login(browser, account['username'], account['password'])
  File "z:\Users\rapha\Documents\Microsoft-Rewards-Farmer\ms_rewards_farmer.py", line 56, in login
    browser.find_element_by_id('idSIButton9').click()
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input type="submit" id="idSIButton9" data-bind="
            attr: primaryButtonAttributes,
            externalCss: {
                'button': true,
                'primary': true },
            value: primaryButtonText() || str['CT_PWD_STR_SignIn_Button_Next'],
            hasFocus: focusOnPrimaryButton,
            click: primaryButton_onClick,
            enable: isPrimaryButtonEnabled,
            visible: isPrimaryButtonVisible,
            preventTabbing: primaryButtonPreventTabbing" class="button ext-button primary ext-primary" value="Next" disabled=""> is not clickable at point (522, 357). Other element would receive the click: <div class="lightbox-cover disable-lightbox" data-bind="css: { 'disable-lightbox': svr.bZ &amp;&amp; showLightboxProgress() }"></div>
  (Session info: headless chrome=89.0.4389.114)

**Comment by charlesbel** [comment]
This is a common error, just restart the script. I don't know how to fix it, if you know, make a pull request.
