### ISSUE TITLE
[BUG] Errors when using vpn

### ISSUE THREAD

**Issue by Lucas559-noob** [charlesbel/Microsoft-Rewards-Farmer#71]
With nordvpn, idk why, my internet always stop working when using it, maybe this is the reason

**Error Log**

```
C:\Users\Lucas\Desktop\Microsoft-Rewards-Farmer-master>ms_rewards_farmer.py
←[91m
███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗
████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝←[00m
←[95m        by Charles Bel (@charlesbel)               version 1.1
←[00m
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_
conn
    conn = connection.create_connection(
  File "C:\Python39\lib\site-packages\urllib3\util\connection.py", line 73, in c
reate_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in u
rlopen
    httplib_response = self._make_request(
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _
make_request
    self._validate_conn(conn)
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in
_validate_conn
    conn.connect()
  File "C:\Python39\lib\site-packages\urllib3\connection.py", line 353, in conne
ct
    conn = self._new_conn()
  File "C:\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_
conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection objec
t at 0x0000005D64B1F6D0>: Failed to establish a new connection: [Errno 11001] ge
taddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in u
rlopen
    retries = retries.increment(
  File "C:\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in incre
ment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipapi.co', port=443)
: Max retries exceeded with url: /json/ (Caused by NewConnectionError('<urllib3.
connection.HTTPSConnection object at 0x0000005D64B1F6D0>: Failed to establish a
new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lucas\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer
.py", line 729, in <module>
    LANG, GEO, TZ = getCCodeLangAndOffset()
  File "C:\Users\Lucas\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer
.py", line 200, in getCCodeLangAndOffset
    nfo = ipapi.location()
  File "C:\Python39\lib\site-packages\ipapi\ipapi.py", line 76, in location
    resp = get(url, headers=headers, **options)
  File "C:\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 542, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ipapi.co', port=4
43): Max retries exceeded with url: /json/ (Caused by NewConnectionError('<urlli
b3.connection.HTTPSConnection object at 0x0000005D64B1F6D0>: Failed to establish
 a new connection: [Errno 11001] getaddrinfo failed'))

C:\Users\Lucas\Desktop\Microsoft-Rewards-Farmer-master>ms_rewards_farmer.py
←[91m
███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗
████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝←[00m
←[95m        by Charles Bel (@charlesbel)               version 1.1

DevTools listening on ws://127.0.0.1:30960/devtools/browser/2be5414c-6d6d-456e-a
71c-541bfc6d4abd
[LOGIN] Logging-in...
Traceback (most recent call last):
  File "C:\Users\Lucas\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer
.py", line 754, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\Lucas\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer
.py", line 41, in login
    waitUntilVisible(browser, By.ID, 'loginHeader', 10)
  File "C:\Users\Lucas\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer
.py", line 146, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located(
(by_, selector)))
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line
80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


C:\Users\Lucas\Desktop\Microsoft-Rewards-Farmer-master>ms_rewards_farmer.py
←[91m
███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗
████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝←[00m
←[95m        by Charles Bel (@charlesbel)               version 1.1
←[00m
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_
conn
    conn = connection.create_connection(
  File "C:\Python39\lib\site-packages\urllib3\util\connection.py", line 96, in c
reate_connection
    raise err
  File "C:\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in c
reate_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Nenhuma conexão pôde ser feita porque a
 máquina de destino as recusou ativamente

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in u
rlopen
    httplib_response = self._make_request(
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _
make_request
    self._validate_conn(conn)
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in
_validate_conn
    conn.connect()
  File "C:\Python39\lib\site-packages\urllib3\connection.py", line 353, in conne
ct
    conn = self._new_conn()
  File "C:\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_
conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection objec
t at 0x000000B123DFF6D0>: Failed to establish a new connection: [WinError 10061]
 Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativament
e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in u
rlopen
    retries = retries.increment(
  File "C:\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in incre
ment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ipapi.co', port=443)
: Max retries exceeded with url: /json/ (Caused by NewConnectionError('<urllib3.
connection.HTTPSConnection object at 0x000000B123DFF6D0>: Failed to establish a
new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina
 de destino as recusou ativamente'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lucas\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer
.py", line 729, in <module>
    LANG, GEO, TZ = getCCodeLangAndOffset()
  File "C:\Users\Lucas\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer
.py", line 200, in getCCodeLangAndOffset
    nfo = ipapi.location()
  File "C:\Python39\lib\site-packages\ipapi\ipapi.py", line 76, in location
    resp = get(url, headers=headers, **options)
  File "C:\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 542, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ipapi.co', port=4
43): Max retries exceeded with url: /json/ (Caused by NewConnectionError('<urlli
b3.connection.HTTPSConnection object at 0x000000B123DFF6D0>: Failed to establish
 a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máqu
ina de destino as recusou ativamente'))
```

The problem is because i have not good vpn

**Comment by Lucas559-noob** [comment]
Hehe, never thought a free vpn(windscribe) so good

```
←[91m
███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗
████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝←[00m
←[95m        by Charles Bel (@charlesbel)               version 1.1

DevTools listening on ws://127.0.0.1:40603/devtools/browser/069e1b57-b5bc-4b2c-8
295-32040e5eb9a5
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Ensuring login on Bing...
←[92m[LOGIN] Logged-in successfully !←[00m
←[92m[POINTS] You have 763 points on your account !←[00m
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completing search of card 1
[DAILY SET] Completing quiz of card 2
[DAILY SET] Completing poll of card 3
←[92m[DAILY SET] Completed the Daily Set successfully !←[00m
[PUNCH CARDS] Trying to complete the Punch Cards...
←[92m[PUNCH CARDS] Completed the Punch Cards successfully !←[00m
[MORE PROMO] Trying to complete More Promotions...
←[92m[MORE PROMO] Completed More Promotions successfully !←[00m
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/32
[BING] 2/32
[BING] 3/32
[BING] 4/32
[BING] 5/32
[BING] 6/32
[BING] 7/32
[BING] 8/32
[BING] 9/32
[BING] 10/32
[BING] 11/32
[BING] 12/32
[BING] 13/32
[BING] 14/32
[BING] 15/32
[BING] 16/32
[BING] 17/32
[BING] 18/32
```
and still going :) maybe 1 hour every 2 days will be so good

**Comment by UnknownGreen** [comment]
Had the same issue but I managed to fix it by turning Cybersec off since it was causing issues with the farmer
