### ISSUE TITLE
[BUG] Script not catching all cards

### ISSUE THREAD

**Issue by DerMuffin** [charlesbel/Microsoft-Rewards-Farmer#83]
*MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE*

**Error Log**
Didnt get one because script "run as it should"

**Screenshot of the page**
No real error page. Rewards Dashboard just missing some green hooks after run the Script. They also dont work after a second time of running the script.

**Source code of dashboard**
https://gist.github.com/DerMuffin/07c66f80bfc54b13c92552d64bad5671

**Comment by DerMuffin** [comment]
[DAILY SET] Trying to complete the Daily Set...
Traceback (most recent call last):
  File "FolderPath\ms_rewards_farmer.py", line 798, in <module>
    completeDailySet(browser)
  File "FolderPath\ms_rewards_farmer.py", line 487, in completeDailySet
    d = getDashboardData(browser)['dailySetPromotions']
  File "FolderPath\ms_rewards_farmer.py", line 483, in getDashboardData
    dashboard = json.loads(dashboard)
  File "FolderPath\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "FolderPath\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "FolderPath\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ChiIIerr** [comment]
From what I can tell, it's the A, B, C quiz type of quests that are getting skipped, not running, or erroring out.

**Comment by FRKFFR** [comment]
me is the card (More activities) and
(Quests and Loyalty Cards) What the Script Doesn't Do
![Uploading image.png…]()
