### ISSUE TITLE
[BUG] the script does not switch accounts and displays an error

### ISSUE THREAD

**Issue by FRKFFR** [charlesbel/Microsoft-Rewards-Farmer#85]
←[91m
███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗
████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝←[00m
←[95m        by Charles Bel (@charlesbel)               version 2.0
←[00m
←[93m********************anononymous2002@gmx.fr********************←[00m

DevTools listening on ws://127.0.0.1:57159/devtools/browser/2830709b-a8c1-4e32-b139-3df77677e993
[LOGIN] Logging-in...
[LOGIN] Writing email...
Traceback (most recent call last):
  File "C:\Users\Sophie\Desktop\Nouveau dossier (4)\Microsoft-Rewards-Farmer-master2\ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\Sophie\Desktop\Nouveau dossier (4)\Microsoft-Rewards-Farmer-master2\ms_rewards_farmer.py", line 55, in login
    browser.execute_script("document.getElementById('i0118').value = '" + pwd + "';")
  File "C:\Users\Sophie\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\Sophie\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Sophie\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot set properties of null (setting 'value')
  (Session info: headless chrome=101.0.4951.54)

![image](https://user-images.githubusercontent.com/65563530/167250923-09b9ff1c-2e86-45d4-ba5f-4160a0fb04f7.png)

**Comment by FRKFFR** [comment]
ah it's good I find the cause of my problem the software blocks because it is on the login page by the Authenticator application after writing the email.

**Comment by FRKFFR** [comment]
you have to make an API that clicks on the use passwords button
