### ISSUE TITLE
[BUG] Randomly fails when running from Task Scheduler

### ISSUE THREAD

**Issue by donovanj44** [charlesbel/Microsoft-Rewards-Farmer#92]
*MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE*

**Error Log**
Traceback (most recent call last):
  File "C:\Users\josep\Microsoft-Rewards-Farmer\ms_rewards_farmer.py", line 800, in <module>
    completeMorePromotions(browser)
  File "C:\Users\josep\Microsoft-Rewards-Farmer\ms_rewards_farmer.py", line 681, in completeMorePromotions
    morePromotions = getDashboardData(browser)['morePromotions']
  File "C:\Users\josep\Microsoft-Rewards-Farmer\ms_rewards_farmer.py", line 479, in getDashboardData
    dashboard = json.loads(dashboard)
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Screenshot of the page**
https://imgur.com/a/agDqg2b

**Source code of dashboard**
Copy the source code of the [Microsoft Rewards Dashboard Page](https://account.microsoft.com/rewards) and paste it on [Gist](https://gist.github.com). Then share me the link of the gist here.
https://gist.github.com/donovanj44/38056cb7a6a05a5b690eaeb9c2c9d264 (Removed email and names for security)

This error randomly occurs when the task is ran, while sometimes the task completes fine, but this results in many overlapping windows.

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
