### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mouflon23** [charlesbel/Microsoft-Rewards-Farmer#96]
Error Log

Traceback (most recent call last):
  File "C:\Users\super\Downloads\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\super\Downloads\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 58, in login
    browser.find_element(By.ID, 'idSIButton9').click()
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\super\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: headless chrome=103.0.5060.114)

**Comment by farshadz1997** [comment]
This bug related to chrome 103 and it's nothing to do with bot, roll back to Chrome 102 or wait for Chrome 104 as they said it will fix in Chrome 104.

**Comment by farshadz1997** [comment]
I get the same error as you with even selenium 4.3.0

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
