### ISSUE TITLE
error please help[BUG]

### ISSUE THREAD

**Issue by Crysiz2631** [charlesbel/Microsoft-Rewards-Farmer#98]
**Error Log**
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Ensuring login on Bing...
Traceback (most recent call last):
  File "C:\Users\gronb\Desktop\files\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\gronb\Desktop\files\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 86, in login
    checkBingLogin(browser, isMobile)
  File "C:\Users\gronb\Desktop\files\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 91, in checkBingLogin
    browser.get('https://bing.com/')
  File "C:\Users\gronb\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\gronb\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gronb\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: headless chrome=104.0.5112.48)

**Screenshot of the page**
https://i.imgur.com/5U9FxPE.png

WHAT DO I DO

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
